City-of-Helsinki/drupal-helfi-platform-config

- features/helfi_base_config/helfi_base_config.info.yml
How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/17
> UFH-81 Branding selector

- composer.json
- features/helfi_base_config/helfi_base_config.info.yml
- features/helfi_languages/config/install/core.menu.static_menu_link_overrides.yml
- features/helfi_languages/config/install/language.content_settings.menu_link_content.menu_link_content.yml
How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi/pull/19
> UHF-31 Footer

- features/helfi_base_config/helfi_base_config.info.yml
How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/28
> UHF-223 Hyphenation

- features/helfi_base_config/helfi_base_config.install
- Switch to corresponding branch: 
- `composer require drupal/helfi_platform_config:dev-UHF-235-remove-node-frontpage`
- Try to access https://hel-platform.docker.sh/node - you should get 404.
> UHF-235 Remove /node view

- features/helfi_media/config/install/core.entity_view_display.media.image.list_of_links.yml
- features/helfi_media/config/install/core.entity_view_mode.media.list_of_links.yml
- features/helfi_media/config/install/responsive_image.styles.hero__background.yml
- features/helfi_media/config/install/responsive_image.styles.hero__bottom.yml
- features/helfi_media/config/install/responsive_image.styles.hero__diagonal.yml
- features/helfi_media/config/install/responsive_image.styles.hero__left_right.yml
- features/helfi_media/config/install/responsive_image.styles.list_of_links__thumbnail.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.list_of_links.default.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.list_of_links_item.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.list_of_links.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.list_of_links_item.default.yml
- features/helfi_paragraphs/config/install/field.field.node.page.field_content.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.list_of_links.field_list_of_links_design.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.list_of_links.field_list_of_links_links.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.list_of_links.field_list_of_links_title.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.list_of_links_item.field_list_of_links_desc.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.list_of_links_item.field_list_of_links_image.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.list_of_links_item.field_list_of_links_link.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_list_of_links_desc.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_list_of_links_design.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_list_of_links_image.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_list_of_links_link.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_list_of_links_links.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_list_of_links_title.yml
- features/helfi_paragraphs/config/install/paragraphs.paragraphs_type.list_of_links.yml
- features/helfi_paragraphs/config/install/paragraphs.paragraphs_type.list_of_links_item.yml
- `composer require drupal/hdbt_admin:dev-UHF-251-list-of-links && composer require drupal/hdbt:dev-UHF-251-list-of-links && composer require drupal/helfi_platform_config:dev-UHF-251-list-of-links`
- Log in and add a basic page or edit existing one. You should now have list of links paragraph available for the content area.
- Try different options on the paragraph and check that it looks good on all resolutions and designs. There is plenty of options here.
- Also the admin theme should react to different designs by hiding obsolete fields when …
> UHF-251 List of links

- composer.json
- features/helfi_content/config/install/language/fi/social_media.settings.yml
- features/helfi_content/config/install/social_media.settings.yml
- features/helfi_content/helfi_content.info.yml
How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/37
> UHF-250 Social media

- features/helfi_content/config/install/editor.editor.full_html.yml
- features/helfi_content/config/install/filter.format.full_html.yml
- features/helfi_example_content/content/node/b62f70bb-3e19-4c21-be5e-621b96169fe1.yml
- features/helfi_example_content/content/node/dec562f5-ce02-4b24-bc43-47fffe513d27.yml
How to test: 
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/38
> UHF-205 Highlight quote

- features/helfi_base_config/config/install/language/fi/views.view.content.yml
- features/helfi_base_config/config/install/language/ru/views.view.content.yml
- features/helfi_base_config/config/install/language/sv/views.view.content.yml
- features/helfi_base_config/config/install/views.view.content.yml
> UHF-X Views content language column

- features/helfi_example_content/content/node/d450f779-4ed7-40ec-9184-9f2a46465dbe.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.columns.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.columns.default.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.columns.field_columns_design.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.columns.field_columns_left_column.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.columns.field_columns_right_column.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.columns.field_columns_title.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_columns_design.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_columns_left_column.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_columns_right_column.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_columns_title.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.columns.field_columns_design.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.columns.field_columns_left_column.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.columns.field_columns_right_column.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.columns.field_columns_title.yml
- features/helfi_paragraphs/config/install/language/fi/field.storage.paragraph.field_columns_design.yml
- features/helfi_paragraphs/config/install/language/fi/paragraphs.paragraphs_type.columns.yml
- features/helfi_paragraphs/config/install/paragraphs.paragraphs_type.columns.yml
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/43
> UHF-650 Columns paragraph

- features/helfi_content/config/install/field.field.node.article.field_content.yml
- features/helfi_content/config/install/field.field.node.page.field_content.yml
- features/helfi_example_content/content/node/b62f70bb-3e19-4c21-be5e-621b96169fe1.yml
- features/helfi_example_content/content/node/d450f779-4ed7-40ec-9184-9f2a46465dbe.yml
- features/helfi_media/config/install/core.entity_view_display.media.image.image.yml
- features/helfi_media/config/install/image.style.1_1_thumbnail.yml
- features/helfi_media/config/install/image.style.1_1_thumbnail_2x.yml
- features/helfi_media/config/install/responsive_image.styles.gallery_thumbnail.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.gallery.default.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.gallery_slide.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.gallery.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.gallery_slide.default.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.gallery.field_gallery_slides.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.gallery_slide.field_gallery_slide_caption.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.gallery_slide.field_gallery_slide_media.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_gallery_slide_caption.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_gallery_slide_media.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_gallery_slides.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.gallery.field_gallery_slides.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.gallery_slide.field_gallery_slide_caption.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.gallery_slide.field_gallery_slide_media.yml
- features/helfi_paragraphs/config/install/language/fi/paragraphs.paragraphs_type.gallery.yml
- features/helfi_paragraphs/config/install/language/fi/paragraphs.paragraphs_type.gallery_slide.yml
- features/helfi_paragraphs/config/install/paragraphs.paragraphs_type.gallery.yml
- features/helfi_paragraphs/config/install/paragraphs.paragraphs_type.gallery_slide.yml
The instructions are written in here how to test this on platform:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/45
Also check these PRs:
https://github.com/City-of-Helsinki/drupal-helfi/pull/50
> UHF-201 Gallery

- features/helfi_example_content/content/node/0f14edf8-bb60-4c3b-8d02-4433aac0d3e6.yml
- features/helfi_example_content/content/node/3a313b2f-8b70-41a6-a655-3f9805cb1f48.yml
- features/helfi_example_content/content/node/77e5183c-4d25-447e-a4e1-58776b2b545b.yml
- features/helfi_example_content/content/node/7f3b3413-fbf6-4f0b-873c-1fafd3c7912f.yml
- features/helfi_example_content/content/node/8455251b-91bd-4c71-9756-94112e8912c1.yml
- features/helfi_example_content/content/node/b62f70bb-3e19-4c21-be5e-621b96169fe1.yml
- features/helfi_example_content/content/node/c2b41989-c715-4ec4-8df1-42655293fdfc.yml
- features/helfi_example_content/content/node/d450f779-4ed7-40ec-9184-9f2a46465dbe.yml
- features/helfi_example_content/content/node/d5bf4eac-26d6-420e-bd19-7d66ff969181.yml
- features/helfi_example_content/content/node/dec562f5-ce02-4b24-bc43-47fffe513d27.yml
- features/helfi_example_content/content/node/efc11410-25ca-48ef-bfe0-f03860a3b7e7.yml
Check that the node paths will be generated when example content is created.
> UHF-X Example content pathauto

- features/helfi_content/config/install/field.field.node.article.field_author.yml
- features/helfi_content/config/install/field.field.node.landing_page.field_liftup_image.yml
- features/helfi_content/config/install/field.field.node.page.field_liftup_image.yml
- features/helfi_content/config/install/filter.format.full_html.yml
- features/helfi_media/helfi_media.info.yml
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/22
> UHF-760 All languages

- .github/workflows/ci.yml
- composer.json
- features/helfi_content/config/install/social_media.settings.yml
- helfi_platform_config.info.yml
- helfi_platform_config.services.yml
- src/Menu/FilterByLanguage.php
- tests/src/Functional/MenuLanguageTest.php
- `composer require drupal/helfi_platform_config:dev-UHF-181`
- `drush en helfi_platform_config`
> UHF-181: Hide untranslated menu links

- src/Menu/FilterByLanguage.php
Check that only the main menu is processed to display only the viewed language menu links.
> UHF-X Whitelisted only the main menu to be processed

- composer.json
- features/helfi_base_config/config/install/diff.settings.yml
- features/helfi_base_config/helfi_base_config.info.yml
- features/helfi_content/config/install/core.entity_view_display.node.article.default.yml
- features/helfi_content/config/install/field.field.node.article.field_content.yml
- features/helfi_content/config/install/field.field.node.page.field_content.yml
- features/helfi_media/config/install/core.entity_view_display.media.image.hero.yml
- features/helfi_media/config/install/core.entity_view_mode.media.hero.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.hero.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.accordion.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.banner.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.columns.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.gallery_slide.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.hero.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.image.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.liftup_with_image.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.list_of_links.default.yml
- `composer require drupal/helfi_platform_config:dev-UHF-922-revisions && composer require drupal/hdbt:dev-UHF-922-revisions && composer require drupal/hdbt_admin:dev-UHF-922-revisions`
- Go to any example content page and make changes to the content. Change paragraphs, texts, pictures, order etc. If you make a HUGE amount of changes at once the diff can be quite wild so maybe make just some for starters.
- Save the content and choose the "Revisions" tab next to "Edit" tab on the node actions.
- You should now see on the revisions that there …
> UHF-922 Revisions

- features/helfi_example_content/content/node/b62f70bb-3e19-4c21-be5e-621b96169fe1.yml
- features/helfi_example_content/content/node/f4742487-e239-4b53-bbe6-18ebcef89069.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.banner.default.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.hero.default.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.list_of_links_item.default.yml
- features/helfi_paragraphs/helfi_paragraphs.info.yml
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi/pull/72
> UHF-927 External link

- features/helfi_base_config/config/install/system.menu.main.yml
Testing instructions: https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/31
Also check:
https://github.com/City-of-Helsinki/drupal-helfi/pull/82
> UHF-80: Change main menu language to und

- features/helfi_content/config/install/core.entity_form_display.node.page.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.accordion.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.banner.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.columns.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.content_cards.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.hero.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.liftup_with_image.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.list_of_links.default.yml
- `composer require drupal/helfi_platform_config:dev-UHF-886_paragraph_design && composer require drupal/hdbt_admin:dev-UHF-886_paragraph_design && make new`
- Login and go to create new landing page (or edit old one).
- Add or edit the following paragraphs: Hero, Columns, Banner, List of links, Liftup with image and Content cards
- Check that there is a new design widget for each of these fields and that it works. 
- Go to create new Page (or edit old one).   
- Add or edit the following paragraphs: Accordion
- Check that …
> UHF-886 Paragraph design

- composer.json
- features/helfi_base_config/config/install/easy_breadcrumb.settings.yml
- features/helfi_base_config/helfi_base_config.info.yml
- features/helfi_content/config/install/filter.format.full_html.yml
- features/helfi_example_content/content/node/cfd766be-5fb5-4c70-877b-a41ca0cbd9b4.yml
- features/helfi_example_content/content/node/f7fbd889-a04d-4f4b-b127-4177fc48d3fb.yml
- features/helfi_services/config/install/core.base_field_override.node.service.promote.yml
- features/helfi_services/config/install/core.base_field_override.node.service.title.yml
- features/helfi_services/config/install/core.entity_form_display.node.service.default.yml
- features/helfi_services/config/install/core.entity_view_display.node.service.default.yml
- features/helfi_services/config/install/core.entity_view_display.node.service.parent_service.yml
- features/helfi_services/config/install/core.entity_view_display.node.service.teaser.yml
- features/helfi_services/config/install/core.entity_view_mode.node.parent_service.yml
- features/helfi_services/config/install/field.field.node.service.field_service_is_parent.yml
- features/helfi_services/config/install/field.field.node.service.field_service_long_description.yml
- features/helfi_services/config/install/field.field.node.service.field_service_parent_service.yml
- features/helfi_services/config/install/field.field.node.service.field_service_short_description.yml
- features/helfi_services/config/install/field.field.node.service.field_service_visible_title.yml
- features/helfi_services/config/install/field.storage.node.field_service_is_parent.yml
- features/helfi_services/config/install/field.storage.node.field_service_long_description.yml
- features/helfi_services/config/install/field.storage.node.field_service_parent_service.yml
- features/helfi_services/config/install/field.storage.node.field_service_short_description.yml
- features/helfi_services/config/install/field.storage.node.field_service_visible_title.yml
- features/helfi_services/config/install/language.content_settings.node.service.yml
- features/helfi_services/config/install/node.type.service.yml
- features/helfi_services/config/install/pathauto.pattern.service_page_pattern.yml
- features/helfi_services/helfi_services.features.yml
- features/helfi_services/helfi_services.info.yml
- helfi_platform_config.module
- `composer require drupal/helfi_platform_config:dev-UHF-1090_services && composer require drupal/hdbt:dev-UHF-1090_services && composer require drupal/hdbt_admin:dev-UHF-1090_services`
- Run `make shell`
- `cd public`
- First you need to enable helfi_tpr module since it is not on by default in platform:`drush en helfi_tpr`
- Next you need to fetch some units and services from TPR: `MIGRATE_LIMIT=500 drush mim tpr_unit && drush mim tpr_service`
- `drush cr`
- Now you should have 500 units under the integrations tab "TPR …
> UHF-1090 Services

- features/helfi_gdpr_compliance/config/install/language/fi/eu_cookie_compliance.settings.yml
- translations/fi/strings.po
- translations/ru/strings.po
- translations/sv/strings.po
- Switch to corresponding branches: `composer require drupal/helfi_platform_config:dev-UHF-X-additional-translations`
- `make new`
- Go to front page with browser where you haven't accepted the cookies and check that the cookie consent is translated.
Also check this:
https://github.com/City-of-Helsinki/drupal-helfi/pull/101
> Added missing translations for the system

- features/helfi_base_config/config/install/views.view.content.yml
- translations/fi/strings.po
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi/pull/105
> UHF-1478 TPR lists

- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser_with_image.yml
- features/helfi_tpr_config/config/install/core.entity_view_mode.tpr_unit.teaser_with_image.yml
- features/helfi_tpr_config/config/install/views.view.unit_search.yml
- features/helfi_tpr_config/helfi_tpr_config.info.yml
https://github.com/City-of-Helsinki/drupal-helfi/pull/119
https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/30
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/95
> UHF-1046 Unit search layout

- translations/fi/strings.po
Instructions https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/47
> UHF-X Ckeditor Tel Link

- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- translations/fi/strings.po
Check instructions: https://github.com/City-of-Helsinki/drupal-hdbt/pull/101
> UHF-1597: Accessibility

- assets/js/reactAndShareSettings.js
- helfi_platform_config.libraries.yml
- helfi_platform_config.module
- src/Plugin/Block/ReactAndShare.php
- templates/react-and-share.html.twig
- `composer require drupal/hdbt:dev-UHF-433-react-and-share && composer require drupal/helfi_platform_config:dev-UHF-433-react-and-share`
- Go to edit your local.settings.php that can be found from public/sites/default/local.settings.php (create one if there isn't one) and add the following lines there: 
- `putenv('REACT_AND_SHARE_APIKEY_FI=abcdefgh12345678');`
- `putenv('REACT_AND_SHARE_APIKEY_EN=abcdefgh12345678');`
- `putenv('REACT_AND_SHARE_APIKEY_SV=abcdefgh12345678');`
- Ask the correct api-keys from Tero
- Log into …
> UHF-433 React and Share

- src/Menu/FilterByLanguage.php
Remove admin menu from filter by language menu link filteration because it breaks the toolbar
> UHF-X Remove admin menu from filter by language tool

- features/helfi_content/config/install/field.storage.paragraph.field_banner_design.yml
- features/helfi_content/config/install/language/fi/field.storage.paragraph.field_banner_design.yml
NOTICE: This should be tested after the https://github.com/City-of-Helsinki/drupal-hdbt/pull/118 PR is merged to avoid bugs related to the buttons.
Test with no previous setup:
1. Run the composer one liner to get the site: `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
2. Go to the newly created folder and switch to correct branch: `composer require drupal/helfi_platform_config:dev-UHF-1731-banner-paragraph-changes && composer require drupal/hdbt:dev-UHF-1731-banner-paragraph-changes && composer require drupal/hdbt_admin:dev-UHF-1731-banner-paragraph-changes`
3. Get the site running: `make new`
4. Log in to the site using the link that the install gives and go to create a new …
> UHF-1731: Banner paragraph changes

- features/helfi_content/config/install/field.storage.paragraph.field_liftup_with_image_design.yml
- features/helfi_content/config/install/language/fi/field.storage.paragraph.field_liftup_with_image_design.yml
NOTICE: This should be tested and merged AFTER the https://github.com/City-of-Helsinki/drupal-hdbt/pull/120 is merged to avoid conflicts since this feature is partly based on the work done it that PR.
Test with no previous setup:
1. Run the composer one liner to get the site: `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
2. Go to the newly created folder and switch to correct branch: `composer require drupal/helfi_platform_config:dev-UHF-1730-liftup-with-image-paragraph-changes && composer require drupal/hdbt:dev-UHF-1730-liftup-with-image-paragraph-changes && composer require drupal/hdbt_admin:dev-UHF-1730-liftup-with-image-paragraph-changes`
3. Get the site running: `make new`
4. …
> UHF-1730: Liftup with image paragraph changes

- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_errand_service.tpr_errand_service.default.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_service.tpr_service.default.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_service_channel.tpr_service_channel.default.yml
1. Set up local project:
2. Checkout correct branches:
- `composer require drupal/helfi_tpr:dev-UHF-1410_palvelusivu` (see PR: https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/45)
- `composer require drupal/helfi_platform_config:dev-UHF-1410_palvelusivu` (this PR)
3. Build the site:
- `make new`
4. Enable `helfi_tpr_config` feature:
- `make shell`
- `drush en -y helfi_tpr_config`
5. Import some TPR entities (set `MIGRATE_LIMIT=500` or similar if seen fit):
- `drush migrate:import tpr_service`
- `drush migrate:import tpr_errand_service`
- `drush migrate:import tpr_service_channel`
6. Clear cache:
- …
> UHF-1410: palvelusivu (config)

- composer.json
- features/helfi_content/config/install/core.entity_form_display.paragraph.content_liftup.default.yml
- features/helfi_content/config/install/core.entity_view_display.paragraph.content_liftup.default.yml
- features/helfi_content/config/install/field.field.node.landing_page.field_content.yml
- features/helfi_content/config/install/field.field.node.page.field_content.yml
- features/helfi_content/config/install/field.field.node.page.field_lower_content.yml
- features/helfi_content/config/install/field.field.paragraph.content_liftup.field_content_liftup_content.yml
- features/helfi_content/config/install/field.storage.paragraph.field_content_liftup_content.yml
- features/helfi_content/config/install/language/fi/field.field.paragraph.content_liftup.field_content_liftup_content.yml
- features/helfi_content/config/install/language/fi/paragraphs.paragraphs_type.content_liftup.yml
- features/helfi_content/config/install/paragraphs.paragraphs_type.content_liftup.yml
- features/helfi_content/helfi_content.info.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser_with_image.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.wide_teaser.yml
- features/helfi_tpr_config/config/install/core.entity_view_mode.tpr_unit.wide_teaser.yml
- features/helfi_tpr_config/config/install/views.view.der_tpr_unit.yml
- features/helfi_tpr_config/config/rewrite/core.entity_view_display.paragraph.content_liftup.default.yml
- features/helfi_tpr_config/config/rewrite/field.field.paragraph.content_liftup.field_content_liftup_content.yml
- features/helfi_tpr_config/config/rewrite/field.storage.paragraph.field_content_liftup_content.yml
- `composer require drupal/hdbt:dev-UHF-1181_content_liftup && composer require drupal/hdbt_admin:dev-UHF-1181_content_liftup && composer require drupal/helfi_platform_config:dev-UHF-1181_content_liftup && composer require drupal/helfi_tpr:dev-UHF-1181_content_liftup`
- Run `make shell`
- Run `drush en -y helfi_tpr_config`
- Run `MIGRATE_LIMIT=500 drush mim tpr_unit` 
- Run `drush cr`
- Run `drush uli` and log into the site.
- Go to unit listing and check what units the importer took for you from TPR. Publish one or two of …
> UHF-1181 Content liftup

- composer.json
Uninstall dynamic entity reference
> UHF-1181 Content liftup revert #2

- features/helfi_tpr_config/config/install/core.entity_form_display.paragraph.service_list.default.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.paragraph.service_list.default.yml
- features/helfi_tpr_config/config/install/field.field.paragraph.service_list.field_service_list_description.yml
- features/helfi_tpr_config/config/install/field.field.paragraph.service_list.field_service_list_meta_load_mor.yml
- features/helfi_tpr_config/config/install/field.field.paragraph.service_list.field_service_list_services.yml
- features/helfi_tpr_config/config/install/field.field.paragraph.service_list.field_service_list_title.yml
- features/helfi_tpr_config/config/install/field.storage.paragraph.field_service_list_description.yml
- features/helfi_tpr_config/config/install/field.storage.paragraph.field_service_list_meta_load_mor.yml
- features/helfi_tpr_config/config/install/field.storage.paragraph.field_service_list_services.yml
- features/helfi_tpr_config/config/install/field.storage.paragraph.field_service_list_title.yml
- features/helfi_tpr_config/config/install/language/fi/field.field.paragraph.service_list.field_service_list_description.yml
- features/helfi_tpr_config/config/install/language/fi/field.field.paragraph.service_list.field_service_list_meta_load_mor.yml
- features/helfi_tpr_config/config/install/language/fi/field.field.paragraph.service_list.field_service_list_services.yml
- features/helfi_tpr_config/config/install/language/fi/field.field.paragraph.service_list.field_service_list_title.yml
- features/helfi_tpr_config/config/install/language/fi/paragraphs.paragraphs_type.service_list.yml
- features/helfi_tpr_config/config/install/paragraphs.paragraphs_type.service_list.yml
- features/helfi_tpr_config/config/install/views.view.service_list.yml
- features/helfi_tpr_config/config/rewrite/field.field.node.landing_page.field_content.yml
- `composer require drupal/hdbt:dev-UHF-2088_service_list && composer require drupal/helfi_platform_config:dev-UHF-2088_service_list`
- There might be a bug with `entity.path_alias.collection` not existing, so you might need to run `make drush-cr`
- Log in to the site with the link provided by installation process
- Open the terminal and run `make shell`
- Run `drush en -y helfi_tpr_config && MIGRATE_LIMIT=50 drush mim tpr_service && drush cr` 
- Go to service listing and publish a bunch of them (more than 4)
- Go to add a …
> UHF-2088 Service list

- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- translations/fi/strings.po
Related to [drupal-module-helfi-tpr/pull/44](https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/44). Please check that for instructions.
> UHF-2014 Missing email and link

- translations/fi/strings.po
How to test:
1. Install fresh `drupal-helfi` environment
2. Import some TPR Services, TPR Errand Services and TPR Service Channels
3. Get the latest theme changes: `composer update`
4. Checkout this branch: `composer require drupal/helfi_platform_config:dev-UHF-1410_palvelusivu_translations`
5. Import translations: `make drush-locale-update`
6. Clear cache: `make drush-cr`
7. Navigate to some TPR Service page (for example https://helfi.docker.so/fi/asukaspysakointi) to see the translated strings
> UHF-1410: Palvelusivu (translations)

- composer.json
- features/helfi_content/config/install/core.entity_form_display.node.page.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.sidebar_text.default.yml
- features/helfi_content/config/install/core.entity_view_display.node.page.default.yml
- features/helfi_content/config/install/core.entity_view_display.node.page.teaser.yml
- features/helfi_content/config/install/core.entity_view_display.paragraph.sidebar_text.default.yml
- features/helfi_content/config/install/editor.editor.minimal.yml
- features/helfi_content/config/install/field.field.node.page.field_sidebar_content.yml
- features/helfi_content/config/install/field.field.paragraph.sidebar_text.field_sidebar_text_text.yml
- features/helfi_content/config/install/field.field.paragraph.sidebar_text.field_sidebar_text_title.yml
- features/helfi_content/config/install/field.storage.node.field_sidebar_content.yml
- features/helfi_content/config/install/field.storage.paragraph.field_sidebar_text_text.yml
- features/helfi_content/config/install/field.storage.paragraph.field_sidebar_text_title.yml
- features/helfi_content/config/install/filter.format.minimal.yml
- features/helfi_content/config/install/language/fi/field.field.node.page.field_sidebar_content.yml
- features/helfi_content/config/install/language/fi/field.field.paragraph.sidebar_text.field_sidebar_text_text.yml
- features/helfi_content/config/install/language/fi/field.field.paragraph.sidebar_text.field_sidebar_text_title.yml
- features/helfi_content/config/install/language/fi/paragraphs.paragraphs_type.sidebar_text.yml
- features/helfi_content/config/install/paragraphs.paragraphs_type.sidebar_text.yml
- features/helfi_content/config/install/user.role.authenticated.yml
- features/helfi_content/helfi_content.info.yml
- features/helfi_tpr_config/config/install/core.entity_form_display.tpr_service.tpr_service.default.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_service.tpr_service.default.yml
- features/helfi_tpr_config/config/install/core.entity_view_display.tpr_service.tpr_service.teaser.yml
- features/helfi_tpr_config/config/install/field.field.tpr_service.tpr_service.field_sidebar_content.yml
- features/helfi_tpr_config/config/install/field.storage.tpr_service.field_sidebar_content.yml
- features/helfi_tpr_config/config/install/language/fi/field.field.tpr_service.tpr_service.field_sidebar_content.yml
- `composer require drupal/hdbt:dev-UHF-1736_sidebar_content && composer require drupal/helfi_platform_config:dev-UHF-1736_sidebar_content && composer require drupal/helfi_tpr:dev-UHF-1736_sidebar_content`
- There might be a bug with `entity.path_alias.collection` not existing, so you might need to run `make drush-cr`
- Log in to the site with the link provided by installation process
- Open the terminal and run `make shell`
- Run `drush en -y helfi_tpr_config && MIGRATE_LIMIT=50 drush mim tpr_service && drush cr` 
- Go to …
> UHF-1736 Sidebar content

- assets/css/smartti_chat.css
- helfi_platform_config.libraries.yml
Check instructions here: https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/94
> UHF-2700: Enable smartti chat on KYMP

- assets/js/genesys_chat.js
Changed a backend URL & enabled debug mode for testing.
> UHF-2478: genesys testing

- helfi_platform_config.libraries.yml
How to test:
* Test with local kymp environment.
* Get the change: `composer require drupal/helfi_platform_config:dev-UHF-3261-smartti-chat-changes`
* Load a page that includes the Smartti chatbot.
* Using the source, check that the script tag uses async:
`<script src="https://cdn.smartifik.com/files/clients/helsingin_kaupunki/smartti_client.js" async></script>`
> UHF-3261: Use async attribute with Smartti chatbot

- translations/fi/strings.po
Check City-of-Helsinki/drupal-module-helfi-tpr#87 for instructions.
> UHF-3450: Add translations for school settings

- translations/fi/strings.po
Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/238
> UHF-X Errand service translations

- helfi_features/helfi_tpr_config/config/update/helfi_tpr_config_update_9017.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
- translations/fi/strings.po
- translations/sv/strings.po
- Configs for the field in TPR Unit
- Translations moved to helfi_tpr module
> UHF-3821: 'Show website link' checkbox for TPR Unit edit form

- helfi_features/helfi_base_config/config/language/fi/system.maintenance.yml
- helfi_features/helfi_base_config/config/language/sv/system.maintenance.yml
- helfi_features/helfi_base_config/config/optional/system.maintenance.yml
- helfi_features/helfi_base_config/config/update/helfi_base_config_update_9006.yml
- helfi_features/helfi_base_config/helfi_base_config.install
- helfi_features/helfi_base_config/translations/fi.po
- helfi_features/helfi_base_config/translations/sv.po
**Check instructions from here:**
https://github.com/City-of-Helsinki/drupal-hdbt/pull/244
**Also check these PRs:**
https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/69
https://github.com/City-of-Helsinki/drupal-helfi-asuminen/pull/36
https://github.com/City-of-Helsinki/drupal-helfi-tyo-yrittaminen/pull/44
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/301
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/291
https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/211
> UHF-3627: Add update hook to change the maintenance text for the correct version

- helfi_features/helfi_base_config/helfi_base_config.install
- helfi_features/helfi_charts/helfi_charts.install
- helfi_features/helfi_content/helfi_content.install
- helfi_features/helfi_news_item/helfi_news_item.install
Bug fix for Helfi Charts translations.
> Added update hook for installing Helfi Chart module translations.

- assets/js/genesys_neuvonta.js
- helfi_platform_config.libraries.yml
- src/Plugin/Block/GenesysNeuvonta.php
Genesys chat for Neuvonta pages (debug enabled.)
> UHF-4778: Genesys chat for Neuvonta pages

- composer.json
Reverts City-of-Helsinki/drupal-helfi-platform-config#280
> Revert "UHF-X Allowed formats post update"

- translations/new/fi.po
- translations/new/sv.po
Added translations for daycare search filter options.
* Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/128
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/128
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/111
> UHF-4529: Vare translations

- helfi_features/helfi_content/config/update/helfi_content_update_9027.yml
- helfi_features/helfi_content/helfi_content.install
- helfi_features/helfi_tpr_config/config/update/helfi_tpr_config_update_9025.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
Check instructions from 
- https://github.com/City-of-Helsinki/drupal-hdbt/pull/289
> UHF-3884 Sidebar

- helfi_features/helfi_tpr_config/helfi_tpr_config.install
Moved field installation from TPR module update hook to HDBT admin editorial post update hook
> UHF-3884: Sidebar fix 

- helfi_features/helfi_content/config/optional/social_media.settings.yml
- helfi_features/helfi_content/helfi_content.install
Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt/pull/299
> UHF-5126: Social media wsod

- assets/js/genesys_neuvonta.js
- translations/new/fi.po
- translations/new/sv.po
Relates to https://github.com/City-of-Helsinki/drupal-hdbt/pull/328
> UHF-5228: replace genesys chat link with a button

- helfi_platform_config.libraries.yml
Changed the Watson chatbot endpoint URLs.
> UHF-6087: Watson chatbot update

- helfi_features/helfi_content/helfi_content.install
* Fixed update hook where there was wrong function called
> Fixed update hook where there was wrong function called

- helfi_features/helfi_content/config/update/helfi_content_update_9032.yml
* Fixes indentation issue in update file
> Fixes indentation issue in update file

- helfi_features/helfi_news_feed/helfi_news_feed.module
* [Fixed null coalescing operator.](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/commit/bc5dc7de537b58fa9a353ff183ea097e2eaf5695)
> Fixed null coalescing operator.

- helfi_features/helfi_toc/helfi_toc.module
* Added toc for content type district
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6137-district-content-type`
* See KYMP PR
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/417
> UHF-6137: Added toc for district

- helfi_features/helfi_navigation/assets/schema.json
- helfi_features/helfi_navigation/config/optional/block.block.external_menu_mega_menu.yml
- helfi_features/helfi_navigation/config/optional/block.block.external_menu_mobile_menu__fallback.yml
- helfi_features/helfi_navigation/helfi_navigation.install
- helfi_features/helfi_navigation/helfi_navigation.module
- helfi_features/helfi_navigation/src/ExternalMenuTreeFactory.php
- helfi_features/helfi_navigation/src/Plugin/Block/ExternalMenuBlockBase.php
- helfi_features/helfi_navigation/templates/menu--external-menu--mega.html.twig
- helfi_features/helfi_navigation/templates/menu--external-menu--mobile--fallback.html.twig
- helfi_features/helfi_navigation/templates/menu--external-menu.html.twig
> Uhf 6038 menu data syncing temp

- composer.json
- patches/field_group_fix-translations_label_description-3111107-31-rerolled.patch
Re-rolled field group title translations patch.
> UHF-X Field group patch

- composer.json
- patches/paragraphs_asymmetric_translation_widgets-3310368-check-for-subform.patch
Added check for subforms in paragraphs asymmetric widget forms to fix the problem with pseudo paragraphs.
> UHF-X Paragraphs asymmetric patch

- helfi_features/helfi_news_feed/config/install/core.entity_form_display.paragraph.news_list.default.yml
- helfi_features/helfi_news_feed/helfi_news_feed.install
Changes the weight of two fields in the News list paragraph.
> UHF-X: news list paragraph field weights

- helfi_platform_config.module
* Check if the current project is not in environments list before handling Etusivu links
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6960_fix_for_non_helfi_project`
* `$config['helfi_api_base.environment_resolver.settings']['project_name'] = 'my_awesome_project'; ` 
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/459
> UHF-6960: Fix for non helfi project

- composer.json
* Removed paragraphs asymmetric translations widget patch as it was included in latest release.
> UHF-X Remove obsolete paragraphs patch

- helfi_features/helfi_media_map_config/translations/fi.po
- helfi_features/helfi_media_map_config/translations/sv.po
* [Added translations for helfi media map ui.](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/commit/17854dea19bd8e25e9af257462e9cc2bbcd13c5b)
* https://github.com/City-of-Helsinki/drupal-module-helfi-media-map/pull/5
[UHF-7823]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7823 Media map UI translation

- helfi_features/helfi_react_search/helfi_react_search.module
- helfi_features/helfi_react_search/src/Plugin/search_api/processor/IsSchool.php
- helfi_features/helfi_react_search/src/Plugin/search_api/processor/MediaReferenceToObject.php
Backend logic to school search.
Check testing info here: https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/297
[UHF-6836]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6836: School search base

- helfi_features/helfi_content/config/install/filter.format.full_html.yml
- helfi_features/helfi_content/config/install/filter.format.minimal.yml
- helfi_features/helfi_content/helfi_content.info.yml
- helfi_features/helfi_content/helfi_content.install
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7882`
[UHF-7882]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7882: Removed token_filter and aet modules in preparation for 3.x release

- helfi_features/helfi_react_search/helfi_react_search.module
- helfi_features/helfi_react_search/src/Plugin/search_api/processor/Coordinates.php
- helfi_features/helfi_react_search/src/Plugin/search_api/processor/IsSchool.php
- helfi_features/helfi_react_search/src/SupportsUnitIndexTrait.php
Adds supporting backend functionality to school search paragraph.
- Add new processor "Coordinates" (for indexing coordinates data)
- Make a trait out of `supportsIndex` method for defining processors for tpr unit datasourced indices
Check info here: https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/307
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/307
[UHF-6839]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6839: Adress filter

- helfi_features/helfi_react_search/translations/fi.po
- helfi_features/helfi_react_search/translations/sv.po
* Update transation string to be universal for react searches.
Check instructions from HDBT PR: https://github.com/City-of-Helsinki/drupal-hdbt/pull/553
[UHF-6667]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6667: update react search translations

- composer.json
* Rerolled patch for the admin toolbar for 9.5.4 https://www.drupal.org/project/drupal/issues/2313309
> UHF-X Admin toolbar patch re-roll

- modules/helfi_test_content/helfi_test_content.module
* See https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/460
[UHF-5924]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-5924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-5924 Custom test content (3.x)

- modules/helfi_node_news_item/helfi_node_news_item.tokens.inc
* [Added missing short-title token.](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/commit/8e068405f307a6e08006070c4e4a0efeb736d3e0)
> Added missing short-title token for news item.

- helfi_platform_config.module
- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/hdbt_admin_tools/src/Plugin/Validation/Constraint/HeroConstraint.php
- modules/hdbt_admin_tools/src/Plugin/Validation/Constraint/HeroConstraintValidator.php
- modules/hdbt_admin_tools/translations/fi.po
- modules/hdbt_admin_tools/translations/sv.po
* Added constraint for missing hero block entities in entity forms and enhanced the checks for the hero block to prevent missing H1 elements.
* `make fresh`
* Update the Helfi Platform config and the HDBT theme
* `composer require drupal/helfi_platform_config:dev-UHF-8128_missing_h1 drupal/hdbt:dev-UHF-8128_missing_h1`
* Import translations by running `drush locale:check; drush locale:update` in shell
* Go to create or edit a landing page
* Check the Hero checkbox and remove hero paragraph from the three dots
* Open `public/modules/contrib/helfi_platform_config/modules/hdbt_admin_tools/src/Plugin/Validation/Constraint/HeroConstraintValidator.php` in your IDE and comment the line …
> UHF-8128: Missing H1

- modules/helfi_paragraphs_banner/helfi_paragraphs_banner.install
Something goes wrong while updating the paragraphs.
`Error:   >  [error]  Call to undefined method Drupal\Core\Field\BaseFieldDefinition::save()  
`
* Added a check to make sure the object implements the ParagraphInterface with the wanted method.
* `make fresh`
* Before composer require, find or create one page with banner that has centered design and one that has centered secondary design.
* `composer require drupal/helfi_platform_config:dev-UHF-6469_Banner-updates`
[UHF-6469]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6469: Fix banner updating

- modules/hdbt_admin_tools/assets/js/modalWindowPosition.js
- modules/hdbt_admin_tools/assets/js/paragraphSelection.js
- modules/hdbt_admin_tools/assets/js/select2_icon.js
- modules/hdbt_admin_tools/hdbt_admin_tools.libraries.yml
- modules/helfi_toc/assets/js/tableOfContents.js
- modules/helfi_toc/helfi_toc.libraries.yml
* Use core/once instead of jQuery.once in hdbt_admin_tools javascripts
* Converted the table of contents to Vanilla JS.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8389_core_once`
Check that the following JS features still works
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/216
[UHF-8389]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8389: Core once

- documentation/development.md
- modules/helfi_global_announcement/helfi_global_announcement.module
* Added documentation for the custom blocks.
> Added documentation for the custom blocks.

- modules/helfi_toc/assets/js/tableOfContents.js
* Fixed type error: Cannot read properties of null (reading 'querySelecctorAll').
> UHF-X: ToC update

- composer.json
> Updated patches for 2.x.

- modules/helfi_react_search/src/Plugin/search_api/processor/DistrictImageAbsoluteUrl.php
- modules/helfi_react_search/src/Plugin/search_api/processor/ProjectExecutionSchedule.php
- modules/helfi_react_search/src/Plugin/search_api/processor/ProjectImageAbsoluteUrl.php
- modules/helfi_react_search/src/Plugin/search_api/processor/ProjectPlanSchedule.php
* Add search api processors for district and project search
Check instructions from KYMP PR: https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/647
[UHF-7788]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7788: Add search api processors for district and project search

- composer.json
Updated versions
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8616`
**Allowed formats:**
Go add a new long text field to any content type. 
Change the "full html" / "filtered html". 
Save the field settings. 
Go edit or create new content and save it. It should work. 
**Focal point:**
Check out any image on any page. 
Go to edit the media entity, edit the focal point and save the media.
Run `drush cr` just in case
Go to check the same page again. the image should have been updated
**SiteImprove:**
https://helsinkisolutionoffice.atlassian.net/browse/UHF-1172 
**Social media:**
Go to any page with social …
> UHF-8618 update contrib modules to D10 compatible version

- helfi_platform_config.module
* Add check for hero block visibility based on the field_has_hero value
* Make sure your instance is up and running on latest dev branch and has the latest database from testing. For example SOTE is good for testing this.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8729_hero_access_fix`
[UHF-8729]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8729: Fix for hero block access checks

- modules/helfi_paragraphs_hero/config/install/field.storage.paragraph.field_hero_design.yml
- modules/helfi_paragraphs_hero/helfi_paragraphs_hero.api.php
- modules/helfi_paragraphs_hero/helfi_paragraphs_hero.install
- modules/helfi_paragraphs_hero/helfi_paragraphs_hero.module
Updates were not passing on front page instance because the allowed values list for hero is different for front page and other instances.
* Changed the hero paragraph field_hero_design to use function to define allowed values instead of the fixed list in the configuration.
* Make sure your instance is up and running on correct branch. First try with some other instance than front page, then check the front page instance PR.
* `git checkout dev`
* `make fresh`
* `make drush-cim drush-cr`
* `composer require drupal/helfi_platform_config:dev-UHF-1781_hero_designs_allowed_values_change`
* Run `make drush-cr drush-updb`
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/403
[UHF-1781]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
> UHF-1781: Change hero field_hero_design to use function for allowed values

- assets/js/reactAndShareSettings.js
* Added async attribute to react and share javascript.
* Fix minor issue with cookie compliance and react and share buttons being displayed briefly at the same time when accepting cookies
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8598_react_and_share_script_async`
[UHF-8598]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8598 React and Share (Askem) script async

- modules/helfi_global_announcement/src/Plugin/Block/GlobalAnnouncementsBlock.php
composer require drupal/helfi_platform_config:dev-UHF-8682
> UHF-8692: use uuid from external entity to prevent it from changing after cache clear

- modules/helfi_react_search/src/LinkedEvents.php
* Add comment to getPlacesList function
> UHF-X: add comment to getPlacesList function.

- modules/helfi_react_search/src/Plugin/Block/NewsArchiveBlock.php
Check installation / testing info here: https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/411
[UHF-8638]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8638: Add archive block code helfi_react_search module

- composer.json
- modules/helfi_global_announcement/config/install/external_entities.external_entity_type.helfi_announcements.yml
- modules/helfi_global_announcement/helfi_global_announcement.install
- modules/helfi_global_announcement/helfi_global_announcement.module
Reverts City-of-Helsinki/drupal-helfi-platform-config#518
> Revert "UHF-8525: Removed cron based cache invalidation in favor of automatic PubSub based cache invalidation"

- modules/helfi_paragraphs_contact_card_listing/src/Entity/ContactCard.php
Prevent error when contact card image is not set
> check for empty and return empty array if no image set

- helfi_platform_config.libraries.yml
* Needed to bump up the version number
> Bumped up the genesys_auth_redirect library version.

- modules/helfi_global_announcement/config/install/external_entities.external_entity_type.helfi_announcements.yml
- modules/helfi_global_announcement/helfi_global_announcement.install
- modules/helfi_global_announcement/helfi_global_announcement.module
See https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/518
> UHF-8525: Removed cron based cache invalidation in favor of automatic PubSub based cache invalidation

- modules/helfi_global_announcement/config/install/external_entities.external_entity_type.helfi_announcements.yml
- modules/helfi_global_announcement/helfi_global_announcement.install
- modules/helfi_global_announcement/helfi_global_announcement.module
- modules/helfi_global_announcement/src/Plugin/Block/GlobalAnnouncementsBlock.php
- modules/helfi_node_announcement/config/install/core.base_field_override.node.announcement.title.yml
- modules/helfi_node_announcement/config/install/core.entity_form_display.node.announcement.default.yml
- modules/helfi_node_announcement/config/install/core.entity_view_display.node.announcement.default.yml
- modules/helfi_node_announcement/config/install/core.entity_view_display.node.announcement.teaser.yml
- modules/helfi_node_announcement/config/install/field.field.node.announcement.field_announcement_title.yml
- modules/helfi_node_announcement/config/install/field.storage.node.field_announcement_title.yml
- modules/helfi_node_announcement/config/install/language/fi/field.field.node.announcement.field_announcement_title.yml
- modules/helfi_node_announcement/helfi_node_announcement.install
* Add new field announcement_title for screenreaders
* Check instructions from the HDBT PR.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/777
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/597
[UHF-8930]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8930: Add new field announcement_title for screenreaders

- composer.json
* Removed CKE4 contrib module (for D10)
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: Remove CKE4 contrib module.

- .github/workflows/ci.yml
- composer.json
- modules/helfi_ckeditor/config/install/filter.format.full_html.yml
* Removed colspan/rowspan from allowed attributes.
* Conflict if drush 11 is being installed.
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113 Drupal10 bug fixes v2

- modules/helfi_react_search/helfi_react_search.info.yml
- modules/helfi_toc/helfi_toc.info.yml
* Updated couple of old translation patterns that still had `helfi_features` there.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_update-translation-paths`
* Run `make drush-locale-update`
> Updated old translation paths.

- composer.json
- modules/hdbt_admin_tools/hdbt_admin_tools.module
Remove todo commented code and and replace it with service implementation. added conflicting api base version
> Use default language resolver

- modules/helfi_ckeditor/helfi_ckeditor.install
- modules/helfi_tpr_config/helfi_tpr_config.install
* Removed obsolete update hooks from Helfi ckeditor module.
* Remove duplicated update hooks from Helfi TPR config.
> UHF-X V3 update fixes

- modules/helfi_react_search/helfi_react_search.install
* Add update for job_listing reindex
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-5253_Job_location_filter`
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/380
[UHF-5253]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-5253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-5253: Add update for job_listing reindex

- modules/helfi_tpr_config/config/install/core.entity_form_display.paragraph.unit_search.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.paragraph.unit_search.default.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_search_results_term.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_search_results_terms.yml
- modules/helfi_tpr_config/config/install/field.storage.paragraph.field_search_results_term.yml
- modules/helfi_tpr_config/config/install/field.storage.paragraph.field_search_results_terms.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_search_results_term.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_search_results_terms.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Added new fields for unit search paragraph so that results texts can be altered from defaults.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9067`
* Update the hdbt-theme
* `composer require drupal/hdbt:dev-UHF-9067`
* Import translations `make drush-locale-update drush-cr`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/873
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/674
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/541
[UHF-9067]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> UHF-9067 New fields for unit search paragraph

- composer.json
- modules/helfi_global_announcement/src/Plugin/ExternalEntities/StorageClient/Announcements.php
- modules/helfi_paragraphs_news_list/src/HelfiExternalEntityBase.php
- modules/helfi_paragraphs_news_list/src/Plugin/ExternalEntities/StorageClient/News.php
- `composer require drupal/helfi_platform_config:dev-UHF-9639-v3`
> UHF-9639: Allow environment resolver to fail

- modules/helfi_base_content/config/optional/language/fi/metatag.metatag_defaults.front.yml
- modules/helfi_base_content/config/optional/language/fi/metatag.metatag_defaults.global.yml
- modules/helfi_base_content/config/optional/language/fi/metatag.metatag_defaults.node.yml
- modules/helfi_base_content/config/optional/language/fi/metatag.metatag_defaults.taxonomy_term.yml
- modules/helfi_tpr_config/config/install/views.view.locked_services.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.locked_services.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
- translations/override/fi.po
- translations/override/sv.po
* Added missing translations and updated faulty ones
[UHF-9088]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9088 Missing translations

- modules/helfi_base_content/config/optional/language/sv/metatag.metatag_defaults.front.yml
- modules/helfi_base_content/config/optional/language/sv/metatag.metatag_defaults.global.yml
- modules/helfi_base_content/config/optional/language/sv/metatag.metatag_defaults.node.yml
- modules/helfi_base_content/config/optional/language/sv/metatag.metatag_defaults.taxonomy_term.yml
- modules/helfi_node_announcement/config/optional/language/sv/core.base_field_override.node.announcement.promote.yml
- modules/helfi_node_announcement/config/optional/language/sv/field.field.node.announcement.field_announcement_all_pages.yml
- modules/helfi_node_landing_page/config/optional/language/sv/core.base_field_override.node.landing_page.promote.yml
- modules/helfi_node_landing_page/config/optional/language/sv/field.field.node.landing_page.field_has_hero.yml
- modules/helfi_node_landing_page/config/optional/language/sv/field.field.node.landing_page.field_hero.yml
- modules/helfi_node_landing_page/config/optional/language/sv/field.field.node.landing_page.field_liftup_image.yml
- modules/helfi_node_landing_page/config/optional/language/sv/field.field.node.landing_page.field_metatags.yml
- modules/helfi_node_news_item/config/optional/language/sv/core.base_field_override.node.news_item.promote.yml
- modules/helfi_node_news_item/config/optional/language/sv/core.base_field_override.node.news_item.status.yml
- modules/helfi_node_page/config/optional/language/sv/core.base_field_override.node.page.promote.yml
- modules/helfi_tpr_config/config/optional/language/sv/field.field.tpr_service.tpr_service.field_lower_content.yml
- modules/helfi_tpr_config/config/optional/language/sv/field.field.tpr_service.tpr_service.field_sidebar_content.yml
- modules/helfi_tpr_config/config/optional/language/sv/field.field.tpr_unit.tpr_unit.field_metatags.yml
- translations/override/fi.po
- translations/override/sv.po
* Added more missing translations
[UHF-9088]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9088 More translations

- modules/helfi_base_content/helfi_base_content.info.yml
* Added system module as a dependency for the helfi_base_content module.
> UHF-X Configuration rewrite fix

- modules/helfi_base_content/config/rewrite/easy_breadcrumb.settings.yml
* Don't rewrite any easy breadcrumb setting what is either similar to default value or the content is set in to the config ignore settings.
> UHF-X Easy breadcrumb revert

- .sonarcloud.properties
- helfi_platform_config.module
- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/helfi_paragraphs_hero/helfi_paragraphs_hero.api.php
- modules/helfi_paragraphs_hero/helfi_paragraphs_hero.module
- src/Plugin/Block/HeroBlock.php
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/572
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/735
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/280
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/945
[UHF-9738]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9738: news article content type

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
- modules/helfi_paragraphs_news_list/src/ElasticExternalEntityBase.php
- modules/helfi_paragraphs_news_list/tests/src/Kernel/ExternalEntityStorage/NewsStorageClientTest.php
- modules/helfi_paragraphs_news_list/tests/src/Kernel/ExternalEntityStorage/TermStorageClientTestBase.php
* `composer require drupal/helfi_platform_config:dev-UHF-10127`
* Run `drush cr`
> UHF-10127: Fixed OR queries

- modules/helfi_react_search/src/LinkedEvents.php
* Added missing page number to the query parameters in LinkedEvents.
> Hotfix: Added missing page number to the query parameters in LinkedEvents.

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
- modules/helfi_paragraphs_news_list/src/ClientBuilder.php
- modules/helfi_paragraphs_news_list/tests/src/Unit/ClientBuilderTest.php
- `composer require drupal/helfi_platform_config:dev-UHF-10339`
- Start Etusivu instance
> UHF-10339: Default to testing in case matching environment does not exist

- composer.json
> UHF-X: Replace patch

- composer.json
[UHF-10462]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10462: Add stage file proxy

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
When this PR is merged and deployed to testing the following changes need to be made manually to front page instance:
* Change the current news archive url to `/news/search-for-news` / `/uutiset/etsi-uutisia` / `/nyheter/sok-efter-nyheter` 
* Create a new landing page called `Current` and have it on the `/news` / `/uutiset` / `/nyheter` path.
* Changed the news archive base url to `/news/archive`.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10452`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/799
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/695
[UHF-10452]: …
> UHF-10452: Change the news list news archive base url again

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
* Fixed News groups filter 
* `composer require drupal/helfi_platform_config:dev-UHF-10472`
[UHF-10472]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10472: Filter by correct field

- helfi_platform_config.libraries.yml
* Added minified: true, to fix the issue with delivering non-aggregated JS files. See: https://www.drupal.org/project/drupal/issues/3416508
[UHF-10547]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10547: Preprocessing JS files

- modules/helfi_paragraphs_hero/src/Entity/Hero.php
* Bug fix for getting author translation if one exists.
[UHF-8670]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8670: Hero image author

- composer.json
* Updated tfa module to 1.8 on composer.json.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10589`
[UHF-10589]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10589: Make sure that tfa module is updated to secure version

- modules/helfi_test_content/config/rewrite/helfi_calculator.settings.yml
- modules/helfi_test_content/content/node/35a89867-7755-42e2-9eee-59929397d151.yml
- modules/helfi_test_content/helfi_test_content.info.yml
- modules/helfi_test_content/helfi_test_content.module
* Enable `helfi_etusivu_entities` module when test content is being installed and set the remote entity setting to false.
> UHF-X Test content fixes

- modules/helfi_image_styles/config/install/responsive_image.styles.unit_contact_card.yml
- modules/helfi_image_styles/helfi_image_styles.install
* Change unit contact card responsive image styles to match new look
* Check installation instructions from the [hdbt PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1082)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1082
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/827
[UHF-9508]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9508: Change unit contact card layout

- modules/helfi_base_content/helfi_base_content.install
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/181
[UHF-9982]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9982: Grant raven permissions

- composer.json
- patches/3486375.patch
Fixes DTT tests on etusivu.
Related to: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/838
> UHF-10719: Add patch for https://drupal.org/i/3486375

- modules/helfi_base_content/config/install/views.view.helfi_redirect.yml
- modules/helfi_base_content/config/optional/language/fi/views.view.helfi_redirect.yml
- modules/helfi_base_content/helfi_base_content.install
Few changed to view settings from acceptance testing.
- View is sortable with is_custom field.
- Show status field.
Added translations to pager.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10539-view-configuration`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/862
[UHF-10539]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10539 update view configuration

- modules/helfi_toc/assets/js/tableOfContents.js
* Fixes errors that have been coming in production to sentry
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10756 `
[UHF-10756]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10756: Added check if title components exist

- composer.json
* Updated the Gin toolbar to 2.0 version.
[UHF-10910]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10910: Updated the Gin toolbar to 2.0 version.

- modules/helfi_tpr_config/helfi_tpr_config.install
[Check this PR for instructions](https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/177)
[UHF-10352]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10352: update permissions for tpr entity deletion

- modules/hdbt_admin_tools/config/optional/language/fi/views.view.content.yml
- modules/hdbt_admin_tools/config/optional/language/sv/views.view.content.yml
- modules/hdbt_admin_tools/config/rewrite/views.view.content.yml
- modules/hdbt_admin_tools/hdbt_admin_tools.install
- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/helfi_base_content/config/optional/language/fi/views.view.locked_content.yml
- modules/helfi_base_content/config/optional/language/fi/views.view.scheduler_scheduled_content.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.locked_content.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.scheduler_scheduled_content.yml
- modules/helfi_base_content/config/rewrite/views.view.locked_content.yml
- modules/helfi_base_content/config/rewrite/views.view.scheduler_scheduled_content.yml
- modules/helfi_base_content/helfi_base_content.install
- modules/helfi_base_content/helfi_base_content.module
- modules/helfi_media/config/optional/language/fi/views.view.media.yml
- modules/helfi_media/config/optional/language/fi/views.view.media_library.yml
- modules/helfi_media/config/optional/language/sv/views.view.media_library.yml
- modules/helfi_media/config/rewrite/views.view.media_library.yml
- modules/helfi_media/helfi_media.install
- modules/helfi_media/helfi_media.module
- modules/helfi_tpr_config/config/optional/language/fi/views.view.tpr_errand_service_list.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.tpr_service_channel_list.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.tpr_service_list.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.tpr_unit_list.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
* Attempt to fix "Published" and "Unpublished" translations.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11222`
[UHF-11222]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Attempt to fix "Published" and "Unpublished" translations.

- modules/helfi_base_content/config/optional/language/fi/views.view.redirect.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.helfi_redirect.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.locked_content.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.redirect.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.scheduler_scheduled_content.yml
- modules/helfi_base_content/helfi_base_content.install
* Attempt to fix the SV translations for views.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11222`
[UHF-11222]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11222: Attempt to fix the SV translations for views.

- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_event_location.yml
- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_remote_events.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_event_location.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_remote_events.yml
- modules/helfi_react_search/helfi_react_search.install
* Removed requested descriptions from event paragraph fields
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11299`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1193
[UHF-11299]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11299: Changed texts and translations for linkedevents

- composer.json
* Removed patch concerning: https://www.drupal.org/project/elasticsearch_connector/issues/34863752
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_elastic_search_connector`
> UHF-X Elasticsearch connector

- documentation/development.md
* Added documentation of how to properly add configuration files and their translations
[UHF-11069]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11069 Documentation

- src/Plugin/Block/ContentBlockBase.php
- src/Plugin/Block/HeroBlock.php
- src/Plugin/Block/IbmChatApp.php
- src/Plugin/Block/LowerContentBlock.php
- src/Plugin/Block/ProfileBlock.php
- src/Plugin/Block/ReactAndShare.php
- src/Plugin/Block/SidebarContentBlock.php
- src/Plugin/Block/SocialMediaSharingBlock.php
- src/Plugin/Block/TeliaAceWidget.php
- tests/src/Unit/Block/BlockUnitTestBase.php
- tests/src/Unit/Block/ContentBlockTest.php
- tests/src/Unit/Block/HeroBlockTest.php
- tests/src/Unit/Block/IbmChatAppTest.php
- tests/src/Unit/Block/LowerContentBlockTest.php
- tests/src/Unit/Block/ProfileBlockTest.php
- tests/src/Unit/Block/ReactAndShareTest.php
- tests/src/Unit/Block/SidebarContentBlockTest.php
- tests/src/Unit/Block/SocialMediaSharingBlockTest.php
- tests/src/Unit/Block/TeliaAceWidgetTest.php
- tests/src/Unit/DefaultImageBuilderTest.php
* Coding standard fixes and added tests for blocks and default image builder.
[UHF-11069]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11069 Unit tests for blocks

- modules/helfi_media_map/src/Entity/HelMap.php
* Added function to check is provider is palvelukartta
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11472`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1214
[UHF-11472]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11472: Added getCookieConsentBypass for helfi map module

- modules/helfi_paragraphs_content_cards/helfi_paragraphs_content_cards.module
- modules/helfi_paragraphs_content_cards/src/Entity/ContentCards.php
* Add bundle class for content cards paragraph for the future.
* Check installation instructions from the [hdbt PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1221).
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/922
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1221
[UHF-11609]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11609: Small accessibility fixes for content cards and announcement

- modules/hdbt_admin_tools/config/install/hdbt_admin_tools.site_settings.yml
- modules/helfi_etusivu_entities/config/install/external_entities.external_entity_type.helfi_announcements.yml
- modules/helfi_etusivu_entities/config/install/external_entities.external_entity_type.helfi_surveys.yml
- modules/helfi_node_landing_page/config/install/core.entity_form_display.node.landing_page.default.yml
- modules/helfi_node_news_item/config/install/core.entity_form_display.node.news_item.default.yml
- modules/helfi_paragraphs_banner/config/install/core.entity_form_display.paragraph.banner.default.yml
- modules/helfi_paragraphs_hearings/config/install/external_entities.external_entity_type.helfi_hearings.yml
- modules/helfi_paragraphs_list_of_links/config/install/core.entity_form_display.paragraph.list_of_links_item.default.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news.yml
- modules/helfi_tpr_config/config/install/views.view.er_tpr_unit.yml
- modules/helfi_tpr_config/config/install/views.view.locked_services.yml
- modules/helfi_tpr_config/config/install/views.view.locked_units.yml
- modules/helfi_tpr_config/config/install/views.view.service_list.yml
- modules/helfi_tpr_config/config/install/views.view.service_units.yml
- modules/helfi_tpr_config/config/install/views.view.unit_search.yml
* Reordered configurations the way Drupal exports them.
> UHF-X Configuration reorder

- translations/override/fi.po
* Add and edit source text for content lock contrib module translations that are in platform config module
* Use **KYMP** and **Päätökset** instances to test this!
* Make sure your instance is up and running on the feature branch.
* `git fetch && git checkout origin UHF-11514`
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11514`
* Run drush magic to get all the translations on your local:
* Go to shell `make shell`
* In the shell, run `drush cim -y`
* Next run `drush locale:check && drush locale:update`
* And then `drush helfi:locale-import helfi_platform_config`
* Finally clear caches: `drush cr`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/931
* …
> UHF-11514: Translation fixes

- modules/helfi_base_content/helfi_base_content.module
* Grant anonymous user permissions to debug api
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/206
[UHF-11337]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11337: Grant anonymous user permissions to debug api

- composer.json
* This thing was fixed
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_stage_file_proxy -W`
> Updated stage file proxy to 3.1.5.

- modules/helfi_react_search/config/install/core.entity_form_display.paragraph.event_list.default.yml
- modules/helfi_react_search/config/install/core.entity_view_display.paragraph.event_list.default.yml
- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_language.yml
- modules/helfi_react_search/config/install/field.storage.paragraph.field_language.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_language.yml
- modules/helfi_react_search/helfi_react_search.install
Modify events list paragraph.
Check instructions here: https://github.com/City-of-Helsinki/drupal-hdbt/pull/1252
[UHF-11240]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11240: Add event language option to events list

- src/Plugin/Block/TeliaAceWidget.php
Updated telia ace chat block Chat ID field's help text to be more helpful
> UHF-11683: Updated field's help text

- composer.json
> UHF-X Oembed providers.

- helfi_platform_config.install
- helfi_platform_config.module
- modules/hdbt_cookie_banner/hdbt_cookie_banner.services.yml
- modules/hdbt_cookie_banner/src/Services/CookieSettings.php
- modules/hdbt_cookie_banner/tests/src/Kernel/Controller/HdbtCookieSettingsPageControllerTest.php
- modules/hdbt_cookie_banner/tests/src/Kernel/KernelTestBase.php
- modules/hdbt_cookie_banner/tests/src/Kernel/Services/CookieSettingsTest.php
- modules/helfi_etusivu_entities/src/Plugin/ExternalEntities/StorageClient/EtusivuJsonApiEntityBase.php
- modules/helfi_paragraphs_org_chart/src/OrgChartImporter.php
- modules/helfi_paragraphs_org_chart/tests/src/Unit/OrgChartImporterTest.php
- modules/helfi_paragraphs_org_chart/tests/src/Unit/OrgChartLazyBuilderTest.php
- modules/helfi_platform_config_base/helfi_platform_config_base.install
* Allow adding non-core instances to EnvironmentResolver
* Get päätökset url from environment resolver.
[UHF-11699]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- `make fresh` in päätökset in `dev` branch.
- `make fresh` in strategia.
- `composer require drupal/helfi_platform_config:dev-UHF-11699`
- `composer require drupal/helfi_api_base:dev-UHF-11699`
- `drush cr`
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/213.
[UHF-11178]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11699, UHF-11178

- composer.json
- helfi_platform_config.install
- modules/helfi_recommendations/src/EventSubscriber/SearchApiSubscriber.php
- patches/UHF-10647-search-api.patch
Enabling `helfi_recommendations` on all core sites.
* Make sure your https://github.com/City-of-Helsinki/drupal-helfi-asuminen instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10647_enable_recommendations`
* `composer update -W drupal/helfi_platform_config` (to patch `search_api`)
* `make drush-updb drush-cr`
[UHF-10647]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10647: Enable recommendations

- helfi_platform_config.install
* Fixed issue with: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/actions/runs/15047813236/job/42294832099
[UHF-10647]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10647: Phpstan

- modules/helfi_tfa/README.md
I added TFA to `helhist` project some time ago and spent bit too much time figuring this simple thing out. Thought I would've been happy to see it in README. Maybe this helps the next developer or future me.
> UHF-X: Add mention about TFA key for settings in README

- helfi_platform_config.install
* Make sure the new required module is installed.
* Make sure your palvelukeskus is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X-fix-palvelukeskus -W`
* Caused by: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/978.
> Install serialization module

- modules/helfi_react_search/config/install/field.storage.paragraph.field_event_list_type.yml
- modules/helfi_react_search/config/optional/language/fi/field.storage.paragraph.field_event_list_type.yml
- modules/helfi_react_search/helfi_react_search.info.yml
- modules/helfi_react_search/helfi_react_search.install
- modules/helfi_react_search/helfi_react_search.module
- modules/helfi_react_search/src/Enum/CourseCategory.php
- modules/helfi_react_search/src/Enum/EventCategory.php
- modules/helfi_react_search/src/Plugin/Field/FieldWidget/LinkedEventsSelect2Widget.php
- modules/helfi_react_search/translations/fi.po
- Fixed sentry issue: https://sentry.test.hel.ninja/organizations/city-of-helsinki/issues/25462/.
- Make update hooks idempodent.
- Use allowed_values_function in configuration.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9754`
* Run `drush helfi:platform-config:update helfi_react_search`
* Run `drush locale:check; drush locale:update`.
[UHF-9754]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9754: Fix crash when saving events list paragraph

- helfi_platform_config.install
* Enable stage_file_proxy on core instances
[UHF-11420]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11420: Enable stage_file_proxy on core instances

- modules/helfi_tpr_config/config/optional/language/sv/views.view.locked_units.yml
* Added Swedish translations for submit buttons.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9855`
* 
[UHF-9855]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9855: Translations

- modules/helfi_tpr_config/config/optional/language/fi/views.view.er_tpr_unit.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.locked_services.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.locked_units.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.service_list.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.service_units.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.unit_search.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.er_tpr_unit.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.locked_services.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.locked_units.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.service_list.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.service_units.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.tpr_errand_service_list.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.tpr_service_channel_list.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.tpr_service_list.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.tpr_unit_list.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.unit_search.yml
* Added Swedish translations and a missing translation file for locked services view.
* Removed redundant separators from translations.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9855`
[UHF-9855]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9855 Configuration translations

- modules/helfi_recommendations/src/Plugin/QueueWorker/QueueWorker.php
Lots of errors to sentry every time cron is run.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_missing_translation_error`
* run drush-cron
* No missing translation error
> prevent massive amount of errors by checking if translation exists

- helfi_platform_config.install
See https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1054
> Set update hook order

- modules/hdbt_admin_tools/hdbt_admin_tools.install
* Install editoria11y module if it's not installed.
[UHF-12206]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12206: Install editoria11y module if it's not installed.

- modules/helfi_paragraphs_news_list/templates/news-list--no-results.html.twig
* Wrap the no results text to li-element
* Check installation intructions from the [hdbt PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1388/files)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1388/files
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/1084
[UHF-12286]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12286: Fix no results text styles and html-dom in news-list paragraph

- composer.json
- modules/helfi_etusivu_entities/config/install/external_entities.external_entity_type.helfi_announcements.yml
- modules/helfi_etusivu_entities/config/install/external_entities.external_entity_type.helfi_surveys.yml
- modules/helfi_etusivu_entities/tests/src/Kernel/EtusivuJsonApiEntityTest.php
- modules/helfi_etusivu_entities/tests/src/Kernel/Plugin/Block/AnnouncementsBlockTest.php
- modules/helfi_etusivu_entities/tests/src/Kernel/Plugin/Block/BlockTestBase.php
- modules/helfi_etusivu_entities/tests/src/Kernel/Plugin/Block/SurveyBlockTest.php
- modules/helfi_paragraphs_curated_event_list/config/install/external_entities.external_entity_type.linkedevents_event.yml
- modules/helfi_paragraphs_hearings/config/install/external_entities.external_entity_type.helfi_hearings.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news_groups.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news_neighbourhoods.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news_tags.yml
- modules/helfi_paragraphs_news_list/tests/src/Kernel/Entity/NewsListLazyBuilderTest.php
- modules/helfi_paragraphs_news_list/tests/src/Kernel/KernelTestBase.php
* Update external entities to 3.0.0-beta6
* Fix tests (https://www.drupal.org/project/external_entities/issues/3549828)
* Make sure your instance is up and running on latest dev-branch
* `git checkout dev && git pull origin dev`
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-12039 -W`
* Run code updates
* `composer install`
* `make drush-updb`
* 
[UHF-12039]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12039: update external_entities
