City-of-Helsinki/drupal-helfi-platform-config

- features/helfi_media/config/install/core.entity_form_display.media.file.default.yml
- features/helfi_media/config/install/core.entity_form_display.media.file.media_library.yml
- features/helfi_media/config/install/core.entity_form_display.media.image.default.yml
- features/helfi_media/config/install/core.entity_form_display.media.image.media_library.yml
- features/helfi_media/config/install/core.entity_form_display.media.remote_video.default.yml
- features/helfi_media/config/install/core.entity_form_display.media.remote_video.media_library.yml
- features/helfi_media/config/install/core.entity_form_display.media.soundcloud.default.yml
- features/helfi_media/config/install/core.entity_form_display.media.soundcloud.media_library.yml
- features/helfi_media/config/install/core.entity_view_mode.media.full.yml
- features/helfi_media/config/install/core.entity_view_mode.media.media_library.yml
- features/helfi_media/config/install/crop.settings.yml
- features/helfi_media/config/install/crop.type.focal_point.yml
- features/helfi_media/config/install/language.content_settings.media.file.yml
- features/helfi_media/config/install/language.content_settings.media.image.yml
- features/helfi_media/config/install/language.content_settings.media.remote_video.yml
- features/helfi_media/config/install/language.content_settings.media.soundcloud.yml
- features/helfi_media/config/install/media.type.image.yml
- features/helfi_media/config/install/system.image.gd.yml
- features/helfi_media/config/install/system.image.yml
- features/helfi_media/helfi_media.info.yml
- Clone hel.fi environment (https://github.com/City-of-Helsinki/drupal-helfi) and switch to UHF-81_branding_selector OR `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
- Switch to corresponding branch: 
- `composer require drupal/helfi_platform_config:dev-UHF-X-enable-responsive-image-on-media-feature`
- Log in to the site.
- Make sure that the responsive image module is on.
> UHF-X Add responsive image as dependency on media feature

- composer.json
- `composer require drupal/helfi_platform_config:dev-UHF-X_features_deprecation_notice`
- Log in to the site.
- Clear caches from the https://hel-platform.docker.sh/fi/admin/config/development/performance
- Make sure this doesn't occur anymore
Also check this:
- https://github.com/City-of-Helsinki/drupal-helfi/pull/27
> UHF-X Features deprecation notices

- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.list_of_links.field_list_of_links_design.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.list_of_links.field_list_of_links_links.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.list_of_links.field_list_of_links_title.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.list_of_links_item.field_list_of_links_desc.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.list_of_links_item.field_list_of_links_image.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.list_of_links_item.field_list_of_links_link.yml
- features/helfi_paragraphs/config/install/language/fi/field.storage.paragraph.field_list_of_links_design.yml
- features/helfi_paragraphs/config/install/language/fi/paragraphs.paragraphs_type.list_of_links.yml
- features/helfi_paragraphs/config/install/language/fi/paragraphs.paragraphs_type.list_of_links_item.yml
- `composer require drupal/helfi_platform_config:dev-UHF-251-list-of-links`
- Go to edit content in Finnish and make sure that the list of links paragraph is translated.
> UHF-251 Add missing translations to list of links paragraph

- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.columns.default.yml
- `composer require drupal/hdbt_admin:dev-UHF-X-admin-ui-adjustments && composer require drupal/helfi_platform_config:dev-UHF-X-admin-ui-adjustments`
- Log in and go to edit "Palstat" content and make sure that each of the columns paragraph content is collapsed.
- Add image paragraph and it should look more sleek especially on desktop. Screenshot attached.
Also check:
https://github.com/City-of-Helsinki/drupal-helfi/pull/56
https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/17
> UHF-X Collapse column paragraphs in edit mode

- features/helfi_gdpr_compliance/config/install/eu_cookie_compliance.settings.yml
- `composer require drupal/hdbt:dev-UHF-402-cookie-banner-styling && composer require drupal/helfi_platform_config:dev-UHF-402-cookie-banner-styling`
- The cookie compliance banner should now look good and there should be overlay on the site until you accept the cookies. You should be able to use the site despite the overlay tho.
- Check that the banner looks good and works in desktop and mobile and matches about these layouts: https://app.abstract.com/projects/6a2238d2-fcb7-40e4-b2aa-a4487941ad8a/branches/master/collections/ee5cddf8-7f89-4688 …
> UHF-402: Cookie compliance banner styling

- features/helfi_content/config/install/field.field.node.landing_page.field_content.yml
- features/helfi_example_content/content/node/7f3b3413-fbf6-4f0b-873c-1fafd3c7912f.yml
- features/helfi_paragraphs/config/install/core.entity_form_display.paragraph.liftup_with_image.default.yml
- features/helfi_paragraphs/config/install/core.entity_view_display.paragraph.liftup_with_image.default.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.liftup_with_image.field_liftup_with_image_desc.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.liftup_with_image.field_liftup_with_image_design.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.liftup_with_image.field_liftup_with_image_image.yml
- features/helfi_paragraphs/config/install/field.field.paragraph.liftup_with_image.field_liftup_with_image_title.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_liftup_with_image_desc.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_liftup_with_image_design.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_liftup_with_image_image.yml
- features/helfi_paragraphs/config/install/field.storage.paragraph.field_liftup_with_image_title.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.liftup_with_image.field_liftup_with_image_desc.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.liftup_with_image.field_liftup_with_image_design.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.liftup_with_image.field_liftup_with_image_image.yml
- features/helfi_paragraphs/config/install/language/fi/field.field.paragraph.liftup_with_image.field_liftup_with_image_title.yml
- features/helfi_paragraphs/config/install/language/fi/field.storage.paragraph.field_liftup_with_image_design.yml
- features/helfi_paragraphs/config/install/language/fi/paragraphs.paragraphs_type.liftup_with_image.yml
- features/helfi_paragraphs/config/install/paragraphs.paragraphs_type.liftup_with_image.yml
- `composer require drupal/hdbt:dev-UHF-252-liftup-with-image && composer require drupal/helfi_platform_config:dev-UHF-252-liftup-with-image`
- You should now have liftup with image paragraph available in landing pages. Go to https://hel-platform.docker.sh/fi/esimerkki-laskeutumissivusta and scroll down. There should be four example banners for you to check how the element looks like.
- Go to edit the content and add one more liftup with image. You should have options for the liftup with image paragraph design. Links are added to the …
> UHF-252 Liftup with image

- composer.json
- `composer require drupal/helfi_platform_config:dev-UHF-1072-multiple-paragraph-handles-patch && composer require drupal/hdbt_admin:dev-UHF-1072-multiple-paragraph-handles-bug-fix-removal` NOTICE: Branches have different names depending on the repository.
- `make new`
- Log into the site and edit any content. Make sure there is only one drag handle per draggable item and that you can drag the items to new order.
Also check this PR:
https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/30
> UHF-1072: Patch nested paragraphs issue on platform

- features/helfi_base_config/config/rewrite/user.settings.yml
- Switch to corresponding branches: `composer require drupal/helfi_platform_config:dev-UHF-1416-disable-user-creation-unless-admin`
- `make new`
- Don't login to the site but go to the login page instead and make sure you can't create a new account.
Test also these:
https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/5
https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/3
> UHF-1416: Disable user creation from anyone else except admin

- composer.json
- features/helfi_base_config/config/install/menu_link_attributes.config.yml
- features/helfi_base_config/helfi_base_config.info.yml
- `composer require drupal/hdbt:dev-UHF-X-branding-navigation && composer require drupal/helfi_platform_config:dev-UHF-X-branding-navigation` 
- Log into the site and make sure you can add link to the Branding navigation https://hel-platform.docker.so/en/admin/structure/menu/manage/branding-navigation/add
- When adding the link also make sure to check that there is "Attributes" fieldset present and that under it you can add text to "Icon". Write there `signout`
- Save the menu link and go to the front page to see if the …
> UHF-X Branding navigation

- composer.json
Switched helfi_media_map module to depend on * instead of 1.x-dev.
> UHF-1709: Media library form

- helfi_platform_config.libraries.yml
- src/Plugin/Block/KuuraHealthChat.php
- `composer require drupal/hdbt:dev-UHF-910-kuura-chat-bot && composer require drupal/helfi_platform_config:dev-UHF-910-kuura-chat-bot`
- Log in to the site and go to https://hel-platform.docker.so/fi/admin/structure/block and you should see a new region "Attachments". Add a block to this region called "Kuura Health Chat". Hide the block title and save.
- Go to site front page and the chat bot should be available on the right bottom corner of the site.
Also check these PRs: …
> UHF-910: Add Kuura Health chat bot block

- features/helfi_content/config/install/core.entity_form_display.paragraph.banner.default.yml
- features/helfi_content/config/install/core.entity_form_display.paragraph.hero.default.yml
- features/helfi_content/config/install/filter.format.full_html.yml
- `composer require drupal/hdbt:dev-UHF-1755_cta_icons && composer require drupal/hdbt_admin:dev-UHF-1755_cta_icons && composer require drupal/helfi_platform_config:dev-UHF-1755_cta_icons`
- Log in to the site and go to edit a landing page. 
- Add Hero and choose "Taustakuva" design. Check that there's a possibility to add icon for the link field and that it works when you save the node.
- Add Banner paragraph. Check that there's a possibility to add icon for the link field and that it works when you save the node.
- …
> UHF-1755 CTA Icons

- features/helfi_base_config/config/install/config_ignore.settings.yml
Test with no previous setup:
1. Run the composer one liner to get the site: `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
2. Go to the newly created folder and switch to correct branch: `composer require drupal/helfi_platform_config:dev-UHF-1775-footer-settings-to-config-ignore`
3. Get the site running: `make new`
4. Log in to the site using the link that the install gives and go to https://hel-platform.docker.so/fi/admin/config/development/configuration/ignore to make sure there is *site_settings line on the configuration.
5. Run `make drush-cex` to get all the config exported.
6. Go to https://hel-platform.docker.so/fi/admin/tools/site-settings and change the site settings (for …
> UHF-1775 Footer settings to config ignore 

- features/helfi_content/config/install/core.entity_form_display.node.page.default.yml
- features/helfi_content/config/install/core.entity_view_display.node.page.default.yml
- features/helfi_content/config/install/core.entity_view_display.node.page.teaser.yml
- features/helfi_content/config/install/field.field.node.page.field_lead_in.yml
- features/helfi_content/config/install/field.storage.node.field_lead_in.yml
- features/helfi_content/config/install/language/fi/field.field.node.page.field_lead_in.yml
- features/helfi_content/config/install/metatag.metatag_defaults.node.yml
NOTICE: This should be tested and merged AFTER the https://github.com/City-of-Helsinki/drupal-hdbt/pull/124 is merged to avoid conflicts since this feature is partly based on the work done it that PR.
Test with no previous setup:
1. Run the composer one liner to get the site: `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
2. Go to the newly created folder and switch to correct branch: `composer require drupal/helfi_platform_config:dev-UHF-1734-basic-page-changes && composer require drupal/hdbt:dev-UHF-1734-basic-page-changes`
3. Get the site running: `make new`
4. Log in to the site using the link that the install gives and go to create / edit any basic page. There should now be new …
> UHF-1734 Basic page changes

- helfi_platform_config.libraries.yml
- src/Plugin/Block/SmarttiChatbot.php
Testing:
* If you don't already have a site for testing, create one:
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
* `cd hel-platform`
* `make new`
* Update the module to include the changes: `composer require drupal/helfi_platform_config:dev-UHF-443-smartti-chatbot`
* Clear caches.
* Log-in to the site.
* From the block layout page (`/admin/structure/block`) add "Smartti Chatbot" block to the "Attachments" section.
* Check that the Chatbot ("Kysy robotilta") is shown at the page(s) specified at the block configuration. By default, the block is placed to all content pages.
> UHF-443: Add Smartti Chatbot block

- features/helfi_media_map_config/config/install/language/fi/core.entity_view_display.media.hel_map.default.yml
- `composer require drupal/hdbt:dev-UHF-2005-general-fixes && composer require drupal/helfi_platform_config:dev-UHF-2005-general-fixes && composer require drupal/helfi_tpr:dev-UHF-2005-general-fixes`
- Log in and go to add a landing page.
- Add a map to the content and view the landing page. If the maps is added to Finnish page the "Open map in a new window" should be translated now. If on English side the map should say the English version.
- Edit the same landing page and add unit search as the first paragraph on the …
> UHF-2005 General fixes

- features/helfi_tpr_config/config/install/pathauto.pattern.service_entity_pattern.yml
- features/helfi_tpr_config/config/install/pathauto.pattern.unit_entity_pattern.yml
- features/helfi_tpr_config/config/install/pathauto.settings.yml
How to test:
1. Setup a fresh environment
2. Checkout this branch: `composer require drupal/helfi_platform_config:dev-UHF-2295_tpr_url_alias_fix`
3. Install the site: `make new`
4. Enable the HELfi TPR Config feature: `drush en -y helfi_tpr_config`
5. Login to the site as admin
6. See `/admin/config/search/path/settings` and make sure that `menu-link-parents` is listed in the `Safe tokens` field
7. See `/admin/config/search/path/patterns` and make sure that
- `Service entity pattern` is `[tpr_service:menu-link-parents]/[tpr_service:label]`
- `Unit entity pattern` is `[tpr_unit:menu-link-parents]/[tpr_unit:label]`
> UHF-2295: TPR url alias fix

- helfi_features/helfi_tpr_config/config/install/language/fi/views.view.service_list.yml
- helfi_features/helfi_tpr_config/config/install/language/sv/views.view.service_list.yml
- helfi_features/helfi_tpr_config/config/install/views.view.service_list.yml
How to test:
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
* `cd hel-platform`
* `make new`
* Update the platform config module to include changes: `composer require drupal/helfi_platform_config:dev-UHF-2520_service_list_paragraph_translations`
* Make sure you have some services imported from TPR. Using `make shell`:
* `drush en -y helfi_tpr_config`
* `drush migrate:import tpr_service`
* Create a landing page with paragraph "Service list" and add at least 5 services.
* Save the page and make sure the load more button says "Load more services" and result counter says "5 services".
* Make sure the values are translated to Finnish as well.
Also check these PRs: …
> UHF-2520: Translate service list correctly

- helfi_features/helfi_tpr_unit_districts/modules/helfi_helsinki_neighbourhoods/helfi_helsinki_neighbourhoods.install
Fixes creating and translating terms when installing the Helsinki neighbourhoods module.
How to test:
* It's easiest to test with the `sote` site, where this module is used.
* Checkout branch `UHF-2158-sote-district-search`.
* Get the new changes from this PR: `composer require drupal/helfi_platform_config:dev-UHF-2158-district-search-terms-fix`
* Run `make fresh` or `make new`.
* At this point, remember to have the `DRUPAL_SYNC_FILES=no` at the .env file so that the `make fresh` command actually finishes.
* There shouldn't be any error messages related to translating terms.
* (You can also check that there is `neighbourhoods`taxonomy and it has a lot of terms.)
> UHF-2158: Fix creating and translating terms

- helfi_features/helfi_announcements/src/Plugin/Block/AnnouncementsBlock.php
Prevent function from returning anything else than allowed types thus preventing site from dying.
> UHF-X type error fix

- composer.json
- helfi_features/helfi_base_config/helfi_base_config.info.yml
- helfi_platform_config.info.yml
- helfi_platform_config.install
Added menu external link translation module to platform_config.
Test this with existing site and new site:
**Existing site with the module already installed (sote, kymp, strategia):**
Site should be up and running
Run `composer require drupal/helfi_platform_config:dev-UHF-X_menu_external_link_translation`
Run `drush deploy`
Go check existing menu item from /admin/structure/menu/manage/main
You should see:
new override field for the link field.
**New site(kasko/elo):**
Run `git clone https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus.git`
Run `composer require drupal/helfi_platform_config:dev-UHF-X_menu_external_link_translation`
Run make new
Create new menu item by going to /admin/structure/menu/manage/main
You should see:
new override field for the link field.
> Uhf x menu external link translation

- composer.json
Allows selecting a menu item of an unpublished node as a parent when placing an entity in the menu. See the original issue: https://www.drupal.org/project/drupal/issues/2807629
How to test:
1. Set up any site instance
2. Create a node and place it in a menu but leave it unpublished
3. Create another node and try to put in in a menu using the previously created node as parent → no can do (the unpublished node is not in the dropdown)
4. Checkout this branch of the module: `composer require drupal/helfi_platform_config:dev-UHF-3087_non_published_navigation`
5. Install patched core: `composer install`
6. Repeat step 3 → can do!
> UHF-3087: non-published menu links as parent

- helfi_features/helfi_content/config/install/editor.editor.full_html.yml
- helfi_features/helfi_content/config/install/filter.format.full_html.yml
- helfi_features/helfi_content/config/update/helfi_content_update_9006.yml
- helfi_features/helfi_content/helfi_content.install
- helfi_features/helfi_tpr_config/config/install/field.field.tpr_service.tpr_service.field_lower_content.yml
- helfi_features/helfi_tpr_config/config/install/field.field.tpr_unit.tpr_unit.field_lower_content.yml
- helfi_features/helfi_tpr_config/config/update/helfi_tpr_config_update_9008.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
How to test on an existing instance:
1. `composer require drupal/hdbt:dev-UHF-2916_style_fixes && composer require drupal/helfi_platform_config:dev-UHF-2916_style_fixes`
2. `make drush-cr`
3. `make drush-cim`
4. `make drush-updb`
5. `make drush-cr`
6. Now you should have all configuration in place and the buttons should return to normal. However sometimes some buttons might still look too small and the content where they are added needs to be saved again.
7. Basically now you should test that all buttons on the site and see if they look and work correctly.
8. Check at least banner paragraph with link, hero with link, text paragraph with link button, liftup with image with link button, unit search paragraph with many units so that pager is visible, service list paragraph with many services …
> UHF-2916: Remove highlight component from WYSIWYG and fix buttons around the site.

- composer.json
- patches/eu_cookie_compliance_block_8.x-1.19.patch
- patches/eu_cookie_compliance_js_error_8.x-1.19-patched.patch
This PR includes two changes:
* The custom patch to `eu_cookie_compliance` module is moved from gist to this repository.
* A new custom patch is added to fix the JavaScript error at the cookie preference page.
* Fixing the JS error will also fix the issue of not setting the `cookie-agreed-version` cookie.
**How to test:**
* Set up a local development environment.
* You can check the current behaviour by going to the `/cookie-information-and-settings` page:
* Remove existing cookies (`cookie-agreed-categories`, `cookie-agreed-version`, `cookie-agreed`) using the browser's development tools.
* Refresh the page.
* Use the checkboxes to select e.g. all but the last category.
* Save changes by pressing the "Accept selected cookies".
* Now you should see a JS error _"Uncaught SyntaxError: …
> UHF-2956: Fix JS error from cookie preferences page

- drush.services.yml
- src/Commands/ChangeCollationCommands.php
Introduces a custom drush command that changes the collation of `tpr_unit_field_data.name` and `tpr_unit_field_data.name_override` to `utf8mb4_swedish_ci` (default is `utf8mb4_general_ci`) to enable correct sorting with Scandinavian characters (ÅÖÄ).
How to test:
1. Setup a site (SOTE is good)
2. Import and publish some TPR Units
3. Create a page with a Unit search paragraph and add some of the units there (choose ones starting with ÅÖÄ)
4. See how the view is sorted incorrectly, i.e. Å and Ä is treated as A etc.
5. Checkout this branch: `composer require drupal/helfi_platform_config:dev-UHF-3254_database_collation_change`
6. Run the drush command (in the container): `drush helfi:change-collation`
7. Clear cache and see the view again and observe the correct sorting
See PR …
> UHF-3254: drush command for changing database field collation

- helfi_features/helfi_announcements/config/optional/block.block.announcements.yml
Adds _Announcements_ block to _before_content_ region if _hdbt_ theme is installed.
**How to test:**
* Test with a development environment which doesn't have the Announcements module installed.
* For example, install a new site from [drupal-helfi-platform](https://github.com/City-of-Helsinki/drupal-helfi-platform).
* Get the changes: `composer require 'drupal/helfi_platform_config:dev-UHF-3184-announcements-block-config'`.
* Install the module: `drush en -y helfi_announcements`
* Go to the `/structure/block` and check that Announcements block is located as a first item at the Before content region.
> UHF-3184: Add Announcements block as optional config

- helfi_features/helfi_tpr_config/helfi_tpr_config.install
How to test with running instance:
- Make sure your instance is up and running and has fairly new database dump, preferably Sote
- Go to shell `make shell`
- In shell, type `drush sqlc`
- In SQL Cli type `describe tpr_service_field_data;` and look for `color_palette` field, in Sote and Kymp case it is missing.
- Update the modules/themes
- `composer require drupal/hdbt_admin:dev-UHF-3474_color_palette && composer require drupal/helfi_platform_config:dev-UHF-3474_color_palette`
- Run updates: make drush-cim drush-updb drush-cr
- Go back to shell and SQL cli. Describe the `tpr_service_field_data` table again and look for `color_palette` field. It should be listed now. 
If you want to test this with the site
- Log in, go to https://helfi-sote.docker.so/admin/content/integrations/tpr-service …
> UHF-3474 Color palette

- helfi_features/helfi_content/config/install/editor.editor.full_html.yml
This should fix issue with new sites being built with this configuration having the quote option missing from the WYSIWYG.
> UHF-X: Fix quote configuration

- helfi_features/helfi_content/config/install/user.role.admin.yml
- helfi_features/helfi_content/config/install/user.role.content_producer.yml
- helfi_features/helfi_content/config/install/user.role.read_only.yml
- helfi_features/helfi_content/config/language/fi/user.role.read_only.yml
- helfi_features/helfi_content/config/language/sv/user.role.read_only.yml
- helfi_features/helfi_content/config/update/helfi_content_update_9010.yml
- helfi_features/helfi_content/helfi_content.install
- helfi_features/helfi_content/translations/fi.po
- helfi_features/helfi_content/translations/sv.po
- helfi_features/helfi_tpr_config/config/update/helfi_tpr_config_update_9013.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
How to test / install:
- Make sure your instance is up and running on latest dev branch.
- Update the modules/themes
- `composer require drupal/helfi_platform_config:dev-UHF-3479_read_only_role && composer require drupal/helfi_tpr:dev-UHF-3479_read_only_role`
- Run `make drush-updb drush-cr drush-uli`
- Log in with the link provided and go to /admin/content page
- Edit a published landing page and basic page, which have menu links enabled
- Unpublish the nodes and make a note of the nodes what you unpublished
- Go to Integrations page and search for published unit and published service.
- Unpublish these as well and make sure they've been added to menu. If not, add them to menu. Make a note of these entities as well.
- Open an incognito tab and explore the pages what you've unpublished …
> UHF-3479: Read only role

- composer.json
Test with: `composer require drupal/helfi_platform_config:dev-UHF-3812_support_for_core_930 --with-all-dependen
cies`
> UHF-3812 Support for Drupal core 9.3.0

- assets/css/genesys_chat.css
- assets/css/smartti_chat.css
- assets/js/genesys_chat.js
- helfi_platform_config.libraries.yml
- fixed the closing button on mobile
- fixed javascript errors
- css fix for smartti chatbot that prevents the chats from going on top of each other on mobile
How to test:
- Set up KYMP instance
- Checkout this branch of the module: `composer require drupal/helfi_platform_config:dev-UHF-3091_genesys_fixes`
- Add a page that has URL `/pysakointi` so that the chat shows up
- View the page in mobile view using the browser developer tools and make sure that
- the chat can be closed using the `(X)` button
- there are no javascript errors in the console
- smartti chatbot and genesys chat don't appear on top of each other
> UHF-3901: genesys chat fixes

- helfi_features/helfi_toc/assets/js/tableOfContents.js
Removed react and share cookie consent heading from appearing in table of contents listing
* Create a page that has ToC enabled
* Open the page with cookies disabled
* Notice ToC containing RNS heading
* Get this branch on drupal-helfi-plaform-config of the test site
* Notice this getting fixed
* Approve
> Remove RNS cookie consent heading from ToC

- composer.json
How to test / install:
- Make sure your instance is up and running on latest dev branch. _**Preferably kasko**_
- Update the platform config module
- `composer require drupal/helfi_platform_config:dev-UHF-3911_views_ajax`
- Run `composer install && make drush-cr`
- Go to a page which has a view with exposed filters and check that the ajax works when a selection is made from the filter
- For example: https://helfi-kasko.docker.so/fi/kasvatus-ja-koulutus/lukiokoulutus-0 or similar to this page in test-site https://nginx-kasvatus-koulutus-test.agw.arodevtest.hel.fi/fi/test-kasvatus-ja-koulutus/lukiokoulutus-0
> UHF-3911 Views ajax

- composer.json
How to test: 
- Get kasko instance up an running
- Run `composer require drupal/helfi_tpr:dev-UHF-X_views_infinite_scroll_update --with-all-dependencies && composer require drupal/helfi_platform_config:dev-UHF-X_views_infinite_scroll_update`
- Run `make drush-cr`
- Go to a page with multiple views and test their ajax functionalities
- Test also that admin views (media library) doesn't get ajax error when choosing an image for the hero
Check also: https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/90
> UHF-X Infinite scroll update

- .github/workflows/ci.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
To test this:
`drush updb`
Open any TPR service or unit page and make sure the canonical URL is an absolute URL.
> UHF-3883: Remove metatag canonical URL override

- composer.json
- helfi_features/helfi_base_config/config/update/helfi_base_config_update_9005.yml
- helfi_features/helfi_base_config/helfi_base_config.info.yml
- helfi_features/helfi_base_config/helfi_base_config.install
Adds Role Delegation module (https://www.drupal.org/project/role_delegation) and sets permissions for the Admin role to assign roles for users.
How to test:
1. Set up a fresh (for example) KASKO instance
2. Require this branch of the module: `composer require drupal/helfi_platform_config:dev-UHF-3659_admin_assign_roles`
3. Run database updates: `make drush-updb`
4. Access https://helfi-kasko.docker.so/en/childhood-and-education/admin/people/permissions/module/role_delegation and make sure that the Admin role has three permissions checked: Assign Admin role, Assign Content producer role, Assign Read only role
Once this PR is accepted and merged, the configs can be exported and taken into use on all sites.
> UHF-3659: role_delegation installation & config

- composer.json
Check that deprecation message is gone and patch installs fine.
`composer require drupal/helfi_platform_config:dev-UHF-X_publication_date_patch`
`composer install`
> UHF-X Patched publication date module

- .github/pull_request_template.md
- helfi_features/helfi_tpr_config/config/update/helfi_tpr_config_update_9021.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
* Updated TPR Service views to show eight (8) items initially and when clicking load more. The value was four (4).
* Make sure your instance is up and running on latest dev branch. Preferably Sote.
* `make fresh` or `make up drush-sync-db drush-cim drush-updb drush-cr drush-uli`
* `composer require drupal/helfi_platform_config:dev-UHF-2871_service_list_items`
* Go to any unit which you know have a lot of services and check that there are initially eight services listed
* F.e. https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat/haagan-terveysasema
* Check also the service list paragraph for the change
* F.e. …
> UHF-2871 Service list items

- helfi_features/helfi_content/config/language/fi/views.view.locked_services.yml
- helfi_features/helfi_content/config/language/fi/views.view.locked_units.yml
- helfi_features/helfi_content/helfi_content.install
Locked views translations were not implemented correctly originally - now here is a PR that does.
* Added an update hook that imports the translations when run.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_locked_units_services_translations`
* Make sure that after the update hook is run your locked views are translated and if you run `make drush-cex` the two configuration files are added to your codebase.
> UHF-X Added update hook to import locked views translations

- helfi_platform_config.install
A tool to fix broken icon links made with CKEditor.
* Created an update hook which will go through each user generated CKEditor link button with icon
* The processor will remove target=_blank, obsolete false data attributes and will convert the data-icon to data-selected-icon
* Install your instance with the instructions found from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/263
* `composer require drupal/helfi_platform_config:dev-UHF-4556_ckeditor_link_conversion`
* Check for pages with broken button links (IE. double icons, missing icons, etc). Here's few examples:
* https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/sosiaali-ja-terveyspalvelut
* …
> UHF-4556 CKEditor link conversion

- composer.json
- helfi_platform_config.info.yml
Installing new site fails when the installation is run using [composer oneliner](https://github.com/City-of-Helsinki/drupal-helfi-platform) and with `make new`. The drush command `drush helfi:locale-import helfi_platform_config` will fail as the helfi_api_base module is not installed. 
* Added helfi_api_base module as a dependency.
* Run `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main yoursite --no-interaction --repository https://repository.drupal.hel.ninja/`
* Run `composer require drupal/helfi_platform_config:dev-UHF-X_helfi_api_base_dependency`
* Run `make new`
* Make sure the installation finishes without fatal errors
> Added helfi_api_base module as dependency.

- composer.json
Applied patch for the Allowed formats module. Will fix post update issues.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_allowed_formats_post_update`
* Run `make drush-updb`
* Check that patch gets applied and drush updb works without complaints
> UHF-X Allowed formats post update

- helfi_features/helfi_announcements/src/Plugin/Block/AnnouncementsBlock.php
Announcement blocks are now sorted by:
* Type/severity: alert, attention, notice
* Visibility: global, service/unit pages or specific page.
Added sorting for announcement blocks. 
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-3856_announcement_sort`
* Select a content page to test this with
* Create a set of announcements of different types and visibilities, Pick few of these (Remember to create the announcements in random order to test the sorting properly): 
* **global alert** announcement, **page specific alert** announcement,
* **global attention** announcement, **service specific attention** …
> UHF-3856: Add type & visibility sorting for announcements

- composer.json
You should use Sote to test since sote frontpage has dash in its /fi frontpages name. Breadcrumb module stripped dashes from the breadcrumb. Also, the front page name was shown twice in the breadcrumb.
* Added a patch which solves the problem
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-3631_breadcrumb -W`
* If you use Sote: Go to finnish front page and see the breadcrumb
* If other cases, find or create a page which has dash in it's name
Go to the page and you should see breadcrumb with dashes, front page name should be seen only once
What to expect in Sote frontpage: Etusivu > Sosiaali- ja terveyspalvelut
> UHF-3631 breadcrumb

- assets/js/genesys_neuvonta.js
* A JavaScript snippet was added that enables the opening of the Genesys chat widget by clicking on an element with a certain ID (`#openChat`).
* Set up any instance
* `composer require drupal/helfi_platform_config:dev-UHF-4810_neuvonta_genesys_button`
* Create a content page of any type and set the `Genesys (Neuvonta)` chat block to be visible on that page
* Add an element (for example a link) with `id="openChat"` on that page
* Click on the element and see how the chat widget opens
> UHF-4810: Open chat from a separate button

- assets/js/genesys_chat.js
- assets/js/genesys_neuvonta.js
- fixed a typo in a variable name
- added `window.chatExtension = chatExtension;` to enable the Smartti chatbot to send conversations to Genesys
> UHF-X: KYMP Genesys fixes

- helfi_features/helfi_base_config/config/update/helfi_base_config_update_9009.yml
- helfi_features/helfi_base_config/helfi_base_config.install
Fix layout issue on group content creation from where the sidebar would go under content when adding new content to group.
* Changed the page--group template to extend correct template and removed the language switcher from the group content creation page since it isn't available on the regular content creation page either.
* Check instructions from the [hdbt_admin PR](https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/125)
* Check instructions from the [hdbt_admin PR](https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/125)
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/125
> UHF-4847: Fix layout issue on group content creation form

- translations/new/fi.po
- translations/new/sv.po
Fix translations for North Sami after text change.
Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/144.
> Fix translations for `North Sami`

- assets/js/reactAndShareSettings.js
- src/Plugin/Block/ReactAndShare.php
Added finnish site name as rns initial request's category parameter
* Added finnish sitename to drupalSettings for javascript to use
* Added sitename as rns request parameter
* Make sure you have rns key set in local.settings.php in order to test in local (if not, ask for it)
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-4259_rns_block_additions`
* Open browser's network tab
* Go to any page with rns block set to it (any content page)
* Make sure to reload without cache so the new javascript is loaded
* After the page has loaded, find the initial rns request  from network tab, check the request's payload
* There should …
> UHF-4259 react and share block additions

- helfi_features/helfi_news_item/config/install/core.entity_view_display.node.news_item.medium_teaser.yml
- helfi_features/helfi_news_item/config/install/core.entity_view_mode.node.medium_teaser.yml
- helfi_features/helfi_news_item/helfi_news_item.install
While working on the group news archive task we needed a new display for news item that will be used on other instances as well so added one.
* New display for news item called medium teaser was added.
* Test this using the HALLINTO instance since it is the only one beside KASKO to have news item feature on.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-4092_news_item_medium_teaser`
* Log into the site and make sure that under the news items Manage display (/admin/structure/types/manage/news_item/display) there is "Medium Teaser" tab. 
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/ …
> UHF-4092 News item medium teaser

- composer.json
Gin theme got new beta version during spring and it had multiple design changes. These changed didn't apply out of the box to HDBT Admin theme.
* Fixed the position of node preview tools container.
Check instructions from https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/135
> UHF-4815: Update Gin toolbar version

- helfi_features/helfi_news_item/config/install/core.entity_view_display.node.news_item.teaser.yml
Change the default settings for news item teaser image to 3:2 aspect ratio.
* Change the default settings for news item teaser image to 3:2 aspect ratio.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-5573_news_item_aspect_ratio`
* If you create a new instance or enable the news item feature to a site where this is not available then you will get the correct aspect ratio from the start. The kasko and etusivu instances that have news items enabled have already manually been updated to use this style in the other PRs.
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/27
* …
> UHF-5573: Change the default settings for news item teaser image to 3:2 aspect ratio

- helfi_features/helfi_events/config/install/core.entity_form_display.paragraph.event_list.default.yml
- helfi_features/helfi_events/config/install/core.entity_view_display.paragraph.event_list.default.yml
- helfi_features/helfi_events/config/install/field.field.paragraph.event_list.field_event_list_description.yml
- helfi_features/helfi_events/config/install/field.storage.paragraph.field_event_list_description.yml
- helfi_platform_config.install
- Change events list description field type to text_long
- Enable helfi_events
Changed some fields configs to transform `field_event_list_description` to type `text_long`. 
Enable `helfi_events` feature via update hook.
- Run `composer require drupal/helfi_platform_config:dev-UHF-X-enable-events-paragraph` in your instance of choice.
- Run `make drush-cr drush-updb`
- Check that paragraph type `events` is available.
- Add or edit a landing page.
- Add a paragraph of type `events`. See that the description field is of type `text_long` (has ckeditor toolbar at the top). Fill the fields and check that the description field is rendered correctly.
> UHF-X: Enable events paragraph

- helfi_features/helfi_news_item/config/install/core.entity_view_display.node.news_item.card_teaser.yml
- helfi_features/helfi_news_item/config/install/core.entity_view_mode.node.card_teaser.yml
- helfi_features/helfi_news_item/helfi_news_item.install
Added new card teaser display mode for helfi news item
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-5283-main-news-styles`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/326
> UHF-5283: Added new display mode for news

- helfi_features/helfi_frontpage/config/install/core.entity_form_display.paragraph.popular_service_item.default.yml
- helfi_features/helfi_frontpage/config/install/core.entity_form_display.paragraph.popular_services.default.yml
- helfi_features/helfi_frontpage/config/install/core.entity_view_display.paragraph.popular_service_item.default.yml
- helfi_features/helfi_frontpage/config/install/core.entity_view_display.paragraph.popular_services.default.yml
- helfi_features/helfi_frontpage/config/install/field.field.paragraph.popular_service_item.field_service_links.yml
- helfi_features/helfi_frontpage/config/install/field.field.paragraph.popular_service_item.field_service_title.yml
- helfi_features/helfi_frontpage/config/install/field.field.paragraph.popular_services.field_service_items.yml
- helfi_features/helfi_frontpage/config/install/field.storage.paragraph.field_service_items.yml
- helfi_features/helfi_frontpage/config/install/field.storage.paragraph.field_service_links.yml
- helfi_features/helfi_frontpage/config/install/field.storage.paragraph.field_service_title.yml
- helfi_features/helfi_frontpage/config/install/paragraphs.paragraphs_type.popular_service_item.yml
- helfi_features/helfi_frontpage/config/install/paragraphs.paragraphs_type.popular_services.yml
- helfi_features/helfi_frontpage/config/language/fi/field.field.paragraph.popular_services.field_service_items.yml
- helfi_features/helfi_frontpage/config/language/fi/paragraphs.paragraphs_type.popular_service_item.yml
- helfi_features/helfi_frontpage/config/language/fi/paragraphs.paragraphs_type.popular_services.yml
- helfi_features/helfi_frontpage/config/update/helfi_frontpage_update_9001.yml
- helfi_features/helfi_frontpage/helfi_frontpage.info.yml
- helfi_features/helfi_frontpage/helfi_frontpage.install
- helfi_features/helfi_frontpage/helfi_frontpage.module
- helfi_features/helfi_frontpage/src/Plugin/Validation/Constraint/MinimumCount.php
- helfi_features/helfi_frontpage/src/Plugin/Validation/Constraint/MinimumCountValidator.php
Added functionality to showcase services via a paragraph.
Sketch: https://share.goabstract.com/ca21840a-654f-4386-a828-93dd3759040d?collectionLayerId=daadaaf5-3cdc-4f85-b23b-b6ff6db8f9f2&mode=design
- Added new feature module `helfi_frontpage` (some frontpage components are to be global)
- Added new paragraph types: `popular_services` & `popular_service_items`
- Added update hook to enable `popular_services` in landing pages
- Checkout branch in your instance of choice. Run `composer require drupal/helfi_platform_config:dev-UHF-5664-popular-services-paragraph drupal/hdbt:dev-UHF-5664-popular-serivces-paragraph` (yep, the HDBT branch is typo'd)
- Run `drush cr; drush en helfi_frontpage`
- Run `drush locale:check && drush locale:update` 
- Check `/fi/admin/structure/paragraphs_type` and see …
> Uhf 5664 popular services paragraph

- helfi_features/helfi_events/assets/js/eventList.js
Event link is used as a container, which messes with screen readers. Move it inside title element.
* Moved a-element inside title
* Made style changes to HDBT project to make the whole element clickable
* In an instance of your choice, run `composer require drupal/helfi_platform_config:dev-UHF-5699-events-accessibility-fix drupal/hdbt:dev-UHF-5699-events-accessibility-fix`
* Clear cache `drush cr`
* Edit or create either a landing- or standard page. Add a paragraph of type `Events`. Fill the fields.
* View the page. Link to the event should be located inside the event title, but the whole event item should be clickable.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/345
> UHF-5699: Move event link inside title

- helfi_features/helfi_news_feed/helfi_news_feed.module
Added a "See all the news" link on the "News list" paragraph. The link points to the news archive page on the matching environment (local, test, production) of the Etusivu instance.
- Set up any instance (implemented on KYMP)
- Get this branch of the helfi_platform_config module:
- `composer require drupal/helfi_platform_config:dev-UHF-5939_news_list_paragraph_all_news_link`
- Get the matching branch of the HDBT theme:
- `composer require drupal/hdbt:dev-UHF-5939_news_list_paragraph_all_news_link`
- Import translations and clear cache:
- `make shell`
- `drush locale:check; drush locale:update; drush cr`  
- Add the "News list" paragraph on any page and see if the link exist and points to the correct instance/environment
- Create language versions of the page and see that the link text …
> UHF-5939: News list paragraph "all news" link

- helfi_features/helfi_content/config/override/metatag.metatag_defaults.403.yml
- helfi_features/helfi_content/config/override/metatag.metatag_defaults.404.yml
- helfi_features/helfi_content/config/override/metatag.metatag_defaults.front.yml
- helfi_features/helfi_content/config/override/metatag.metatag_defaults.global.yml
- helfi_features/helfi_content/config/override/metatag.metatag_defaults.node.yml
- helfi_features/helfi_content/config/update/helfi_content_update_9031.yml
- helfi_features/helfi_content/helfi_content.install
* Fixed broken references to obsolete URLs in configurations.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_fix_broken_metatag_url`
* Run `make drush-updb drush-cr drush-cex`
* Check that `conf/cmi/metatag.metatag_defaults.global.yml` and `conf/cmi/metatag.metatag_defaults.node.yml` has been updated
> UHF-X Broken metatag url

- helfi_features/helfi_base_config/helfi_base_config.install
* Added update hook to fix the admin@example.com emails.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-5426_email_update`
* Check if the update hook changed UID1 email and site email
* Note! The emails get updated only if they point to `admin@example.com`
* Go to `/user/1/edit` and `/admin/config/system/site-information` paths to verify the changes
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/73
> UHF-5426: Email update

- helfi_features/helfi_news_feed/helfi_news_feed.install
- helfi_features/helfi_news_feed/helfi_news_feed.module
- helfi_features/helfi_news_feed/src/Entity/NewsFeedParagraph.php
- helfi_features/helfi_news_feed/src/HelfiExternalEntityBase.php
- helfi_features/helfi_news_feed/src/Plugin/ExternalEntities/StorageClient/News.php
- helfi_features/helfi_news_feed/tests/src/Kernel/NewsFeedParagraphTest.php
Getenv won't work with environmentResolver since test-environment has APP_ENV=testing and in environmentResolver mapping "test". This causes code to break on test environment.
* Replaced getenv with config file value
* (Bonus fix to news taxonomy autocomplete)
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_env_value_fix`
> UHF-X env value fix

- modules/helfi_test_content/README.md
- patches/default_content_2.0.0-alpha2-2640734_manual_imports-e164a354.patch
Added a new patch for default_content module based on the [latest changes](https://www.drupal.org/project/default_content/issues/2640734#comment-14638943) at issue 2640734. An update for the patch is needed after the default_content module got updated to version 2.0.0-alpha2.
After this is merged to main branch, then the actually patch is changed from composer.json file to point to the raw github file.
* Make sure you have some local development site running.
* Use the new patch.
* It might be easiest to test by temporarily changing the current patch from `vendor/composer/installed.json` to:
```
"drupal/default_content": {
"https://www.drupal.org/project/default_content/issues/2640734#comment-14638943": "https://raw.githubusercontent.com/City-of-Helsinki/drupal-helfi-platform-config/UHF-X- …
```
> Update patch for default_content 2.0.0-alpha2

- composer.json
See https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/349 for more information.
> Use updated patch for default_content

- composer.json
Adds version constraints for CTools to prevent [ctools issue 3300682](https://www.drupal.org/project/ctools/issues/3300682).
* `composer require drupal/helfi_platform_config:dev-UHF-X-not-valid-context-error`
* Make sure you can't install e.g. ctools version 4.0.1
* `composer require drupal/ctools:^4.0.1`
* Make sure you can install ctools version 4.0.0
* `composer require drupal/ctools:^4.0`
> UHF-X: Fix not valid context error

- composer.json
The newest version is 1.20. Lock to previous version until the new version is tested with patches.
> Lock eu_cookie_compliance version to 1.19

- helfi_features/helfi_base_config/helfi_base_config.info.yml
- helfi_features/helfi_gdpr_compliance/helfi_gdpr_compliance.info.yml
* Removed redundant ctools dependencies from platform config submodules.
* Check site specific PR's for testing instructions.
* Tests fail until https://github.com/City-of-Helsinki/drupal-hdbt/pull/382 is merged and released.
* Related theme PR:
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/382
* Site specific PRs:
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/435
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/419
* https://github.com/City-of-Helsinki/drupal-helfi-strategia/pull/308
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/204
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/95
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/43
* https://github.com/City-of-Helsinki/drupal-helfi-asuminen/pull …
> UHF-6300: Remove ctools dependencies from modules

- helfi_features/helfi_content/config/language/fi/field.storage.paragraph.field_hero_design.yml
- helfi_features/helfi_content/config/language/sv/field.storage.paragraph.field_hero_design.yml
- helfi_features/helfi_content/helfi_content.install
* Updated hero design translations since they were wrong
* Also added correct Swedish translations
* Make sure your instance is up and running on latest dev branch. Test i.ex. in kymp
* `make fresh`
* Go to https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/admin/structure/paragraphs_type/hero/fields/paragraph.hero.field_hero_design/translate/fi/edit and check the translations
* All of the other translations should be wrong except without image left
* Check https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/admin/structure/paragraphs_type/hero/fields/paragraph.hero.field_hero_design/translate/sv/edit
* The translations should be in English
* `composer require …
> Added update hook to update hero design translations

- composer.json
* Added patch to fix the WSOD
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6869_VBE_patch -W && composer install`
* Check that the TPR unit listing works. F.e. https://helfi-kasko.docker.so/en/childhood-and-education/admin/content/integrations/tpr-unit
> UHF-6869: Added patch to fix the WSOD in TPR unit listings.

- src/Plugin/Block/ChatLeijuke.php
Fixed assetpaths for leijuke js loading 
* Fixed assetpaths for leijuke js loading
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6169-leijuke-js-paths`
* Check that the chat js loaded via leijuke from assets is loaded.
> UHF-6169: Fixed assetpaths for leijuke js loading.

- helfi_features/helfi_gdpr_compliance/config/update/helfi_gdpr_compliance_update_9013.yml
- helfi_features/helfi_gdpr_compliance/helfi_gdpr_compliance.install
The installed version of eu_cookie_compliance has a bug that breaks the version changes and our proxy setup makes it worse. 
* Reverts cookie policy version change in update 9012 via update 9013.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6993-revert-cookie-policy-version`
* Inspect the cookie_agreed_version and check the cookie banner can be dismissed.
*
> UHF-6993: Revert cookie policy version via update.

- config/schema/helfi_platform_config.schema.yml
- helfi_features/helfi_base_config/config/install/helfi_base_config.breadcrumb.yml
- helfi_platform_config.install
- helfi_platform_config.module
- tests/src/Functional/BreadcrumbTest.php
- Fixed breadcrumb when there is only one item visible
- Removed `helfi_base_config.breadcrumb` configuration in favor of hardcoded link to hel.fi front page 
- Added `system.site:page.front` to ignored configuration
- Make sure your instance is up and running on latest dev branch.
- `git pull origin dev`
- `make fresh`
- Update the Helfi Platform config
- `composer require drupal/helfi_platform_config:dev-UHF-6824-breadcrumb-fixes`
- Run `make drush-updb drush-cr`
- Change default front page (Configuration -> Basic site settings) to whatever `/front` path gets redirected to and make sure "double" URL is removed
- For example `/en/urban-environment-and-traffic/urban-environment-and-traffic` should become `/en/urban-environment-and-traffic`
- Make sure the old URL still works and gets …
> UHF-6824: Breadcrumb fixes

- helfi_features/helfi_content/helfi_content.module
- helfi_platform_config.module
Added content type metatag to all possible content types.
* Added content type metatag to all possible content types.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6075_custom_content_type_metatag`
* Go to any content page
* test with different kind of content: nodes, tpr-entities, job_listings and whatnot
* inspect the page, check the content of head tag
* You should see something like `<meta name="helfi_content_type" content="whatever_content_you_lookin">`
> UHF-6075 custom content type metatag

- composer.json
- patches/drupal-3163299-ajax-exposed-filters-views-block-on-same-page.patch
See: https://www.drupal.org/node/3163299
Test the patch by running: 
`composer require drupal/helfi_platform_config:dev-UHF-X_ajax_exposed_form_patch -W`
> Re-rolled patch for the ajax exposed filters. 

- assets/js/chat_leijuke.js
Fix leijuke loading multiple times sometimes
* Loading debounce
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X-leijuke-init-fix`
* Check the leijuke doesn't load multple instances if ajax triggered e.g. terveysasema search in https://www.hel.fi/fi/test-sosiaali-ja-terveyspalvelut/terveydenhoito/terveysasemat
*
> Fix leijuke loading multiple times sometimes.

- helfi_platform_config.module
- tests/src/Functional/BreadcrumbTest.php
- translations/override/fi.po
- translations/override/sv.po
* Replaced breadcrumb creation with Etusivu instance instead of hardcoded values.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6960_front_page_tasks`
* Check that the breadcrumb "Front page" link points to correct environment
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/447
* https://github.com/City-of-Helsinki/drupal-module-helfi-navigation/pull/16
> UHF-6960: Front page tasks

- helfi_features/helfi_tpr_config/config/install/field.field.tpr_service.tpr_service.field_lower_content.yml
- helfi_features/helfi_tpr_config/config/install/field.field.tpr_unit.tpr_unit.field_lower_content.yml
- helfi_features/helfi_tpr_config/config/update/helfi_tpr_config_update_9028.yml
- helfi_features/helfi_tpr_config/helfi_tpr_config.install
Make it possible to add the events list paragraph to TPR units and TPR service pages lower content area.
* Created update hook that adds the events list paragraph to TPR units and TPR service lower content area.
* To test this feature you can use any instance. I used SOTE so maybe use some other like KYMP. Make sure your instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7110_events_paragraph_to_unit_and_service`
* Go to any TPR unit or TPR service and you should be able to add the event list paragraph to the lower content area. Since I don't know how to get the paragraph to display anything I can only tell you to add the title …
> UHF-7110: Add events list paragraph to TPR units and TPR services

- helfi_features/helfi_news_item/config/language/fi/field.field.node.news_item.field_news_groups.yml
- helfi_features/helfi_news_item/config/language/fi/field.field.node.news_item.field_news_neighbourhoods.yml
- helfi_features/helfi_news_item/helfi_news_item.install
* Added translations for the news item tags and update hook for updating them.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7350_news_item_translations`
* Log in and choose Finnish language for the user administration pages language
* Clear the caches from the drop (Flush all caches)
* Go to create news item and check that the news item tags are translated to Finnish, like so:
> UHF-7350: News item translations

- helfi_features/helfi_charts/assets/js/helfi-charts-cookie-compliance.js
Fix MS Power BI cookie logic
* Switched from hiding iframe to rendering it only when appropriate
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_minor_bug_fixes`
* Update HDBT using https://github.com/City-of-Helsinki/drupal-hdbt/pull/480
* Test in [HDBT PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/480)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/480
> UHF-X: Fix cookie dialog Power BI charts logic

- composer.json
- helfi_platform_config.services.yml
- src/Menu/FilterByLanguage.php
* Removed patch which hides untranslated menu links as all of our menu blocks use either custom menu tree manipulators or menu_block_current_language blocks.
> UHF-7615: Removed patch which hides untranslated menu links

- assets/js/chat_leijuke.js
- translations/new/fi.po
- translations/new/sv.po
* Changed chat wrapper to `<aside>`
* Changed `<div>` to `<button>`
* Added visually hidden title for chat
Test in some instance that has chats i.e. Etusivu
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7419-chat-accessibility-changes`
* Update translations in shell `drush locale:check && drush locale:update`
If your local instance doesn't have a frontpage set, set a page as frontpage and the chat will appear there
> UHF-7419: Accessibility changes to chat button

- assets/js/chat_leijuke.js
Chat category approval appearing twice in cookies if two chat buttons present.
* Checking the cookie category before setting.
* `git checkout dev`
* `git pull`
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7417-chat-cookie-category-duplicaiton`
> UHF-7417: Check cookie category before setting.

- composer.json
- helfi_features/helfi_base_config/helfi_base_config.install
- helfi_features/helfi_content/translations/fi.po
- helfi_features/helfi_tpr_config/translations/fi.po
* Fixed broken Drupal core localization URL
* Moved translations couple of translation from helfi_tpr_config module to helfi_content module
* Added patches to fix the base field definitions caching in multilingual fields and the rendering of admin toolbar and contextual links when browsing the admin pages in other language than English.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7008_localization -W`
* Run `make drush-updb drush-cr drush-locale-update`
* Clear caches from "Flush all caches" link and check that the translations are translated to Finnish. Note. There might be issues with the translations still - see more in here …
> UHF-7008: Fixed broken Drupal core localization URL

- helfi_features/helfi_base_config/helfi_base_config.install
* [Added update hook to update the notifications email to drupal@hel.fi.](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/commit/de702ba4c4cad2e593a9eed1abbd17f86b6dc407)
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_update_notifications_email`
> UHF-X Update notifications email

- helfi_features/helfi_announcements/src/Plugin/Block/AnnouncementsBlock.php
Announcement module tried to get value out of non-existing field.
Added checks to prevent getting values out of non-existing field.
* Test with ETUSIVU -instance
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7741_announcement_wsod_bug`
- Ota etusivun instanssista viimeisin versio ja mene muokkaamaan Poikkeusilmoitus sisältötyypin “Show on content pages” kenttää https://helfi-etusivu.docker.so/fi/admin/structure/types/manage/announcement/fields/node.announcement.field_announcement_content_pages ja laita News item sallituksi sisältötyypiksi. Tallenna.
- Mene luomaan kaksi poikkeusilmoitusta: Minä tein …
> UHF-7741: prevent wsod by checking that the field exists

- assets/js/user_consent_functions.js
- helfi_platform_config.libraries.yml
- src/Plugin/Block/ChatLeijuke.php
- src/Plugin/Block/IbmChatApp.php
Allow Hester/Sotebot to be used with leijuke just like the watson on housing.
Allow new Virtual Assistants to be used without leijuke after they implement the user consent before loading chat code that might store cookies etc.
Provides user consent functions in window.
* Added Sotebot library definition and sotebot chat selection to leijuke. (This needs to be updated once they launch the sotebot.) 
* Added new configurable IBM Chat App block that injects the appropriate script tags.
* Added user consent functions for chat app to use.
* `git checkout dev`
* `git pull`
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7766-sote-chatapp` …
> Uhf 7766 sote chatapp

- composer.json
* Apply patch for the publication date module to fix node preview when publication date is not set.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7721_publication_date_preview`
> UHF-7721: Apply patch for the publication date module.

- helfi_features/helfi_gdpr_compliance/translations/fi.po
- helfi_features/helfi_gdpr_compliance/translations/sv.po
* Added missing translations for cookie banner.
* `git checkout origin dev`
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_add_missing_translation_for_cookie_banner`
* Run `drush locale:check; drush locale:update; drush cr`
> UHF-X Add missing translation for cookie banner text

- helfi_features/helfi_news_feed/config/install/external_entities.external_entity_type.helfi_news.yml
- helfi_features/helfi_news_feed/config/install/external_entities.external_entity_type.helfi_news_groups.yml
- helfi_features/helfi_news_feed/config/install/external_entities.external_entity_type.helfi_news_neighbourhoods.yml
- helfi_features/helfi_news_feed/config/install/external_entities.external_entity_type.helfi_news_tags.yml
- helfi_features/helfi_news_feed/helfi_news_feed.install
External entities were cached indefinitely which caused news feeds to not update.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7739_news_feed_fix`
- Run drush cex
- Configurations were updated: external_entities.external_entity_type.*
- Cache time changed from -1 to 86400(1 day) 
[UHF-7739]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7739 news feed fix

- helfi_features/helfi_news_feed/src/Plugin/ExternalEntities/StorageClient/News.php
News feeds did not update properly.
Removed the part which would request main image url from json api since json-api would return error 500.
* Make sure your Etusivu-instance is up and running on latest dev branch.
* Make sure your instance (`Strategia` most preferably) is up and running on latest dev branch.
* Make sure the second instance has this line in the `local.settings.php`: `$config['helfi_news_feed.settings']['source_environment'] = 'local';` 
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_news_feed_update_problem`
- Go to your etusivu-instance
- Add new `news tag` taxonomy term, for example `MyTestTag`
- Create 1 or 2 `news items` with newly created term (or …
> Fix news feed

- helfi_features/helfi_tpr_config/helfi_tpr_config.install
* Uninstalled views_infinite_scroll
[UHF-7298]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7298: Uninstalled views_infinite_scroll on update hook

- helfi_platform_config.libraries.yml
- src/Plugin/Block/ChatLeijuke.php
Add Talbotti / Watson chabot implemented by IBM to ChatLeijuke libraries and block form.
* Test on any instance you have working currently
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8005-add-watson-talbotti-to-leijuke`
* Go to block layout config: /admin/structure/block
* Add a "Chat Leijuke" block to the "Attachments region"
* Add whatever as the title 
* Select "Talbotti (watson)" from the Dropdown
* Add "Talbotti" as the chat title
* Configure block visibility so that it's visible only on finnish and on a specific page
* Open the page you specified
* None of the scripts from …
> UHF-8005: Add Talbotti (Watson) to ChatLeijuke

- helfi_features/helfi_toc/assets/js/tableOfContents.js
Remove the dependency. Handorgel libary is deleted elsewhere and this functionality is handled in hdbt-theme accordion js library
Removed accordion specific code from toc module.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7794_accordion`
Check https://github.com/City-of-Helsinki/drupal-hdbt/pull/541
https://github.com/City-of-Helsinki/drupal-hdbt/pull/541
[UHF-7794]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7794: remove dependencies to old accordion library

- helfi_features/helfi_media/config/override/oembed_providers.provider.icareus_suite.yml
- helfi_features/helfi_media/helfi_media.install
Helsinkikanava URLs following pattern https://www.helsinkikanava.fi/*/web/helsinkikanava/player/embed/vod?assetId=* don't work.
* Added a new URL pattern to the Icareus Suite provider schemes.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-4062_Add-new-Helsinkikanava-url-matcher`
[UHF-4062]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-4062: Add new Helsinkikanava URL matcher.

- helfi_features/helfi_media/helfi_media.module
The video provider wasn't limited when a remote video is added through the media browser in the remote video paragraph.
* Added a validation that checks that given URL is from an allowed provider.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-6966_Limit-allowed-remote-video-providers`
[UHF-6966]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6966: Validate remote video URL.

- assets/js/chat_leijuke.js
- helfi_platform_config.libraries.yml
- src/Plugin/Block/ChatLeijuke.php
* Added timeout and different opening function for Watson type chats
* Make sure the talpa chats are loaded as quickly as possible by adding async attribute for the library
* Fixed php warnings from ChatLeijuke.php
* Make sure your instance is up and running on latest dev branch. You can use for example asuminen.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8080_watson_chat_opening_issue_fix`
[UHF-8080]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8080: Watson Talpa chat opening fix

- helfi_features/helfi_react_search/src/EventsApiBase.php
- helfi_features/helfi_react_search/src/LinkedEvents.php
* Increase Places fetch from Linkedevents API cache time to 8 hours
* Remove keywords from places Linkedevents API URL not to get detailed keyword data for places
* Change keyword parameter from `keyword_OR_set1 `to `keyword` because keyword is documented and works in the same way.
Check instructions from: [UHF-8084-improve-search-performance](https://github.com/City-of-Helsinki/drupal-hdbt/pull/562)
[UHF-8084]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8084: improve search performance

- helfi_features/helfi_react_search/src/Enum/CategoryKeywords.php
- helfi_features/helfi_react_search/src/EventsApiBase.php
* Add missing nature category for event search
* Make sure your SOTE instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8149-fix-events-nature-category-search`
[UHF-8149]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8149: fix events missing nature category

- assets/js/chat_leijuke.js
* Added additional interval on top of the timeout to tackle issues with slower connections.
* Make sure your asuminen instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8080_watson_chat_opening_issue_fix`
[UHF-8080]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8080: WatsonAdapter chat bug fix

- modules/helfi_node_landing_page/config/install/metatag.metatag_defaults.node__landing_page.yml
* Added correct default value for landing page meta description to the install configurations.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-4213_update_landing_page_metatag_description_default_3x`
[UHF-4213]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-4213: Fix for landing page metatag description 3.x

- helfi_features/helfi_content/config/install/metatag.metatag_defaults.node__landing_page.yml
- helfi_features/helfi_content/helfi_content.install
* Added update hook that updates the landing page metatag description default value to correnct one
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-4213_update_landing_page_metatag_description_default`
[UHF-4213]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-4213: Fix for landing page metatag description

- src/Plugin/Block/IbmChatApp.php
This PR adjusts the IBM Chat App block to use the new embed code.
Changed the embed code to the latest version which uses just one JS file instead of three.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8071-new-ibm-chat-app`
* Add a new `IBM Chat App` on `/admin/structure/block` to the `Attachments` region with the following info:
* Hostname: https://coh-chat-app-test.mo1wrhhyog0.eu-de.codeengine.appdomain.cloud
* Hide title (causes blank whitespace below the footer otherwie)
* Chat Engagement Id: housing
* Chat Tenant Id: www-hel-fi-test
* Chat Assistant Id: housing
* Add only to a specific page
[UHF-8071]: …
> UHF-8071: Use new version of IBM chat embed.

- helfi_features/helfi_react_search/helfi_react_search.services.yml
- helfi_features/helfi_react_search/src/EventSubscriber/BoostStripper.php
Strip boost parameter from index mappings to prevent errors.
Before this fix importing index mappings with boost parameter fail, since ES no longer supports index-time boosting (in favor of query-time boosting).
* Add event subscriber to handle removing boost parameters from mappings before index creation / updating.
* Read info here: https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/322
[UHF-6848]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6848: Add event subscriber to strip boost parameter from index mappings

- modules/helfi_global_announcement/src/Plugin/ExternalEntities/StorageClient/Announcements.php
Read correct module specific configuration file
Announcement query bypassed filter string creation and too much results were returned.
Call the query -method instead of calling directly to request -method (query method calls the request method after creating the query string)
> Uhf X announcement block enable filter

- composer.json
Admin toolbar 2.0 is unsupported.
* Updated `drupal/admin_toolbar` to 3.0
* Update the HDBT Admin theme and platform config module
* `composer require drupal/hdbt_admin:dev-UHF-X-update-admin-toolbar drupal/helfi_platform_config:dev-UHF-X-update-admin-toolbar -W`
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/204
> Updated admin toolbar module

- composer.json
- modules/helfi_base_content/config/install/language/fi/core.base_field_override.paragraphs_library_item.paragraphs_library_item.paragraphs.yml
- modules/helfi_base_content/config/install/language/sv/core.base_field_override.menu_link_content.menu_link_content.changed.yml
- modules/helfi_base_content/config/install/language/sv/core.base_field_override.menu_link_content.menu_link_content.description.yml
- modules/helfi_base_content/config/install/language/sv/core.base_field_override.menu_link_content.menu_link_content.title.yml
- modules/helfi_base_content/config/install/language/sv/core.base_field_override.paragraphs_library_item.paragraphs_library_item.paragraphs.yml
- modules/helfi_node_announcement/config/install/core.entity_form_display.node.announcement.default.yml
- modules/helfi_node_news_item/config/install/core.base_field_override.node.news_item.promote.yml
- modules/helfi_node_news_item/config/install/core.entity_form_display.node.news_item.default.yml
- modules/helfi_node_news_item/config/install/language/fi/core.entity_form_display.node.news_item.default.yml
- modules/helfi_node_news_item/config/install/language/sv/core.entity_form_display.node.news_item.default.yml
- modules/helfi_node_news_item/helfi_node_news_item.install
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_has_hero.yml
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_hero.yml
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_lead_in.yml
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_liftup_image.yml
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_lower_content.yml
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_metatags.yml
- modules/helfi_node_page/config/install/language/sv/field.field.node.page.field_sidebar_content.yml
- modules/helfi_tpr_config/config/install/language/sv/core.entity_form_display.paragraph.unit_search.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Removed patch for field_group translations and added missing translations to configuration
* Make sure your Etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8099 -W`
[UHF-8099]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8099: Field group patch

- modules/helfi_node_page/helfi_node_page.install
- modules/helfi_node_page/helfi_node_page.module
* This thing was fixed
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_news_list_basic_page`
> Added news list paragraph to upper content area on basic page.

- composer.json
* Update the patch for the Ajax exposed filters issue. See: https://www.drupal.org/i/3163299#comment-14974756.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_ajax_filters_patch_update -W`
* Run `composer install` to verify that the drupal core gets updated
Here's the problem: https://user-images.githubusercontent.com/1712902/228764604-483ccc9e-14ca-4255-b9fe-1815c1bd4194.mov
If the problem persists, contact @khalima or @Jussiles
> UHF-X Ajax filters patch update

- modules/helfi_global_announcement/README.md
- modules/helfi_global_announcement/helfi_global_announcement.module
Invalidate cache tags to clear global announcement block from varnish
Cache invalidation via cron.
* Set Etusivu-instance up and running
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7449_announcement_cache_warmer`
- Add  following line to local.settings.php (or change line 73 from `prod` to `local` on Announcements.php)
- `$config['helfi_global_announcement.settings']['source_environment'] = 'local'`
- Add new global announcement to etusivu
- Check that you can see the external announcement in external site
- Go and unpublish the external announcement
- As anonymous user: 
- Go to a page with external …
> UHF-7449 announcement cache warmer

- modules/helfi_ckeditor/config/install/filter.format.full_html.yml
- modules/helfi_ckeditor/helfi_ckeditor.install
* Allow `colspan` and `rowspan` attributes to be used in `th` and `td` tags.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_table_row_and_column_spans`
> UHF-X Table row and column spans

- composer.json
* `composer require drupal/helfi_platform_config:dev-UHF-8334`
[UHF-8334]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8334: Added core patch to fix #2706241

- modules/helfi_base_content/config/rewrite/pathauto.settings.yml
- modules/helfi_base_content/helfi_base_content.install
Automatically generated path aliases were cut short forcing editor to manually save the generated url aliases
Increased max length from 100 to 255
* sote is a good choice for instance due to large menu.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8274_pathauto_maxlength`
- Create content, add it to menu in a way that generate longest path alias.
- Save content and check that automatically created url alias is longer than 100 characters
[UHF-8274]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8274: pathauto max length from 100 to 255

- helfi_platform_config.module
- modules/hdbt_admin_tools/src/Form/SiteSettings.php
- modules/helfi_node_announcement/src/Plugin/Block/AnnouncementsBlock.php
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
- modules/helfi_paragraphs_news_list/src/HelfiExternalEntityBase.php
- modules/helfi_react_search/src/LinkedEvents.php
- src/Plugin/Block/ReactAndShare.php
Add new announcement with only finnish language. Add another with only english language. You should see the correct announcement always.
Add news list paragraph to content (multiple translations). The urls pointing to front-page instance's news archive should 
have correct url + lang code.
Add events paragraph to a page. Fill the info (url for example https://tapahtumat.hel.fi/en/events?text=jooga).
The content should be on correct language.
Make sure you have REACT_AND_SHARE_APIKEY_{LANGCODE} set as env variable or otherwise the block won't show up. Check test environment for correct key. Now go to any page and you should see the block rendered with correct language. The language is only used to pass correct api key to the javascript.
> UHF-8290 getCurrentLanguage parameter

- modules/helfi_paragraphs_contact_card_listing/config/install/core.entity_view_display.paragraph.contact_card.default.yml
- modules/helfi_paragraphs_contact_card_listing/helfi_paragraphs_contact_card_listing.install
This change is related to another PR where translation method of labels were changed.
* Changed Contact Card paragraph's label visibility to hidden.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7413_Config_update`
* [UHF-7413: Change translate method](https://github.com/City-of-Helsinki/drupal-hdbt/pull/630)
[UHF-7413]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7413: Labels visibility to hidden

- modules/hdbt_admin_tools/assets/js/plugins/quote/dialogs/quote.js
Attribute `aria-label` is not well supported on `quoteblock` elements. Better would have been `aria-labelledby` but seems not to have common usage in general over internet, so all extra aria attributes are now removed.
* Aria-label and role removed due to bad support on `quoteblock` elements
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8220_Quote_plugin_lang_support`
* [UHF-8220: Text paragraph RTL support](https://github.com/City-of-Helsinki/drupal-hdbt/pull/619)
[UHF-8220]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …
> UHF-8220: Screen reader support for quotes

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
HDBT:
Adds tags to news list component
This branch: 
Adds query string to the news archive link at the bottom of the news list
HDBT PR:
* Moved news tags list to its own template for reusability
* Added tags to news-list component
* Added block for tags display to the component template
This PR:
* Added logic for passing query params to news archive
* Start up an instance of your choice
* Get the correct branches:
* `composer require drupal/hdbt:dev-UHF-8215-news-list-params drupal/helfi_platform_config:dev-UHF-8215-news-list-params`
* Add or edit a landing page to include paragraph of type "News list"
* Select some taxonomy terms to go along with it from the paragraph options
* View the page. Check for these:
* Selected taxonomy terms should be displayed as tag …
> UHF-8215: Include news list params to archive url

- composer.json
- patches/drupal-3163299-ajax-exposed-filters-views-block-on-same-page.patch
* Re-rolled patch for the ajax exposed filters as it is not applying to core (again).
* `composer require drupal/helfi_platform_config:dev-UHF-X_ajax_exposed_filters -W`
> UHF-X Ajax exposed filters patch

- modules/helfi_paragraphs_banner/config/install/field.field.paragraph.banner.field_banner_design.yml
- modules/helfi_paragraphs_banner/config/install/field.field.paragraph.banner.field_banner_title.yml
- modules/helfi_paragraphs_banner/config/install/field.storage.paragraph.field_banner_design.yml
- modules/helfi_paragraphs_banner/config/install/language/fi/field.storage.paragraph.field_banner_design.yml
- modules/helfi_paragraphs_banner/helfi_paragraphs_banner.install
We are getting rid of center aligned banners. Banner title needs to be required.
* Made banner title required
* Added update hook to update the banner design and re-import the configs.
* `make fresh`
* Before composer require, find or create one page with banner that has centered design and one that has centered secondary design.
* `composer require drupal/helfi_platform_config:dev-UHF-6469_Banner-updates`
[UHF-6469]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6469: Converted banner design from centered to left

- modules/helfi_node_announcement/helfi_node_announcement.info.yml
- modules/helfi_node_announcement/src/Plugin/Block/AnnouncementsBlock.php
- modules/helfi_node_announcement/src/Plugin/Block/AnnouncementsBlockBase.php
Modifies announcement loading logic to include english announcements on languages with non standard support.
* Testing instructions in Etusivu instance PR: https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/351
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/351
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/646
* https://github.com/City-of-Helsinki/drupal-module-helfi-navigation/pull/31
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/103
[UHF-8088]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8088: Include english announcements on non standard languages

- modules/helfi_base_content/helfi_base_content.install
- modules/helfi_user_roles/helfi_user_roles.install
Allow editors, admins and content_producer to see entity usage statistics
Updated permissions
* Test this with a site with plenty of content, for example sote.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8358_entity_usage_permission`
- Log in as user with editor, admin or content_producer role (you can use for example drush uli --uid=user-id-goes-here)
- Go to `/admin/content/paragraphs`
- On the content table, under 'Used'-title: 
- The number should be a link
- User should have permission to access the link
[UHF-8358]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8358?atlOrigin=eyJpIjoiNWRkNTlj …
> UHF-8358 entity usage permission

- src/Plugin/Block/HeroBlock.php
* Set service list search as grey background paragraph so that when it is added right after hero the grey background is moved under the hero block
* Make sure your instance, for example päätöksenteko ja hallinto, is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8479_service_list_search_next_to_hero`
[UHF-8479]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8479: Set service list search as grey bg paragraph

- modules/helfi_ckeditor/helfi_ckeditor.install
* Added update hook to remove unwanted aria-label and role=region attributes from blockquote elements in long text fields.
* `make fresh`
```
<blockquote aria-label="Quote" class="quote" role="region"><p class="quote__text">This is quote text</p>
<footer class="quote__author"><cite>Your name</cite></footer></blockquote>
```
* `composer require drupal/helfi_platform_config:dev-UHF-8404`
```
<blockquote class="quote"><p class="quote__text">This is quote text</p>
<footer class="quote__author"><cite>Your name</cite></footer></blockquote>
```
[UHF-8404]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8404?atlOrigin=eyJpIjoiNWRkNTl …
> UHF-8404: Blockquote attribute cleansing

- helfi_platform_config.services.yml
- modules/helfi_global_announcement/src/Plugin/ExternalEntities/StorageClient/Announcements.php
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.info.yml
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
- modules/helfi_paragraphs_news_list/src/HelfiExternalEntityBase.php
- modules/helfi_paragraphs_news_list/src/Plugin/ExternalEntities/StorageClient/News.php
- src/Commands/RemoveNonHelsinkiTPRUnitsCommands.php
- src/Commands/TranslationWriterCommand.php
Entity query access checks
Guzzle::jsonDecode to utils::jsonDecode
ProphesizeTrait for prophesize method
How to test:
run `composer require drupal/helfi_platform_config:dev-UHF-8390`
run `composer require drupal/upgrade_status` and `drush en -y upgrade_status`
run `drush upgrade_status:analyze helfi_platform_config`
You should only see deprecation errors from prophecy / prophesize method.
> UHF-8390 D10 deprecation

- modules/helfi_toc/assets/js/tableOfContents.js
* Remove references to handorgel library that is no longer used from table of contents functionality.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_hdbt_cleanup  drupal/hdbt:dev-UHF-X_hdbt_cleanup`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/686
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/533
> UHF-X: Remove references to handorgel library that is no longer used

- modules/helfi_media/helfi_media.install
* Added update hook that enables the jquery_ui and jquery_ui_draggable modules that are required by Focal Point 2.0 version.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_focal_point_2.0_dependency`
> UHF-X: Added update hook that enables Focal Point 2.0 dependency

- modules/helfi_test_content/content/node/18345d84-b4f9-4d5f-bdf0-f1f518411a7b.yml
- modules/helfi_test_content/content/node/329149fd-3e4b-40b9-a7d4-59fb34234320.yml
- modules/helfi_test_content/content/node/482655a9-4767-4564-9edb-68ce6a668674.yml
- modules/helfi_test_content/content/node/a23b06b0-090b-46a1-b761-b86f04e61f7e.yml
- modules/helfi_test_content/content/node/a9033e6e-9009-40d8-95c1-402ad4604709.yml
*  Removed references to removed field_hero_bg_color from the test content.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_field_hero_bg_color_removal`
* Inside the shell run `drush en -y helfi_test_content` and the `drush dcim helfi_test_content`
> UHF-X: Removed references to removed field_hero_bg_color

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
The new fields are not visible without updating the form and view display configs.
* Made the new fields visible in the form and view displays of Unit
* Check the instructions in https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/147
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/147)
[UHF-8595]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8595: Update display configs of Unit

- modules/helfi_node_announcement/config/install/core.base_field_override.node.announcement.status.yml
- modules/helfi_node_announcement/helfi_node_announcement.install
- modules/helfi_node_landing_page/config/install/core.base_field_override.node.landing_page.status.yml
- modules/helfi_node_landing_page/helfi_node_landing_page.install
- modules/helfi_node_page/config/install/core.base_field_override.node.page.status.yml
- modules/helfi_node_page/helfi_node_page.install
* Set nodes to an 'unpublished' state as default
* Read instructions from the related PR on KYMP instance
* [UHF-3592: Set nodes unpublished as default `KYMP`](https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/669)
[UHF-3592]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-3592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-3592: Set nodes as unpublish on default

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
These config changes are wanted only in KUVA instance.
* Reverted changes in the tpr_unit display configs.
* Mostly just check the config changes. Following fields shouldn't be enabled anymore for the view display:
* other_info
* price_info
* contacts
* links 
* Make sure your instance (something else than kuva) is up and running
* `composer require drupal/helfi_platform_config:dev-UHF-8595_Revert-unit-display-config-changes`
* `make fresh`
* Check that the four fields (Further information, Charges, Other contact information and Web sites) are not displayed on TPR Unit pages: `/admin/structure/tpr_unit/settings/display`.
[UHF-8595]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> UHF-8595: Revert unit display configs

- src/Plugin/Block/IbmChatApp.php
* Combined ibm chat scripts under one script tag
* Added async attribute for the script tag
* Make sure your instance is up and running on latest dev branch. For example SOTE or Asuminen are good instances to test this.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8597_combine_ibm_chat_scripts`
[UHF-8597]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8597: Combine IBM chats under one script tag

- modules/hdbt_admin_tools/assets/js/ckeditor-config.js
- modules/hdbt_admin_tools/hdbt_admin_tools.module
* CKE configuration filepath was not using assets-path
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8503_CKEditor_cleanup`
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/227
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/549
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/225
[UHF-8503]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8503: CKEditor cleanup (path fix)

- modules/hdbt_admin_tools/hdbt_admin_tools.links.menu.yml
- modules/helfi_base_content/config/install/system.menu.branding-navigation.yml
- modules/helfi_base_content/helfi_base_content.install
- modules/helfi_base_content/helfi_base_content.module
- src/Menu/FilterByLanguage.php
* Configuration related to branding navigation was removed.
* Added update hook that removes branding navigation related content from the instances.
* Check installation instructions from the hdbt PR listed below.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/708
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/551
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/144
[UHF-8006]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8006: Removed branding navigation configuration and mentions from code

- modules/helfi_react_search/helfi_react_search.info.yml
* Remove ckeditor dependency from helfi_react_search module because the module got uninstalled when testing with ckeditor5
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X-remove-ckeditor-dependecy-from-react-search-module`
> UHF-X: Remove ckeditor dependency from helfi react search module

- modules/helfi_paragraphs_contact_card_listing/config/install/field.field.paragraph.contact_card_listing.field_title.yml
- modules/helfi_paragraphs_contact_card_listing/helfi_paragraphs_contact_card_listing.install
- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
* Added multiple new paragraphs available for the TPR service node:
* Upper content: `contact_card_listing, map, event_list`
* Lower content: `text, contact_card_listing, map`
* Fixed contact card listing paragraph title field from "Job title" -> "Title"
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8676_add_components_for_tpr_service`
* `composer require drupal/hdbt:dev-UHF-8676_add_components_for_tpr_service`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/731
[UHF-8676]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> UHF-8676 Add components for tpr service

- modules/helfi_paragraphs_news_list/config/install/core.entity_form_display.helfi_news_groups.helfi_news_groups.default.yml
- modules/helfi_paragraphs_news_list/config/install/core.entity_form_display.helfi_news_neighbourhoods.helfi_news_neighbourhoods.default.yml
- modules/helfi_paragraphs_news_list/config/install/core.entity_form_display.helfi_news_tags.helfi_news_tags.default.yml
- modules/helfi_paragraphs_news_list/config/install/core.entity_view_display.helfi_news_groups.helfi_news_groups.default.yml
- modules/helfi_paragraphs_news_list/config/install/core.entity_view_display.helfi_news_neighbourhoods.helfi_news_neighbourhoods.default.yml
- modules/helfi_paragraphs_news_list/config/install/core.entity_view_display.helfi_news_tags.helfi_news_tags.default.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news_groups.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news_neighbourhoods.yml
- modules/helfi_paragraphs_news_list/config/install/external_entities.external_entity_type.helfi_news_tags.yml
- modules/helfi_paragraphs_news_list/config/install/field.field.helfi_news_groups.helfi_news_groups.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/field.field.helfi_news_neighbourhoods.helfi_news_neighbourhoods.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/field.field.helfi_news_tags.helfi_news_tags.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/field.storage.helfi_news_groups.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/field.storage.helfi_news_neighbourhoods.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/field.storage.helfi_news_tags.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/language/fi/field.field.helfi_news_groups.helfi_news_groups.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/language/fi/field.field.helfi_news_neighbourhoods.helfi_news_neighbourhoods.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/config/install/language/fi/field.field.helfi_news_tags.helfi_news_tags.field_frontpage_term_id.yml
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.install
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
- modules/helfi_paragraphs_news_list/src/Plugin/ExternalEntities/StorageClient/NewsGroups.php
- modules/helfi_paragraphs_news_list/src/Plugin/ExternalEntities/StorageClient/NewsNeighbourhoods.php
- modules/helfi_paragraphs_news_list/src/Plugin/ExternalEntities/StorageClient/NewsTags.php
Fix linking to news archive app from news list paragraph
* Added fields to external entities to read frontpage tid for terms
* Added reading jsonapi response into aforementioned fields
* Fixed news list preprocess to include tids instead of term names
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8524-fix-news-list-params`
* Check if your instance uses news list paragraph on it's frontpage (a lot of the instances do) or if you know a page where it's used, check that one
* ...or just make a landing page, add `news_list` paragraph, add some terms to it and view the page
* The link below the news list should …
> UHF-8524: Fix news list params

- modules/helfi_react_search/helfi_react_search.info.yml
- modules/helfi_react_search/helfi_react_search.module
- modules/helfi_react_search/src/Plugin/DebugDataItem/SearchApiIndex.php
- modules/helfi_react_search/templates/debug-item--search-api.html.twig
- modules/helfi_react_search/tests/src/Unit/SearchApiIndexItemTest.php
See https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/121 for test instructions.
> UHF-8636: Debug page item for search api index

- modules/helfi_user_roles/config/install/user.role.super_administrator.yml
- modules/helfi_user_roles/helfi_user_roles.install
* This thing was fixed
* `composer require drupal/helfi_platform_config:dev-UHF-8848`
[UHF-8848]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8848: Super administrator role

- assets/js/genesys_neuvonta.js
Make chat open button available for the helsinki-info page (again). 
Added logic to check if `disable-genesys-button` has disabled the chat button and replace it with the open chat button.
* Boot up strategia instance (https://github.com/City-of-Helsinki/drupal-helfi-strategia/)
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7650-helsinki-info-button`
* Update HDBT 
*  `composer require drupal/hdbt:dev-UHF-7650-helsinki-info-button` 
* If you ran `make fresh`, you should be able to navigate to this page: https://strategia.docker.so/fi/paatoksenteko-ja-hallinto/ota-yhteytta/helsinki-info
* Edit the page, specifically the …
> UHF-7650: Fix neuvonta chat compatibility with disable-genesys-chat

- assets/js/genesys_kymp.js
- assets/js/genesys_neuvonta.js
- assets/js/genesys_suunte.js
Request chat backend from `chat-proxy.hel.fi`
Switched references to `www.hel.fi` to `chat-proxy.hel.fi` where relevant
Set up the following instances: 
* Etusivu https://github.com/City-of-Helsinki/drupal-helfi-etusivu/
* Liikenne https://github.com/City-of-Helsinki/drupal-helfi-kymp
* SOTE https://github.com/City-of-Helsinki/drupal-helfi-sote
Do the next step for all of them:
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8769`
For etusivu:
* Go to https://helfi-etusivu.docker.so/fi
* Check that chat still works
For Liikenne:
* Go to https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/pysakointi
* Check that …
> UHF-8769: Change genesys chats api backend url to chat-proxy.hel.fi

- modules/helfi_media_remote_video/helfi_media_remote_video.module
When adding an event video from Helsinkikanava as a remote video, the page results in and error page or just an invisible error to the user. A schema for this type of URL wouldn't help as the URL doesn't have the actual video ID.
* Handle the error so that at least "No matching provider found" message is shown.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8726_handle-remote-video-provider-error`
[UHF-8726]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8726: Handle remote video provider error

- modules/helfi_ckeditor/config/install/filter.format.full_html.yml
- modules/helfi_ckeditor/config/install/filter.format.minimal.yml
- modules/helfi_ckeditor/helfi_ckeditor.install
* Removed unwanted and unused allowed html from text-formats.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8564`
[UHF-8564]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8564: Remove unwanted and unused allowed html from text-formats

- assets/js/genesys_auth_redirect.js
- assets/js/genesys_kymp.js
- assets/js/genesys_neuvonta.js
- assets/js/genesys_suunte.js
Domains used in Genesys chat APIs is changing.
* Updated the domains used in Genesys chat.
* Make sure your _etusivu_, _kymp_ and _sote_ instances are up and running on latest dev branch.
* `make fresh`
* Update the Helfi Platform config on each of those instances
* `composer require drupal/helfi_platform_config:dev-UHF-8915_Genesys-domain-change`
- https://helfi-etusivu.docker.so/fi
- https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/pysakointi
- https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/hammashoito
[UHF-8915]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Updated genesys chat domains.

- assets/js/genesys_auth_redirect.js
The new domain for genesys chat services doesn't work in the authentication URLs.
* Reverted the changed domains.
* Make sure your sote instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_Revert-genesys-chat-domain-change`
> Reverted the chat domain change.

- assets/js/genesys_kymp.js
- assets/js/genesys_neuvonta.js
- assets/js/genesys_suunte.js
- helfi_platform_config.libraries.yml
The new domain for genesys chat services doesn't work in the authentication URLs.
* Reverted the changed domains but only the URLs that have `/chat/tunnistus` in them.
* Make sure your sote instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8981_Use-old-chat-auth-domains`
[UHF-8981]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use old domains for auth URLs in chats

- modules/helfi_paragraphs_phasing/src/Entity/Phasing.php
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_phasing`
Edit basic page
- Add toc and a phasing paragraph to the page
- Set phasing paragraphs title level as H2, fill the rest of the phasing paragraph
- Save the page
Go check the content. 
- Toc should have the the phasing paragraphs title as an item
- Phasing paragraph title level should math what you selected earlier
> Get field_phasing_title_level value instead offield_phasing_item_title_level value

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_service.tpr_service.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_service.tpr_service.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_service.tpr_service.teaser.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_service.tpr_service.teaser_search_result.yml
- modules/helfi_tpr_config/helfi_tpr_config.info.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
- modules/helfi_tpr_config/translations/fi.po
- modules/helfi_tpr_config/translations/sv.po
A feature to hide service points is needed.
- Added a checkbox field for hiding the service points.
- Added translations for the new field label and description.
- Added a helper variable for use in the twigs.
* Make sure your instance (any instance with tpr_service content) is up and running on latest dev branch.
* `make fresh`
* Update the hdbt theme and platform config
* `composer require drupal/hdbt:dev-UHF-8717_Hiding-service-points`
* `composer require drupal/helfi_platform_config:dev-UHF-8717_Hiding-service-points`
* Run `make drush-updb drush-cr drush-local-update`
1. Translations don't apply? Try running `drush cr; drush locale:update` separately without the `locale:check` etc.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/771
[UHF-8717]: …
> UHF-8717: Add field for hiding automatic service point listing

- modules/helfi_user_roles/helfi_user_roles.install
* Generate randomized password for uid 1 user.
* `make fresh`
* Update the Helfi Platform config.
* `composer require drupal/helfi_platform_config:dev-UHF-8875-randomize-admin-password`
* Set some password for admin user: `drush user:password helfi-admin 123`.
* #566 
[UHF-8875]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8875: generate random password for uid 1 user

- helfi_platform_config.services.yml
- modules/helfi_paragraphs_hearings/README.md
- modules/helfi_paragraphs_hearings/src/Plugin/ExternalEntities/StorageClient/Hearings.php
Hearings api was moved and the url changed. 
Updated the api url.
Updated logging.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9020`
- Add a hearings paragraph to any landing page and save it
- Load the landing page
- The page should load normally and the paragraph should be visible with either:  
- a list of active hearings
- "no hearings found" -message
- Check the updated url from the readme, copy the api url and see that the url works on your browser 
- Compare the url to the one in `Hearings.php` `API_URL` constant
- the constant's value should match the url you tried in your browser   
[UHF-9020]: …
> UHF-9020 hearing api url

- modules/helfi_base_content/helfi_base_content.install
* Change simple_sitemap configuration so that no sitemap links are generated from menu_link_content entities.
* `make fresh`
* Regenerate sitemap: `drush ssg` 
* `composer require drupal/helfi_platform_config:dev-UHF-8955-simple-sitemap-settings`
[UHF-8955]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8955: reconfigure simple_sitemap

- helfi_platform_config.services.yml
- src/Menu/FilterDisabledTranslations.php
Local main navigation can have menu items with wrong translation (swedish navigation has finnish links)
Local main navigation shows links to unpublished nodes
`Sote is a great candidate` for testing due to bunch of bad links under "disability services"-link in main menu
Filter out links without proper translation from main navigation when incognito.
Filter out links related to unpublished node from main navigation when incognito.
`How to recreate:`
1. go to sote test-environment and check the english main navigation(incognito):  you should see bad links under "disablity services" link 
* `make fresh`
* `composer require …
> UHF-8910 menu publish

- modules/helfi_global_announcement/config/install/external_entities.external_entity_type.helfi_announcements.yml
- modules/helfi_global_announcement/helfi_global_announcement.install
- modules/helfi_global_announcement/helfi_global_announcement.module
- modules/helfi_global_announcement/src/Plugin/ExternalEntities/StorageClient/Announcements.php
Reverts City-of-Helsinki/drupal-helfi-platform-config#594
> Revert "Revert "UHF-8525: Removed cron based cache invalidation in favor of automatic PubSub based cache invalidation""

- composer.json
- modules/helfi_platform_config_base/helfi_platform_config_base.info.yml
- modules/helfi_platform_config_base/helfi_platform_config_base.install
* `composer require drupal/helfi_platform_config:dev-UHF-9099`
[UHF-9099]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9099: Install and enable stomp module

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Made all five new TPR unit fields visible in all instances.
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/157)
[UHF-8939]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8939: Make all new TPR Unit fields visible in all instances

- modules/helfi_toc/helfi_toc.install
- modules/helfi_toc/helfi_toc.module
- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.minimal.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser_with_image.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.wide_teaser.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Adds the table of contents field to the TPR unit entity.
* `make fresh`
* Update the Helfi Platform config and HDBT
* `composer require drupal/helfi_platform_config:dev-UHF-8937_tpr-unit-toc`
* `composer require drupal/hdbt:dev-UHF-8937_tpr-unit-toc`
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/799)
[UHF-8937]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8937 tpr unit toc

- modules/helfi_toc/helfi_toc.install
The `helfi_toc_update_9002` update fails if the `helfi_tpr `module is not installed in the instance.
* Added a check if the module is installed.
* Make sure your etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_fix-toc-update`
> UHF-X Fixed update of helfi_toc module

- helfi_platform_config.install
- helfi_platform_config.module
- modules/helfi_tpr_config/helfi_tpr_config.install
* Remove invalid/unused permissions.
Drupal 10 does not allow roles to have permissions that do not exists.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9113-clear-invalid-permissions`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/800
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/462
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/617
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113 clear invalid permissions

- .github/workflows/v4-sync.yml
- composer.json
We need to release a new major revision for Drupal 10, since most of the patches in this repo are not compatible. My proposal is to have the drupal 10 related changes in a separate branch until we have upgraded everything. This PR adds automation to keep the `4.x` and `main` branches in sync with automatic pull requests, so we don't have to do manual porting.
* N/A
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: sync changes from main to v4 branch

- helfi_platform_config.module
On kasko and päätökset, update hooks that install modules crash. In päätökset, I have managed to replicate this using a production db dump. In kasko, I can replicate this only using the `latest.sql` artifact from github.
The idea of this fix is to create BaseFieldOverride if it does not exist so the field settings can be edited.
This is a cherry picked commit from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/617 in a separate PR since I run into the same issue while reviewing https://github.com/City-of-Helsinki/helsinki-paatokset/pull/319.
Download the latest SQL dump from github artifacts: https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/actions/runs/6623105851.
Create an update hook that installs a module. For example:
```php
/**
* Test update …
```
> UHF-9113, UHF-8284: Fix hook_modules_installed breaking database updates

- modules/helfi_paragraphs_remote_video/config/install/field.field.paragraph.remote_video.field_iframe_title.yml
- modules/helfi_paragraphs_remote_video/config/install/language/fi/field.field.paragraph.remote_video.field_iframe_title.yml
- modules/helfi_paragraphs_remote_video/config/install/language/sv/field.field.paragraph.remote_video.field_iframe_title.yml
- modules/helfi_paragraphs_remote_video/helfi_paragraphs_remote_video.install
* Updated editor guidance for not to use "Video: " prefix on video title
* See full testing / install instructions from Other PRs section
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-7841_Video_accessibility_updates`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/814
[UHF-7841]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-7841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-7841: Updated video title guidance for editors

- helfi_platform_config.module
- tests/src/Functional/LanguageSwitcherAlterTest.php
As anonymous user, language switcher would hide a language's title if the node has translation but translation is unpublished.
Added language switcher alter which changes the url to another one and sets it disabled. 
- This way the language title will be visible. 
- A disabled switcher link is rendered as span and has no url mentioned in it.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9158`
Should be preferably tested with multiple sites (kasko requires drush uli --uid=19 to test group content)
**`Etusivu` for other languages and `Kasko` for group content should be preferably tested.**
- Login as admin, …
> UHF-9158: language switcher titles visible for unpublished translations

- .github/workflows/ci.yml
- composer.json
- patches/simple_sitemap-3264573-respect-frontpage-configuration.patch
A patch for simple_sitemap needed re-rolling since the module updated.
* Updated the applied patch in the composer.json.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_re-rolled-simple-sitemap-patch`
> UHF-X: Updated the patch to fix frontpage URLs in simple_sitemap

- modules/hdbt_admin_tools/hdbt_admin_tools.info.yml
* Added `drupal:views` as a dependency for the `hdbt_admin_tools` module.
> UHF-X Fix missing dependency

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.minimal.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser_with_image.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.wide_teaser.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
The subgroup field should be hidden on all instances except KASKO.
* Hide the subgroup field of TPR units.
* Follow instructions in: https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/481.
* The subgroup field should be hidden after these configs are applied.
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/481
[UHF-9159]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9159: Subgroup field display configs

- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
* Enabled text and map paragraphs for the lower content of TPR units
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8936_tpr-unit-text-and-map`
[UHF-8936]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8936: Enable text and map paragraphs for lower content of TPR units

- assets/css/telia_ace.css
- config/schema/helfi_platform_config.schema.yml
- helfi_platform_config.libraries.yml
- helfi_platform_config.module
- src/Plugin/Block/TeliaAceWidget.php
Creates an embed block for Telia ACE chat widgets. Actual chat functionality can't be tested locally yet because local domains aren't whitelisted on Telia's end, but the widget is visible on the demo site: https://drupal-helfi-drupal-platform-test.test.hel.ninja/fi/new-telia-ace-widget
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9274-telia-ace`
* Create a new page or landing page for testing with swedish and english translations
* Add a new Telia ACE block to the Attachments region with the following values:
* Hide the title
* Script URL: `/wds/instances/J5XKjqJt/ACEWebSDK.min.js`
* Chat ID: …
> UHF-9274: Basic implementation of Telia ACE widget.

- composer.json
* Conflict on Drupal 10.2 until further notice
* Lock simple sitemap to 4.1.7 as there is a task for removing the patch.
> Conflict on Drupal 10.2 for now.

- modules/hdbt_admin_tools/hdbt_admin_tools.tokens.inc
- modules/helfi_base_content/config/rewrite/metatag.metatag_defaults.node.yml
- modules/helfi_base_content/helfi_base_content.install
- phpstan.neon
* Added custom token 'lead-in'. The token will use field_lead_in field value if it exists. However if Hero description is available, it will be used instead.
* Use [node:lead-in] for nodes' metatag description and og:description.
* Make sure the kymp-instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9081_lead_in_token`
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/763
[UHF-9081]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9081 Lead in token

- modules/helfi_react_search/helfi_react_search.install
* Exit early if search api module is not enabled. Like in KUVA instance, where the module `helfi_react_search` is enabled (for some reason).
> UHF-X Search API does not exist

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.minimal.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser_with_image.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.wide_teaser.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
- modules/helfi_tpr_config/translations/fi.po
- modules/helfi_tpr_config/translations/sv.po
School don't have description field coming from TPR so they need a new field for adding the description in the Drupal.
* New field, `enrich_description`, has been added in all instances.
* Make sure your instance (preferably kasko) is up and running on latest `dev `branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9249_description-override`
* `composer require drupal/hdbt:dev-UHF-9249_description-override`
* Run `make drush-updb drush-cr drush-locale-update drush-cr`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/841
[UHF-9249]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9249: Description override field for tpr units

- modules/helfi_react_search/helfi_react_search.module
* Add maternity clinics search to config
* `composer require drupal/helfi_platform_config:dev-UHF-9193_maternity_clinic_search`
* composer require drupal/hdbt:dev-UHF-9193_maternity_clinic_search
* Run `drush deploy`
* Run `drush sapi-c; drush sapi-rt; drush sapi-i; drush cr`
Info in related PR
https://github.com/City-of-Helsinki/drupal-hdbt/pull/865
[UHF-9193]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9193: add paragraph to platform config

- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/hdbt_admin_tools/translations/fi.po
Added description for langcode dropdown
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8061`
- Go to content edit pages where there is a langcode dropdown
- It should have a description text (either finnish or english description)
- Content pages without langcode dropdown should be unaffected
[UHF-8061]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8061: added description for langcode field if it exists

- modules/helfi_calculator/helfi_calculator.module
* Changed the retrieval of calculator json data to use non-overridden data.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_calculator_configuration_fix`
> UHF-X Calculator configuration

- modules/helfi_react_search/helfi_react_search.module
Added third option for search result count. Tested with different options to see that frontend doesn't break.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9007_event_list_pagination_values`
[UHF-9007]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9007: add option for 10 results

- composer.json
* Lock External entities module to 2.0-alpha6 as ExternalEntityTransformRawDataEvent extends non existent Symfony\Component\EventDispatcher\Event class.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_external_entities_alpha6`
> UHF-X External entities alpha6

- modules/helfi_tpr_config/config/install/core.entity_form_display.paragraph.unit_search.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.paragraph.unit_search.default.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_search_results_term.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_search_results_terms.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_unit_search_description.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_unit_search_meta_button.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_unit_search_meta_desc.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_unit_search_meta_label.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_unit_search_meta_placehold.yml
- modules/helfi_tpr_config/config/install/field.field.paragraph.unit_search.field_unit_search_title.yml
- modules/helfi_tpr_config/config/install/field.storage.paragraph.field_unit_search_meta_desc.yml
- modules/helfi_tpr_config/config/install/views.view.unit_search.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_search_results_term.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_search_results_terms.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_unit_search_description.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_unit_search_meta_button.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_unit_search_meta_desc.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_unit_search_meta_label.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_unit_search_meta_placehold.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.paragraph.unit_search.field_unit_search_title.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.unit_search.yml
- modules/helfi_tpr_config/config/optional/language/sv/field.field.paragraph.unit_search.field_unit_search_description.yml
- modules/helfi_tpr_config/config/optional/language/sv/field.field.paragraph.unit_search.field_unit_search_title.yml
- modules/helfi_tpr_config/config/optional/language/sv/views.view.unit_search.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
* Change the default values of Unit Search fields Search label and Search button text so that they come from code.
* Add new optional field _Additional description under the search input_ (field_unit_search_meta_desc)
* Change Search description field to compulsory.
* Adjust the labels and descriptions on the admin side of the paragraph. 
* Make sure your instance is up and running on latest dev branch. You can test this for example with KUVA instance.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9311`
* `composer require drupal/hdbt:dev-UHF-9311`
* Run `make drush-updb drush-cr drush-locale-update drush-cr`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/68 …
> UHF-9311: Unit search paragraph changes and improvements

- modules/helfi_tpr_config/config/install/views.view.service_list.yml
* Add indentifier change to the plarform config module configuration as well to avoid overriding of the configuration in the future. This change was already done to the only instance that uses this feature, the Hallinto-instance.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-5527`
[UHF-5527]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-5527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-5527: Add missing configuration for helfi_platform_config

- assets/css/genesys_chat.css
* The genesys chat has a css-file that overrides the default styles provided by the chat. The styles are horrible and very buggy but I added some improvements and the usability of the chat should be now a bit better than before. But this is no way any master piece and this hopefully will be replaced with Telia Chat in the near future so we won't use too much time on this.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9584`
[UHF-9584]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9584: Genesys-chat style fixes and hacks to mitigate issues when using the chat

- assets/js/chat_leijuke.js
- helfi_platform_config.install
- helfi_platform_config.libraries.yml
Adds and configures chat-leijuke with käyttäjäkysely-popup
- Adds and enables the block
- Added scheduler to the javascript
- Loads the javascript only if the pageload is within given date 
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8988`
- Log in as admin and go to /admin/structure/block
- user inquiry block should be in attachments
- It should have correct configurations: käyttäjätutkimus-provider, on fi,en,sv languages, only for unauthenticated users
- Log out, since this only works for unauthenticated user
- (the debug feature does not work incognito)
- Go to any content page and accept all cookies
- …
> UHF-8988 user inquiry popup

- assets/js/chat_leijuke.js
- helfi_platform_config.install
Problem when you have multiple leijuke blocks on a page. Also, hide the button for leijuke.
Force the block weight low enough to make sure it's the first attachment block.
Hide the button for user inquiry leijuke
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8988_fix`
[check this out ](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/693)
> UHF-8988 fix

- composer.json
- modules/helfi_ckeditor/config/install/editor.editor.full_html.yml
- modules/helfi_ckeditor/config/install/editor.editor.minimal.yml
- modules/helfi_ckeditor/config/install/filter.format.full_html.yml
- modules/helfi_ckeditor/config/install/filter.format.minimal.yml
- modules/helfi_ckeditor/helfi_ckeditor.ckeditor5.yml
- modules/helfi_ckeditor/helfi_ckeditor.info.yml
- modules/helfi_ckeditor/helfi_ckeditor.install
* Removed obsolete attributes from full and minimal filter formats.
* Added an update hook to convert old link button data-attributes to follow new HDS data-attributes.
* Removed class attributes from anchor tags in filter formats.
* Removed class, aria-hidden and role attributes from span elements in filter formats.
* Removed span from editor configurations.
* Added CKEditor5 paste filter module and configured settings for it.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9497 drupal/hdbt:dev-UHF-9497 -W`
This PR / Update will affect all `<a>` tags in long text fields (CKEeditor fields). In hel.fi there are …
> UHF-9497 Word vs. CKEditor5

- modules/helfi_ckeditor/config/install/editor.editor.full_html.yml
- modules/helfi_ckeditor/config/install/filter.format.full_html.yml
- modules/helfi_ckeditor/helfi_ckeditor.install
* Added figure and figcaption tags as these tags was accidentally removed during tags cleanup.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9497_figure`
[UHF-9497]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9497: Missing figure and figcaption

- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/helfi_paragraphs_accordion/config/install/field.field.paragraph.accordion.field_accordion_heading_level.yml
- modules/helfi_paragraphs_accordion/config/install/field.field.paragraph.accordion.field_accordion_title.yml
- modules/helfi_paragraphs_accordion/config/install/field.field.paragraph.accordion.field_accordion_title_level.yml
- modules/helfi_paragraphs_accordion/config/optional/language/fi/field.field.paragraph.accordion.field_accordion_heading_level.yml
- modules/helfi_paragraphs_accordion/config/optional/language/fi/field.field.paragraph.accordion.field_accordion_title.yml
- modules/helfi_paragraphs_accordion/config/optional/language/fi/field.field.paragraph.accordion.field_accordion_title_level.yml
- modules/helfi_paragraphs_accordion/config/optional/language/fi/paragraphs.paragraphs_type.accordion_item.yml
- modules/helfi_paragraphs_accordion/helfi_paragraphs_accordion.install
* Updated texts and translations for accordion and accordion items.
* Added a preprocess hook to change the 'Add accordion item' button text to 'Accordion item'.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8835`
[UHF-8835]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8835 Accordion translations

- modules/hdbt_admin_tools/hdbt_admin_tools.module
* Reverted the alter for paragraph button.
> UHF-8835: Reverted the alter for paragraph button.

- documentation/development.md
- src/ConfigUpdate/ConfigUpdater.php
* Allow instances to prevent `updb` from overwriting local configuration changes.
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/579)
[UHF-9491]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9491: Allow rewriting config on update

- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_service_channel.tpr_service_channel.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Add configuration related to the new information field on service channel.
* Check installation instructions from the [TPR PR](https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/168)
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/703
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/915
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/168
[UHF-9440]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9440: Add new field called information for the service channels

- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_api_url.yml
- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_event_location.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_api_url.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_event_location.yml
- modules/helfi_react_search/helfi_react_search.install
- modules/helfi_react_search/src/LinkedEvents.php
- Update linkedevents getPlacesList() method to be slightly more efficient
- Update events list field descriptions with new place filter requirements.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9695-linkedevents-fix`
* Use this as the API URL: https://tapahtumat.hel.fi/fi/haku?text=seniorikeskus%2Fpalvelukeskus&division=kunta:helsinki&places=tprek:48547,tprek:48591,tprek:33179,tprek:30036,tprek:47695,tprek:48762,tprek:11407
* Enable the location filter
[UHF-9613]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> UHF-9613: LinkedEvents getPlacesList fixes

- modules/helfi_base_content/helfi_base_content.install
* Add update hook that changes the social media modules linkedin api url to the new correct version
* Make sure your instance (ETUSIVU or REKRY is good) is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8333`
[UHF-8333]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8333: Fix LinkedIn share buttons

- modules/helfi_eu_cookie_compliance/config/rewrite/eu_cookie_compliance.settings.yml
- modules/helfi_eu_cookie_compliance/helfi_eu_cookie_compliance.install
* Allow helfi_accordions_open cookie so that it can be used by Siteimprove.
* Check installation instructions from the [HDBT PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/919)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/919
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/709
[UHF-9682]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9682: Add cookie check for siteimprove to be able to see inside accordions

- composer.json
- patches/revision_overview_form.patch
Revision overview form is missing current revision. 
Check this issue https://www.drupal.org/project/drupal/issues/3390329
Force the first revision to be visible.
Create new content, add a field, save
Create a translation for the content and save
Add a new paragraph to the translation and save as new revision
Go check the original language revision overview form. You should be missing "current revision" row from the table
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9767_preview_revision_form_fix`
* Run `composer install` to apply the patch
Follow the reproduction steps. Now all translations should have the …
> Uhf 9767 preview revision form fix

- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
* Change show_www to be visible on the tpr_unit form, it used to be both visible and hidden according to the configuration
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHH-9755_remove_show_www_from_hidden`
[UHF-9755]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHH-9755: Small fix for tpr unit form default configuration

- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_service_channel.tpr_service_channel.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Change service channel email field widget to email
* Check testing instructions from the HDBT PR.
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/171
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/155
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/928
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/717
[UHF-8908]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8908: Convert email field type to email

- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/931
[UHF-9562]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9562: Change email field formatter

- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/helfi_tpr_config/config/install/core.entity_form_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.default.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.minimal.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.teaser_with_image.yml
- modules/helfi_tpr_config/config/install/core.entity_view_display.tpr_unit.tpr_unit.wide_teaser.yml
- modules/helfi_tpr_config/config/install/field.field.tpr_unit.tpr_unit.field_phone_label.yml
- modules/helfi_tpr_config/config/install/field.field.tpr_unit.tpr_unit.field_phone_with_contacts.yml
- modules/helfi_tpr_config/config/install/field.storage.tpr_unit.field_phone_label.yml
- modules/helfi_tpr_config/config/install/field.storage.tpr_unit.field_phone_with_contacts.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.tpr_unit.tpr_unit.field_phone_label.yml
- modules/helfi_tpr_config/config/optional/language/fi/field.field.tpr_unit.tpr_unit.field_phone_with_contacts.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Add option to place phone number in "Other contact details" accordion.
* `make fresh`
* Update the Helfi Platform config & HDBT
* `composer require drupal/helfi_platform_config:dev-UHF-9496-phone-number-option`
* `composer require drupal/hdbt:dev-UHF-9496-phone-number-option`
- Go to [/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/paihdepalvelut/symppis/itiksen-symppis](https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/terveydenhoito/paihdepalvelut/symppis/itiksen-symppis)
- Edit [/fi/sosiaali-ja-terveyspalvelut/admin/content/integrations/tpr-unit/9301/edit](https://helfi-sote.docker.so/fi/sosiaali-ja-terveyspalvelut/admin/content/integrations/tpr-unit/9301 …
> UHF-9496: Add option to place phone number in "Other contact details" accordion.

- helfi_platform_config.services.yml
- modules/helfi_base_content/helfi_base_content.install
- src/Routing/UserCreateRouteSubscriber.php
* Added UserCreateRouteSubscriber to allow only users with super administrator role to create a local user.
* Revoked the admin user's permission for adding admin role to other users.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9471`
[UHF-9471]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9471 Revoke 'assign admin role' permission

- modules/helfi_toc/assets/js/tableOfContents.js
* Added tabindex=-1 attribute to all elements that the table of contents creates anchors to avoid issues with screen readers.
* Add toc-focusable css class to all elements that are used as anchors on table of contents.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9762`
* `composer require drupal/hdbt:dev-UHF-9762`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/724
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/934
[UHF-9762]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> UHF-9762: Accessibility improvements for the table of contents (TOC)

- modules/helfi_toc/assets/js/tableOfContents.js
- modules/helfi_toc/helfi_toc.libraries.yml
* Remove adding the class selector to all toc-focusable elements. 
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9762_simplification`
* `composer require drupal/hdbt:dev-UHF-9762_simplification`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/733
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/943
[UHF-9762]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9762: Remove the class assigment from the table of contents elements

- modules/hdbt_admin_tools/hdbt_admin_tools.module
- modules/helfi_tpr_config/helfi_tpr_config.module
In kasko tests, `hdbt_admin_tools` and `helfi_tpr` are installed without `helfi_tpr_config`. I believe this causes [an error](https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/actions/runs/8571136924/job/23490709530) in `Drupal\Core\Form\FormHelper::processStates()`.
- https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/730
> UHF-9496: Remove dependency to helfi_tpr_config from hdbt_admin_tools

- modules/helfi_ckeditor/helfi_ckeditor.module
Prevent RTL languages showing up as LTR in ckeditor by overriding the language given to ckeditor.
How to reproduce:
- Setup etusivu-instance
- Make sure your user's ui language is either und or any LTR-language
- Go edit any existing arabic content
Ckeditor should show the arabic as LTR
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9932`
- Go and edit the arabic content
- See that the content shows up like RTL-language
- See that the editor works as it is expected to work with RLT-language
- See that the page looks OK after saving
[UHF-9932]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9932?atlOri …
> UHF-9932: CKeditor5 RTL - LTR bug

- composer.json
* Added patch to fix line breaks.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9952`
[UHF-9952]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9952: Added patch to fix line breaks.

- modules/helfi_ckeditor/README.md
- modules/helfi_ckeditor/config/install/editor.editor.full_html.yml
- modules/helfi_ckeditor/config/install/editor.editor.minimal.yml
- modules/helfi_ckeditor/config/install/filter.format.full_html.yml
- modules/helfi_ckeditor/config/install/filter.format.minimal.yml
- modules/helfi_ckeditor/helfi_ckeditor.install
* Added `<p data-chat-trigger>` data-attribute to filter and editor configurations.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9280`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/944
[UHF-9280]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9280 Chat trigger

- modules/helfi_base_content/config/rewrite/metatag.metatag_defaults.node.yml
- modules/helfi_base_content/helfi_base_content.install
- modules/helfi_tpr_config/config/install/metatag.metatag_defaults.tpr_service.yml
- modules/helfi_tpr_config/config/install/metatag.metatag_defaults.tpr_unit.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Fix typo in `article_modified_time` metatag.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9704-fix-time-metatags`
[UHF-9704]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9704: Fix article_modified_time metatag

- composer.json
- patches/editoria11y-3442729.patch
- phpunit.xml
- Make sure you have 2.11.1 version of editoria11y module: `composer show drupal/editoria11y`
- `composer require drupal/helfi_platform_config:dev-UHF-10000`
- `drush cr`
- Open any page as logged in user and make sure `editoria11y.css` is loaded from asset path. For example: `/liikenne-assets/modules/contrib/editoria11y/library/css/editoria11y.css?v=2.2.0` instead of `/modules/contrib/editoria11y/library/css/editoria11y.css?v=2.2.0`.
- https://www.drupal.org/project/editoria11y/issues/3442729
> UHF-10000: Patched editoria11y module

- helfi_platform_config.libraries.yml
- src/Plugin/Block/TeliaAceWidget.php
Create Telia ACE embed block. Change embed method to always use the load_ace.js script.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9551-telia-ace-fixes`
- EN: `helsinki-testichat_en`
- FI: `helsinki-testichat_fi`
- SV: `helsinki-testichat_sv`
- It might take a few seconds to load and it might print errors in the console log, but that's expected
[UHF-9551]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9551: Telia ACE fixes.

- helfi_platform_config.module
- helfi_platform_config.permissions.yml
- tests/src/Functional/UserCancelFormTest.php
* Added a new permission 'delete user accounts' and let only user with that permission to delete other users.
* Altered the `user_cancel_methods` to let only users with high enough permissions to delete other users.
* Added test for the user deletion/cancellation form.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9832`
* https://github.com/City-of-Helsinki/drupal-infofinland/pull/305
[UHF-9832]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9832 User cancellation form

- composer.json
* Unlock external entities module, as the following issue with >= alpha7 might have been solved: ExternalEntityTransformRawDataEvent extends non existent Symfony\Component\EventDispatcher\Event class.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_unlock_external_entities`
> UHF-X Unlock external entities module

- helfi_platform_config.module
- helfi_platform_config.services.yml
- src/Plugin/Block/HeroBlock.php
- tests/src/Kernel/HeroBlockTest.php
* Changes to `hook_block_access` made in #735 broke nodes where `field_has_hero` was FALSE but `field_hero` was not.
* Remove support for `field_hero` without `field_has_hero` since that was not used by news_article nodes.
* Simplify title block hiding logic throughout the code base.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9738-block-access-fixes`
* [?] This change doesn't require updates to the documentation
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/982
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/605
[UHF-9738]: …
> UHF-9738: Fix block access hook

- modules/helfi_toc/assets/js/tableOfContents.js
* Changed the table of content implementation to work with news updates functionality.
* Check installation instructions from the [front page instance PR](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/608)
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/984
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/282
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/757
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/608
[UHF-9739]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9739 Updating news

- modules/helfi_paragraphs_news_list/config/optional/language/fi/external_entities.external_entity_type.helfi_news_tags.yml
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.install
* Fixed translations for news tags.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10090`
[UHF-10090]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10090: Fixed translations for news tags.

- modules/helfi_media_remote_video/helfi_media_remote_video.module
- translations/override/fi.po
* Fixed the media library form validation bug when inserting remote videos via modal.
* Added few Finnish translations.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10059`
[UHF-10059]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10059 Remote video via media library

- documentation/translations.md
- helfi_platform_config.module
- modules/helfi_paragraphs_contact_card_listing/helfi_paragraphs_contact_card_listing.install
- modules/helfi_tpr_config/helfi_tpr_config.install
- This should allow fixing email field label in contact card paragraph. The field label is overridden by [`social_media.settings`](https://github.com/City-of-Helsinki/drupal-helfi-etusivu/blob/dev/conf/cmi/language/fi/social_media.settings.yml#L14-L15).
* Import artifact from github (or create it locally: `drush si -y --existing-config; drush cim -y`)
* `composer require drupal/helfi_platform_config:dev-UHF-9361`
* Simulate `update-config` workflow
* ```
drush cr;
drush locale:check; drush locale:update;
drush updb -y;
drush helfi:locale-import helfi_platform_config;
drush cex
```
[UHF-9361]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9361?atlOrigin=eyJp …
> UHF-9361: Add translation context to email field in social media module

- modules/helfi_tpr_config/src/Entity/Unit.php
`imagecache_external_generate_path()` returns `FALSE` on errors. `getPictureUri()` should return `NULL` on error.
> UHF-X: Fix TypeError: getPictureUri(): Return value must be of type ?string

- modules/helfi_node_announcement/config/install/field.field.node.announcement.field_announcement_title.yml
- modules/helfi_node_announcement/helfi_node_announcement.install
- modules/helfi_tpr_config/config/install/field.field.tpr_unit.tpr_unit.field_phone_label.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Make the announcement title and TPR unit phone label translatable
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10159`
[UHF-10159]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10159 Convert fields to translatable fields

- helfi_platform_config.module
* Disabled the language switcher links on 401/403/404 error pages so that crawlers and others are not able to access the 200 code returning `system/401/403/404` pages.
* Check installation instructions from the [hdbt PR](https://github.com/City-of-Helsinki/drupal-hdbt/pull/1005).
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1005
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/771
[UHF-10060]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10060: Fix system error pages

- modules/helfi_toc/assets/js/tableOfContents.js
- modules/helfi_toc/helfi_toc.libraries.yml
* Moved the table of contents check to a later part of the script to retain the heading ids.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_helfi_toc_heading_ids`
> UHF-X Helfi table of contents - heading ids

- composer.json
- patches/issue-3454977.patch
https://www.drupal.org/project/elasticsearch_connector/issues/3454977
* `composer require drupal/helfi_platform_config:dev-UHF-X-search_api_issue -W`
* `composer show drupal/search_api`. Version should be `1.34`.
> Conflict with search_api 1.35

- composer.json
* Lock Gin toolbar version to RC5 until we've checked all possible issues from RC6.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_lock_gin_toolbar_rc5 -W`
> UHF-X Lock gin toolbar version to RC5

- modules/helfi_react_search/tests/src/Unit/LinkedEventsTest.php
* Mocked datetime service for memorybackend.
[UHF-9493]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9493: Fix tests

- composer.json
- modules/hdbt_admin_tools/hdbt_admin_tools.install
* Updated the conflict restriction for the Gin toolbar RC5 -> RC6.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10252 -W`
- [Added condition to avoid adding navigation in maintenance pages ](https://git.drupalcode.org/project/gin_toolbar/-/commit/7a1f2fdd2c8811c7ee982e275f4600689b7a1fec)
- [Bug in data-offset-top logic](https://www.drupal.org/project/gin_toolbar/issues/3440320)
- [Edit page link in secondary navigation does not support content moderation](https://www.drupal.org/project/gin_toolbar/issues/3403332)
- [PHP warning in gin_toolbar_theme()](https://www.drupal.org/i/3445824)
- Various fixes which …
> UHF-10252 Gin toolbar update

- modules/helfi_robots_header/README.md
- modules/helfi_robots_header/helfi_robots_header.info.yml
- modules/helfi_robots_header/helfi_robots_header.services.yml
- modules/helfi_robots_header/src/EventSubscriber/RobotsResponseSubscriber.php
* Add a new module that adds the `X-Robots-Tag: noindex, nofollow` header when `DRUPAL_X_ROBOTS_TAG_HEADER` environment variable is set to true.
* Set up [Palvelukeskus](https://github.com/City-of-Helsinki/drupal-palvelukeskus)
* `git checkout dev`
* `make fresh shell`
* `composer require drupal/helfi_platform_config:dev-UHF-10255-add-module-for-robots-header`
* `drush en helfi_robots_header`
* Add `DRUPAL_X_ROBOTS_TAG_HEADER: 1` to `compose.yaml` under `services` -> `app` -> `environment`, then run `make up drush-cr`
* Remove the env variable line from `compose.yaml`, then run `make up drush-cr`
[UHF-10255]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10255: Add module for X-Robots-Tag handling if helfi_proxy can't be used

- modules/helfi_toc/assets/js/tableOfContents.js
- modules/helfi_toc/helfi_toc.libraries.yml
The questionnaire heading appears in table of contents
* Questionnaire contents was removed from ToC processing
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10451_questionnaire_heading_in_toc`
[UHF-10451]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/679
> UHF-10451: Remove survey contents from table of contents listing

- modules/hdbt_cookie_banner/assets/hdbt_cookie_banner.js
- modules/hdbt_cookie_banner/config/schema/hdbt_cookie_banner.schema.yml
- modules/hdbt_cookie_banner/hdbt_cookie_banner.info.yml
- modules/hdbt_cookie_banner/hdbt_cookie_banner.libraries.yml
- modules/hdbt_cookie_banner/hdbt_cookie_banner.links.menu.yml
- modules/hdbt_cookie_banner/hdbt_cookie_banner.module
- modules/hdbt_cookie_banner/hdbt_cookie_banner.permissions.yml
- modules/hdbt_cookie_banner/hdbt_cookie_banner.routing.yml
- modules/hdbt_cookie_banner/src/Controller/HdbtCookieBannerController.php
- modules/hdbt_cookie_banner/src/Form/HdbtCookieBannerForm.php
* Add controller for hdbt cookie banner
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8652`
* Run `make drush-updb drush-cr`'
* Run `drush en -y hdbt_cookie_banner`
[UHF-8652]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8652: Add hdbt cookie banner site settings controller

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
When this PR is merged and deployed to testing the following changes need to be made manually to front page instance:
* Change the current news archive url to `/news/archive` / `/uutiset/arkisto` / `/nyheter/arkiv` 
* Create a new landing page called `Current` and have it on the `/news` / `/uutiset` / `/nyheter` path.
* Changed the news archive base url to `/news/archive`.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10452`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/795
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/689
[UHF-10452]: …
> UHF-10452: Change the news list news archive base url

- helfi_platform_config.libraries.yml
Drupal aggregation prevented suunte-chat initialization for some reason.
Prevent suunte-script aggregation
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10466`
- Make sure the JS aggregation is enabled
- (Go check local.settings.php and comment the js preprocess if not commented)
- Go to hammashoita-page as anonymous user FINNISH language
- Hammashoito-chat button should be visible
- Open inspector, check network tab and filter by JS, 
- Check that the genesys_suunte.js is listed in the loaded JS files list (which means not aggregated)
[UHF-10466]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10466 …
> UHF-10466: Prevent suunte js aggregation

- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
* Added Unit contact card to Standard page and Landing page
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9101`
* Updated Paragraph/component information to "Hel.fi components google sheet"
[UHF-9101]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9101: Added Unit contact card to Standard page and Landing page

- helfi_platform_config.libraries.yml
- phpstan.neon
- src/Plugin/Block/ChatLeijuke.php
- Added dependency injection to ChatLeijuke block.
- Removed preprocess attribute from genesys_suunte library as that attribute is not handled in ChatLeijuke.php.
- Added dependency to eu_cookie_compliance library as chat_leijuke.js uses eu_cookie_compliance functions to set the Chat category cookies.
- Set preprocess: false for chat_leijuke library to prevent possible content loading issues in production environment.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10547`
```
$config['system.performance']['css']['preprocess'] = 1;
$config['system.performance']['js']['preprocess'] = 1;
```
[UHF-10547]: …
> UHF-10547 Suunte chat

- modules/helfi_etusivu_entities/README.md
- modules/helfi_etusivu_entities/src/Plugin/ExternalEntities/StorageClient/EtusivuJsonApiEntityBase.php
- modules/helfi_etusivu_entities/tests/src/Functional/LocalEntitiesTest.php
* Fix announcements and surveys for alt languages.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10554`
[UHF-10554]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10554: Fix announcements and surveys for alt languages

- assets/js/reactAndShareSettings.js
* Added settings from https://docs.reactandshare.com/#default-fonts to prevent the loading of Font Awesome and Open sans css files
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10649`
[UHF-10649]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10649 Remove Askem css files

- modules/hdbt_admin_tools/src/Plugin/Field/FieldType/SelectIcon.php
- modules/helfi_media_remote_video/helfi_media_remote_video.module
- modules/helfi_paragraphs_hero/helfi_paragraphs_hero.module
- modules/helfi_paragraphs_hero/src/Entity/Hero.php
- modules/helfi_paragraphs_hero/tests/modules/helfi_paragraphs_hero_test/helfi_paragraphs_hero_test.info.yml
- modules/helfi_paragraphs_hero/tests/modules/helfi_paragraphs_hero_test/helfi_paragraphs_hero_test.module
- modules/helfi_paragraphs_hero/tests/src/Kernel/HeroDesignAllowedValuesAlterTest.php
- modules/helfi_paragraphs_hero/tests/src/Kernel/HeroDesignAllowedValuesTest.php
- modules/helfi_paragraphs_hero/tests/src/Kernel/HeroParagraphTest.php
- modules/helfi_paragraphs_hero/tests/src/Kernel/KernelTestBase.php
- modules/helfi_paragraphs_hero/translations/fi.po
- modules/helfi_paragraphs_hero/translations/sv.po
* Added getter methods to Hero bundle class for getting image, image author, description and title.
* Added a preprocess for the Hero paragraph and added the image_author variable for the templates.
* Added translations for image author field.
* Fixed deprecated translatable string for category field.
* Added tests for Hero bundle class and Hero design alter function.
* `make fresh`
* Update the Helfi Platform config and the HDBT theme
* `composer require drupal/helfi_platform_config:dev-UHF-8670 drupal/hdbt:dev-UHF-8670`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1051
[UHF-8670]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8670?atlOrigin=eyJpIj …
> UHF-8670 Hero image author

- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/helfi_tpr_config.module
* Made unit_contact_card addable to paragraphs library.
* Check installation instructions from the [hdbt_admin PR](https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/302)
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/817
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/302
[UHF-9509]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9509: Made unit_contact_card addable to paragraphs library

- modules/helfi_calculator/config/install/helfi_calculator.settings.yml
- modules/helfi_calculator/config/optional/language/fi/helfi_calculator.settings.yml
* ~~This PR requires the PR https://github.com/City-of-Helsinki/drupal-hdbt/pull/1045 to be merged or the branch to be used on hdbt-theme when reviewing.~~ This has been merged.
* Make sure your instance is up and running on latest dev branch. I recommend testing on ELO since that is were the calculator will come.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10588`
* Make sure the hdbt-theme is using the latest tag 6.7.7.
* Go back to project root and run `make drush-cr`
* On ELO you can now checkout the feature branch `git fetch && git checkout UHF-10588`
* Run `make drush-cim drush-cr` and you should be ready to skip the next bullet.
* Now if you are testing with instance that doens't have the …
> UHF-10588: Add helsinki_benefit_amount_estimate calculator to the required places

- modules/hdbt_cookie_banner/assets/css/cookie-banner-admin-ui.css
- modules/hdbt_cookie_banner/assets/js/cookie-banner-admin-ui.js
- modules/hdbt_cookie_banner/assets/json/siteSettings.schema.json
- modules/hdbt_cookie_banner/src/Form/HdbtCookieBannerForm.php
* Cookie banner did not support language directions or language attributes for screen readers 
* The editor did not save language options properly to json, so adding languages was inpossible.
* Whole editor was rewritten
* json syntax was updated
* banner code was updated
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10461_fixed_cookie_banner_editor`
[UHF-10461]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10461: Add support for language direction by rewriting whole editor.

- modules/helfi_paragraphs_content_liftup/helfi_paragraphs_content_liftup.install
- modules/helfi_platform_config_base/helfi_platform_config_base.install
* Remove stale content liftup paragraph entities before uninstalling the paragraph type
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9511_content_liftup_entities`
[UHF-9511]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9511 Content liftup entities

- assets/js/reactAndShareSettings.js
* We want to use new cookie banner
* React and share was switched to new cookie banner
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8650_cookie_banner_activation`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1080
[UHF-8650]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8650: Switch react and share to use hds cookie banner

- modules/hdbt_cookie_banner/hdbt_cookie_banner.install
- modules/hdbt_cookie_banner/hdbt_cookie_banner.module
* Added uninstall hook to remove the module settings file when module is uninstalled.
* Switched the deprecated `config_ignore_settings_alter` to `config_ignore_ignored_alter`. Ignored only the config objects in the `hdbt_cookie_banner.settings.yml`. Otherwise uninstallation or revert would not work.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8650_config_ignore_fix`
[UHF-8650]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8650 Config ignore fix

- modules/helfi_paragraphs_remote_video/config/install/field.field.paragraph.remote_video.field_remote_video_video_title.yml
- modules/helfi_paragraphs_remote_video/helfi_paragraphs_remote_video.install
* Changed video title field to be required
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-8340`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1104
[UHF-8340]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8340: Changed remote video title to be required

- config/schema/helfi_platform_config.schema.yml
- helfi_platform_config.services.yml
- modules/helfi_node_news_item/config/install/field.field.taxonomy_term.news_neighbourhoods.field_location.yml
- modules/helfi_node_news_item/config/install/field.storage.taxonomy_term.field_location.yml
- modules/helfi_node_news_item/helfi_node_news_item.info.yml
- modules/helfi_node_news_item/helfi_node_news_item.install
- src/EventSubscriber/SearchApiSubscriber.php
- src/Plugin/DataType/Location.php
- src/Plugin/Field/FieldType/LocationItem.php
- src/Plugin/Field/FieldWidget/LocationWidget.php
- src/Plugin/search_api/data_type/LocationDataType.php
* Add geo_point to news and news neighbourhood elasticsearch.
* Add field that stores coordinates
* Add search_api support for location field.
* Make sure your etusivu is up and running on branch `UHF-10774-news-location`.
* `git checkout UHF-10774-news-location`
* `composer require drupal/helfi_platform_config:dev-UHF-10774-news-location`
* Run `make fresh`
```sh
curl 'https://elastic-proxy-helfi-etusivu.docker.so/news/_search' -X POST -H 'Content-Type: application/json' --data-raw '{
"query": {
"bool": {
"filter": [
{
"term": {
"entity_type":"taxonomy_term"
}
},
{
"term": {
"search_api_language":"fi"
}
}
]
}
},
"sort": [
{
"_geo_distance": {
"field_location": {
"lat": 60.187959,
"lon": 24.966060
},
"order": "asc",
"unit": "km",
"mode": "min", …
```
> UHF-10774: news location

- modules/helfi_platform_config_base/helfi_platform_config_base.install
* Use `getActiveProject()` instead of `getActiveEnvironment()`.
[UHF-10239]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10239: Enable image gallery paragraph

- modules/hdbt_cookie_banner/assets/js/hdbt-cookie-banner.js
* Added js to send unapproved cookies/items to Sentry
* If you don't have yet, add to your compose.yaml `SENTRY_DSN_PUBLIC`  and `SENTRY_ENVIRONMENT`  variables in order to test the sentry logging from local environment 
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10465 `
[UHF-10465]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10465 Send unapproved cookies to Sentry

- helfi_platform_config.install
The hook 9306 which was supposed to remove the block, did not run in every environment (Sote for example)
TEST IN SOTE or any other site where the user_inquiry block is still enabled
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_user_inquiry`
- Run drush cex
- The export should delete the configuration
> User inquiry block is still active 

- modules/helfi_node_news_item/config/optional/language/fi/field.field.node.news_item.field_news_item_links_link.yml
- modules/helfi_paragraphs_accordion/helfi_paragraphs_accordion.install
- modules/helfi_paragraphs_accordion/helfi_paragraphs_accordion.module
* Sorted the accordion paragraphs in the following order: text, image, phasing, columns
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_accordion_paragraph_weight`
> UHF-X Accordion paragraphs weights

- modules/helfi_toc/assets/js/tableOfContents.js
* Added a generic class which excludes things from table of contents, prevents accidental class removals in the future affecting what is removed from table of contents.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11032`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1133
[UHF-11032]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11032: Changed exclusion logic for table of contents

- modules/helfi_paragraphs_hearings/src/Plugin/ExternalEntities/StorageClient/Hearings.php
Updated the hearing logic and removed code which is now obsolete.
Show only hearings with correct translation on the listing.
The old implementation tried it's best to show same amount of hearings for all translations. For example, if there were 3 finnish hearings but only 2 swedish, it would have shown 2 swedish and 1 finnish hearings.
A hearing paragraph can be found from strategia for example: [strategia test](https://www.test.hel.ninja/fi/paatoksenteko-ja-hallinto/osallistu-ja-vaikuta) or etusivu frontpage
* `make fresh`
* Update the Helfi packages
* `composer require drupal/helfi_platform_config:dev-UHF-10887`
* `composer require drupal/hdbt:dev-UHF-10887`
- Go …
> UHF-10887 Hearings

- composer.json
- patches/drupal-3467860-optimized-js-assets-mismatch.patch
Lock drupal core version. 10.4 breaks ckeditor link functionality
> UHF-X lock core 10.3.10

- modules/helfi_react_search/helfi_react_search.module
Sort autocomplete results from shortest to longest
Added select2 alter
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10275`
- Login as admin
- Go and edit any page which have linkedevents search
- Try adding new items to topics select2 
- The autocomplete results should be from shortest to longest 
[UHF-10275]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10275 linked events autocomplete sort

- assets/js/chat_leijuke.js
wait for the cookies awhile instad of just preventing the chat from loading
The chat would not open after user authentication redirect
Wait for the cookies to be available
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11208`
- Go to sote-hammashoito -page
- Open chat and use the authentication
- Go through the auth-pipe and redirect back to Sote-hammashoito -page
- The chat should open normally
[UHF-11208]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11208: wait for the cookies

- helfi_platform_config.module
- modules/helfi_react_search/src/LinkedEvents.php
- modules/helfi_test_content/content/menu_link_content/d4d64c29-abc2-4e7e-94b2-7fc3bab25159.yml
- modules/helfi_test_content/content/node/c0aeeda3-54e5-4a08-b742-3b9c24b4f0b6.yml
- modules/helfi_test_content/helfi_test_content.info.yml
* Added test content for the visual regression tests on image gallery.
* Test this out on a clean install so create that instance based on the helfi_platform: `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main testpage --no-interaction --repository https://repository.drupal.hel.ninja/`
* `composer reinstall drupal/helfi_platform_config --prefer-source`
* `composer reinstall drupal/hdbt --prefer-source`
* `composer require drupal/helfi_platform_config:dev-UHF-11017`
* `composer require drupal/hdbt:dev-UHF-11017`
* Once the site is created go to the directory and run `make new`.
* When the site is installed run `drush en -y helfi_test_content` to enable testing content.
* …
> UHF-11017: Visual regression tests for Image Gallery paragraph

- helfi_platform_config.module
- modules/helfi_media_remote_video/helfi_media_remote_video.module
- modules/helfi_media_remote_video/src/Entity/RemoteVideo.php
- modules/helfi_react_search/src/LinkedEvents.php
Fix crashes with some YouTube link.
Sentry issue: https://sentry.hel.fi/organizations/city-of-helsinki/issues/46100/?query=is%3Aunresolved+OEmbed&referrer=issue-stream&statsPeriod=14d
This issue was hard to reproduce locally. I believe the root cause was that google blocks OpenShift environment:
Some YouTube links, like `https://youtube.com/watch?v=g2eYKMjE8ew` (missing www.), are perfecly fine, but not included in the list provider by [drupal/oembed_providers](https://www.drupal.org/project/oembed_providers): https://oembed.com/providers.json. This causes these links to [make network requests](https://github.com/drupal/drupal/blob/11.x/core/modules/media/src/OEmbed/UrlResolver.php#L139-L144) to google from the backend whenever they are used. According to the Sentry logs, Google seems to …
> UHF-10406: Catch exceptions from UrlResolverInterface::getProviderByUrl

- modules/helfi_media_map/src/Entity/HelMap.php
Whitescreen in this page on [PROD](https://www.hel.fi/fi/asuminen/pohjois-pasilaan-valmistuvien-hekan-vuokra-asuntojen-hakuaika-on-alkanut) or [LOCAL](https://helfi-asuminen.docker.so/fi/asuminen/pohjois-pasilaan-valmistuvien-hekan-vuokra-asuntojen-hakuaika-on-alkanut)
[Sentry error](https://sentry.hel.fi/organizations/city-of-helsinki/issues/50940/?referrer=slack&notification_uuid=c5458911-8163-42d4-bca0-4b66e39525c4&environment=production&alert_rule_id=154&alert_type=issue)
Set correct return type on function
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_returntype_whitescreen`
[This …
> wrong return type causes whitescreen

- modules/hdbt_admin_tools/config/optional/language/fi/views.view.content.yml
- modules/hdbt_admin_tools/hdbt_admin_tools.install
- modules/helfi_paragraphs_curated_event_list/src/Plugin/ExternalEntities/StorageClient/Events.php
* Add language support for the curated event list.
* Fix translation in the content listing view.
* Make sure your Front page instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11222`
* `composer require drupal/hdbt:dev-UHF-11222`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/890
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1166
* https://github.com/City-of-Helsinki/hel-fi-drupal-grants/pull/1630
[UHF-11222]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11222: Language support for the curated event list, fix translation in the content listing view

- modules/helfi_paragraphs_curated_event_list/helfi_paragraphs_curated_event_list.module
Prevent whitescreen when event does not have either start or end time.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_curated_events_whitescreen`
* Update HDBT
* `composer require drupal/hdbt:dev-UHF-X_curated_events_whitescreen`
- Add a curated event paragraphs to a page
- Add the following events:
```
- Sound of Stoa
- Ilmaispäivä
- Kiasman ilmaispäivä
- DocPoint 2025
```
- Save the page
- Go see the page
You should not see whitescreen
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/895
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1169
> UHF-X: External event entity causes WSOD fix

- modules/helfi_media/config/install/field.field.media.image.field_media_image.yml
- modules/helfi_media/helfi_media.install
* Remove gif file format from the list of allowed formats on the media image field.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-10023`
[UHF-10023]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10023: Remove gif file format from the list of allowed formats on the media image field

- config/schema/helfi_platform_config.schema.yml
Fix errors in Etusivu tests.
* Add schema entry for helfi linkit widget 
* Boot up Etusivu instance
* `composer require drupal/helfi_platform_config:dev-UHF-11232`
* Run `make fresh`
* Run  `SIMPLETEST_BASE_URL=https://helfi-etusivu.docker.so vendor/bin/phpunit public/modules/custom/helfi_annif/` (this might take a while)
* Troubleshooting:
* Permission errors: run `chmod 777 -R` for directories  `public/sites/simpletest` and `public/sites/default/files/simpletest`
* Deprecation warnings: unrelated, disregard for now
If all goes right, you should receive green lights and the tests should pass. Some deprecation warning show up, but they are not …
> UHF-11232: Add schema entry for helfi linkit widget

- modules/hdbt_cookie_banner/assets/js/hdbt-cookie-banner.js
*  Changed unapproved cookie logging to log only items that are not in the json settings
*If you don't have yet, add to your compose.yaml `SENTRY_DSN_PUBLIC: ""` and `SENTRY_ENVIRONMENT: "local"` variables in order to test the sentry logging from local environment
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11441 `
[UHF-11441]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11441: Changed sentry logging to send only items that are not in cookie settings

- modules/helfi_tpr_config/config/install/views.view.service_units.yml
- modules/helfi_tpr_config/helfi_tpr_config.install
* Changed how many items are shown in service units
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9494`
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/1182
[UHF-9494]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9494: Changed how many items are shown in service units

- modules/helfi_react_search/src/Enum/CategoryKeywords.php
- modules/helfi_react_search/src/LinkedEvents.php
- modules/helfi_react_search/tests/src/Unit/LinkedEventsTest.php
Requests from Linked Events React search components to Linked Events API are currently prone to timeouts, especially when a text search query parameter is included. It was suggested in the ticket that using a keyword instead would make the request more performant. ~This PR attempts to do just that~.
* A db query on "Työ ja yrittäminen" revealed all linked events paragraphs that have a `text`-parameter use the word `tyollisuus` or `työllisyys` (identical in terms of results). They will then all benefit from converting the text based search into a keyword based.
* Tested calling the api with the current request structure and the suggested alteration
* Current: https://api.hel.fi/linkedevents/v1/event/?event_type=General&format=json&include=keywords%2Clocation&page=1&page_size=10&sort=end_tim …
> UHF-11462: Performance improvements to Linked Events query parameter handling

- modules/helfi_media_remote_video/config/install/oembed_providers.provider.icareus_suite.yml
- modules/helfi_media_remote_video/helfi_media_remote_video.install
Helsinki Kanava video embed urls are being updated and we need to support the new url domain and structure to allow adding the video embeds into media library. Existing videos added to Drupal will continue to work via redirects already in place in Helsinki Kanava.
* Added a new scheme for url pattern `https://players.icareus.com/helsinkikanava/embed/vod/*` in oEmbed provider "Icareus Suite".
* Make sure your [drupal-helfi-sote](https://github.com/City-of-Helsinki/drupal-helfi-sote) instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11281_video_embeds`
* Make sure your [drupal-helfi-etusivu](https://github.com/City-of-Helsinki/drup …
> UHF-11281: Add support for new Helsinki Kanava urls

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.module
- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.services.yml
- modules/helfi_paragraphs_news_list/src/EventSubscriber/CacheResponseSubscriber.php
- modules/helfi_paragraphs_news_list/tests/src/Kernel/CacheResponseSubscriberTest.php
News lists paragraphs could have empty result in cases when the external source is not available. The list remains empty until the page cache expire or when purged, which could sometimes take a long time.
This fix sets the maximum cache duration to 10mins when a news list is empty.
* Set the max-age of the paragraph render cache to 600sec (10mins)
* In addition, set the page render cache's max-age to the same value
* Make sure your `helfi-etusivu` instance is up and running
* Rebuild and re-index the news entities to Elasticsearch
* Make sure your `helfi-tyo-yrittaminen` instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11615`
* …
> UFF-11615: Fix empty news list cache duration

- modules/helfi_paragraphs_news_list/src/EventSubscriber/CacheResponseSubscriber.php
* Fixes the broken tests in Etusivu (See https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/876), which was caused by passing the wrong response type
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11615-fixes`
[UHF-11615]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11615: Fix the type response type hinting

- translations/override/fi.po
* Added inline form error translation
[UHF-11394]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11394 Added missing translations

- composer.json
- modules/helfi_recommendations/config/optional/jsonapi.settings.yml
- modules/helfi_recommendations/config/optional/jsonapi_extras.jsonapi_resource_config.media--image.yml
- modules/helfi_recommendations/config/optional/jsonapi_extras.jsonapi_resource_config.node--landing_page.yml
- modules/helfi_recommendations/config/optional/jsonapi_extras.jsonapi_resource_config.node--page.yml
- modules/helfi_recommendations/config/optional/jsonapi_extras.settings.yml
- modules/helfi_recommendations/config/optional/search_api.index.suggestions.yml
- modules/helfi_recommendations/helfi_recommendations.info.yml
- modules/helfi_recommendations/helfi_recommendations.module
- modules/helfi_recommendations/helfi_recommendations.services.yml
- modules/helfi_recommendations/src/ElasticClientBuilder.php
- modules/helfi_recommendations/src/Plugin/Block/RecommendationsBlock.php
- modules/helfi_recommendations/src/Plugin/Field/FieldType/SuggestedTopicsReferenceItem.php
- modules/helfi_recommendations/src/Plugin/Field/FieldWidget/SuggestedTopicsReferenceWidget.php
- modules/helfi_recommendations/src/RecommendationManager.php
- modules/helfi_recommendations/src/RecommendationManagerInterface.php
- modules/helfi_recommendations/src/TopicsManager.php
- modules/helfi_recommendations/src/TopicsManagerInterface.php
- modules/helfi_recommendations/templates/recommendations-block.html.twig
- modules/helfi_recommendations/tests/src/Kernel/RecommendationManagerKernelTest.php
- modules/helfi_recommendations/tests/src/Kernel/TopicsManagerTest.php
- modules/helfi_recommendations/tests/src/Unit/RecommendationManagerTest.php
- src/Plugin/Field/FieldFormatter/TextSpan.php
This PR continues the base implementation for a recommendations block, that can fetch content recommendations from other instances as well.
- Finalise the block implementation (excluding final theming)
- Add configuration options to select:
- recommendation block visibility in current entity page
- instances to show recommendations from
- content types to show recommendations from 
- Fine tune the elasticsearch query
- Configure a JSON-API endpoint, and use it to fetch recommendation data for other instances.
- Add tests
- Still need to figure out how to avoid hitting annif API TPS-limit when processing the queue.
- Still need to figure out how to update index when keywords are generated.
- Still need to figure out translation handling.
- As the data needed for suggestion content is quite …
> UHF-11579: Recommendation block, part 2

- modules/hdbt_cookie_banner/src/Services/CookieSettings.php
- modules/hdbt_cookie_banner/tests/src/Kernel/Services/CookieSettingsTest.php
* Fixed typo from HDBT cookie banner service's `getActiveEtusivuEnvironment()` method and tested the method.
[UHF-11166]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11166: Cookie banner WSOD

- modules/helfi_image_styles/config/install/responsive_image.styles.square_thumbnail.yml
- modules/helfi_media/config/install/core.entity_view_display.media.image.square_thumbnail.yml
- modules/helfi_media/config/install/core.entity_view_mode.media.square_thumbnail.yml
- modules/helfi_paragraphs_contact_card_listing/config/install/core.entity_form_display.paragraph.contact_card.default.yml
- modules/helfi_paragraphs_contact_card_listing/config/install/core.entity_view_display.paragraph.contact_card.default.yml
- modules/helfi_paragraphs_contact_card_listing/config/install/field.field.paragraph.contact_card.field_contact_image.yml
- modules/helfi_paragraphs_contact_card_listing/config/install/field.field.paragraph.contact_card.field_contact_image_reference.yml
- modules/helfi_paragraphs_contact_card_listing/config/install/field.storage.paragraph.field_contact_image_reference.yml
- modules/helfi_paragraphs_contact_card_listing/config/install/field.storage.paragraph.field_email.yml
- modules/helfi_paragraphs_contact_card_listing/config/optional/language/fi/field.field.paragraph.contact_card.field_contact_image.yml
- modules/helfi_paragraphs_contact_card_listing/config/optional/language/fi/field.field.paragraph.contact_card.field_contact_image_reference.yml
- modules/helfi_paragraphs_contact_card_listing/config/optional/language/sv/field.field.paragraph.contact_card.field_contact_image.yml
- modules/helfi_paragraphs_contact_card_listing/config/optional/language/sv/field.field.paragraph.contact_card.field_contact_image_reference.yml
- modules/helfi_paragraphs_contact_card_listing/helfi_paragraphs_contact_card_listing.info.yml
* Added a new image field which is media reference for contact card listing 
* Made it possible to add multiple emails in one card
* Renamed responsive image style contact card to square thumbnail
Test for example in **KYMP** since there is a good paragraph already in the content
* `make fresh`
* `composer require drupal/hdbt:dev-UHF-11593`
* `composer require drupal/helfi_platform_config:dev-UHF-11593 `
* In the shell, run `drush helfi:platform-config:update helfi_media` and  `drush helfi:platform-config:update helfi_paragraphs_contact_card_listing` 
* …
> UHF-11593: Added new image field for contact card

- modules/helfi_test_content/assets/js/focus.js
* Changed the way focus styles are simulated; visual regression tests cannot render styles correctly. Added class instead of copying the focus styles to fix the issue.
> UHF-8792: Visual regression tests (focus)

- helfi_platform_config.install
Search API can't reach the elasticsearch server used for suggestion topics indexing in any environment other than local development. We need to wait until we get that routing to enable `helfi_recommendations` on all core instances, and we can then add the install hook again.
Update hook to enable `helfi_recommendations` was removed.
Maybe this is trivial enough to not need local testing?
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/946
[UHF-10647]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10647: Removing an install hook to enable helfi_recommendations

- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_language.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_language.yml
- modules/helfi_react_search/helfi_react_search.install
Change 'language' label to avoid clashing with existing translation.
> UHF-X: Fix language translation clash

- helfi_platform_config.module
* Switched the config ignore alter hook, and modified the operation list to permit the creation of new configurations during import phase.
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/1027
[UHF-11640]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11640: Config ignore update

- modules/helfi_recommendations/src/RecommendationManager.php
The elastic query was using a feature that was introduced in Elasticquery 8.10.0 (https://github.com/elastic/elasticsearch/pull/96082). Our local development stack covers this, but OpenShift is still on 8.0.0 so the query is failing there.
Query was updated to support 8.0.0.
Maybe we can confirm the new query format in Postman, and then test directly in the test environment?
- Create a POST request in Postman to url `https://etusivu-elastic-proxy-test.agw.arodevtest.hel.fi/suggestions/_search`
- Use the following json contents as raw request Body:
- Old, failing query: [old-query.json](https://github.com/user-attachments/files/20064977/old-query.json)
- New query: [new-query.json](https://github.com/user-attachments/files/20064982/new-query.json)
[UHF-10647]: …
> UHF-10647: Updating elastic query

- composer.json
- patches/drupal-3396318-status-message-bigpipe-mr-9329.patch
* Added patch to fix the status messages when bigpipe module is enabled.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11025`
* `composer install`
[UHF-11025]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11025: Status messages theme

- modules/hdbt_cookie_banner/assets/js/hdbt-cookie-banner.js
- modules/hdbt_cookie_banner/assets/js/unapproved-cookies.js
- modules/hdbt_cookie_banner/hdbt_cookie_banner.libraries.yml
- modules/hdbt_cookie_banner/hdbt_cookie_banner.module
* Separated the unapproved cookies functionality to its own file and added checks for running the initialisation only for the full document. Switched to use the contextual `settings` instead of the global `drupalSettings`.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11025`
* Check that there is no cache prevention in local.settings.php and that the aggregation is turned on
[UHF-11025]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11025 Cookie banner API calling issue

- modules/helfi_paragraphs_org_chart/src/OrgChartImporter.php
We want to use public URL so that paatokset generates publicly accessible URLs
for organizations. However, public URL does not work in local environment.
[UHF-11178]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11178: Fix org chart urls

- config/schema/helfi_platform_config.schema.yml
- helfi_platform_config.install
- helfi_platform_config.module
- `make fresh`
- `composer require drupal/helfi_platform_config:dev-UHF-11611`
- `drush updb`
- Add: `$settings['matomo_site_id'] = '123';` to your local.settings.php.
- Check that `window.drupalSettings.matomo_site_id` variable is set in Javascript.
[UHF-11611]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11611: Move matomo site id to settings.php

- modules/helfi_recommendations/helfi_recommendations.module
- modules/helfi_recommendations/tests/src/Functional/TopicSuggestionsMetaTagTest.php
* Added a meta tag with a comma separated list of suggested topic labels for current content.
* Make sure your etusivu instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11534`
* Test on a few different pages:
[UHF-11534]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11534: Suggested topics for Metatavu crawler

- modules/helfi_recommendations/helfi_recommendations.module
This PR updates the role machine name used for the temporary access check on recommendations block.
Maybe trivial enough to confirm in test environment?
[UHF-10647]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10647: Fixing the role name used for checking access to recommendations block

- patches/drupal-core-sort-storage-comparer-source-and-target-arrays.patch
* The asort() returns always true, so we cannot compare the asort in if statement.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11784 -W`
* `composer install`
* Run `make drush-cr drush-cim`
[UHF-11784]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11784: Patch fix

- modules/helfi_tpr_config/config/install/field.field.tpr_service.tpr_service.field_hide_errand_services.yml
* Changed the default value to 0 instead of 1
* Make sure your  **SOTE** instance is up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11924-default-value-fix`
* In the shell, run `drush helfi:platform-config:update helfi_tpr_config`
* 
[UHF-11924]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11924: Changed default value

- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_event_location.yml
- modules/helfi_react_search/config/install/field.field.paragraph.event_list.field_remote_events.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_event_location.yml
- modules/helfi_react_search/config/optional/language/fi/field.field.paragraph.event_list.field_remote_events.yml
- modules/helfi_react_search/helfi_react_search.module
* Disable remote event filter if location filter is selected and vice versa.
- See: https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/978
Find event_list paragraph or add one to a node.
* 
[UHF-9754]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9754: Event list paragraph states

- modules/helfi_react_search/helfi_react_search.install
- modules/helfi_recommendations/helfi_recommendations.install
* Unset `_info_file_ctime` for `helfi_recommendations` and `helfi_react_search` modules to fix the issues with obsolete interface translation server patterns.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-9754_translations`
[UHF-9754]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9754 Module translations paths

- modules/helfi_recommendations/src/RecommendationManager.php
Recommendation images in production do not work:
- https://www.hel.fi/fi/uutiset/helsinkilaisille-tarkea-meri-on-ollut-monen-omastadi-ehdotuksen-innoittaja
- https://www.hel.fi/fi/kaupunkiymparisto-ja-liikenne/pysakointi/pysakointipaikat-hinnat-ja-maksutavat/pysakoinnin-mobiilisovellusten-hintavertailu
The image url generation was assuming the indexed url is always a relative path, which is true in local development environments, but not in openshift. Added a check for absolute image url.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_recommendation-images`
* Edit file `public/modules/contrib/helfi_platform_config/modules/helfi_recommendati …
> UHF-X: Updating the way recommendation image url is built to support absolute urls

- composer.json
* Lock Drupal core to 10.4. CKEditor plugins will break in D10.5.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-12029_lock_core -W`
[UHF-12029]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-12029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-12029 Lock Drupal core to 10.4

- modules/helfi_paragraphs_news_list/helfi_paragraphs_news_list.install
The changes made to field_limit requires 2 production deployments. The first one created new field (field_news_limit) and copied the values from the old field (field_limit)
This one removes the old field_limit field.
- Remove the old field configuration + data + database tables.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-12028`
* Open sql-client `drush sqlc`
* Run `show tables;`
* The `paragraph__field_limit`should not exist any more
* The new `paragraph__field_news_limit` should be in the tables-list
* Running `drush cex` should delete the `news_list.field_limit` configuration
* Log in as admin
* Go edit …
> UHF-12028 Remove the old field_limit -field

- composer.json
* Don't update the `translatable_menu_link_uri` to 2.1.2 until the overridden options issue has been resolved.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11867 -W`
* `composer i`
[UHF-11867]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11867: Translatable menu link uri

- modules/helfi_paragraphs_contact_card_listing/src/SocialMediaServiceParserTrait.php
- modules/helfi_paragraphs_contact_card_listing/tests/src/Unit/SocialMediaServiceParserTraitTest.php
* Contact cards social media field had a special case for X that set the twitter logo to the card
* The special case was removed and now the correct X logo appears to the contact card
* Make sure your **ETUSIVU** instance is up and running on latest dev branch. Remove your dump from local since there's already good test content in etusivu test or you can create some if you don't want to remove the dump
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X-change-twitter-icon-to-x`
> UHF-X: Removed twitter special case from social media service parse trait

- modules/helfi_base_content/config/optional/language/fi/views.view.scheduler_scheduled_content.yml
- modules/helfi_tpr_config/config/install/views.view.locked_services.yml
- modules/helfi_tpr_config/config/install/views.view.unit_search.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.locked_services.yml
- modules/helfi_tpr_config/config/optional/language/fi/views.view.unit_search.yml
* Updated translations for views exposed form options buttons to prevent a reset of translations in automatic update pull requests.
[UHF-9855]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9855: Configuration translations

- helfi_platform_config.install
* Fix: `Drupal\content_lock\ContentLock\ContentLock::verbose(): Return value must be of type bool, null returned" at /var/www/html/public/modules/contrib/content_lock/src/ContentLock/ContentLock.php line 260`
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X-content_lock_config`
*
> Set content verbose config for content lock module

- modules/helfi_recommendations/helfi_recommendations.install
- modules/helfi_recommendations/helfi_recommendations.module
- modules/helfi_tpr_config/helfi_tpr_config.install
- modules/helfi_tpr_config/src/Entity/Service.php
In #1031 the field was added as a base field for `tpr_service`-entities, which is causing issues in sites where `helfi_recommendations` isn't enabled.
This PR removes the base field and reinstalls the field as a bundle field only when `helfi_recommendations`-module is enabled.
* Launch the frontpage instance (it's where the recommendation index lives)
* Make sure your other instance is up and running on latest dev branch. Use one of the instances with tpr-integration, like asuminen.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-12050_change_field`
* Generate recommendation keywords for testing:
* Run `drush helfi:recommendations:fix-references` to prime the field for …
> UHF-12050: Updating recommended topics field in tpr service

- modules/helfi_users/helfi_users.module
When deleting user, node_field_data, node_field_revision and node_revision are updated with uid = 1.
Cache is not invalidated on user deletion, making the edit page break for nodes owned by deleted user, until the cache is cleared.
Clear cache when user is deleted.
* This thing was fixed
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11997`
* Checkout some instance (for example  [strategia](https://github.com/City-of-Helsinki/drupal-helfi-strategia).
* Find a node owned by some user (for example …
> UHF-11997: When deleting user, node table is not updated correctly.

- modules/helfi_paragraphs_phasing/src/Entity/Phasing.php
Prevent [sentry error](https://sentry.hel.fi/organizations/city-of-helsinki/issues/76865/?project=97&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=8) when previewin node.
cast value to string
- Go and edit [this node](https://helfi-kymp.docker.so/fi/kaupunkiymparisto-ja-liikenne/node/323/edit), try previewing
Should whitescreen, getShowNumbers -method returns int (0) instead of string
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_int_to_string`
- Go and edit [this …
> prevent error when value is int

- modules/helfi_base_content/config/install/views.view.helfi_redirect.yml
- modules/helfi_base_content/config/optional/language/fi/views.view.helfi_redirect.yml
- modules/helfi_base_content/config/optional/language/sv/views.view.helfi_redirect.yml
* Refactored `helfi_redirect` view to use the new `enabled` field.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-X_helfi_redirect_views -W`
> UHF-X Helfi redirect views

- modules/helfi_recommendations/README.md
- modules/helfi_recommendations/helfi_recommendations.install
- modules/helfi_recommendations/helfi_recommendations.module
- modules/helfi_recommendations/helfi_recommendations.permissions.yml
- modules/helfi_recommendations/src/Plugin/Block/RecommendationsBlock.php
- modules/helfi_recommendations/src/Plugin/Field/FieldWidget/SuggestedTopicsReferenceWidget.php
- modules/helfi_recommendations/src/RecommendationManager.php
- modules/helfi_recommendations/src/RecommendationManagerInterface.php
- modules/helfi_recommendations/src/RecommendationsLazyBuilder.php
- modules/helfi_recommendations/src/RecommendationsLazyBuilderInterface.php
- modules/helfi_recommendations/tests/src/Functional/TopicSuggestionsMetaTagTest.php
- modules/helfi_recommendations/tests/src/Kernel/Plugin/Block/RecommendationsBlockKernelTest.php
- modules/helfi_recommendations/tests/src/Kernel/RecommendationManagerKernelTest.php
- modules/helfi_recommendations/tests/src/Unit/RecommendationManagerTest.php
- modules/helfi_recommendations/tests/src/Unit/RecommendationsLazyBuilderTest.php
* Removed temporary role based access restrictions, allowing the recommendation block to be visible to all users in all content types.
* Updated the recommendation search score visibility restriction from role to permission based.
* Hiding the recommendation block by default in kuva-instance.
* Updated documentation.
* Make sure your `etusivu` and `kuva` instances are up and running on latest dev branch.
* `make fresh`
* `composer require drupal/helfi_platform_config:dev-UHF-11798`
* After reaching this far in both instances, run `drush sapi-rt` in both, then `drush sapi-i suggestions` in both.
* Log in to https://helfi-kuva.docker.so
[UHF-11798]: …
> UHF-11798: Removing temporary access restrictions from content recommendations
